# Combination of Random Variables

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(webexercises)
```

## Introduction

A short introduction to the importance of this section is provided in this video (YouTube, 2min).

{{< video https://youtu.be/O_p2ToGLwyU >}}

We have, thus far, developed the concept of probability distributions for single continuous or discrete random variables. As we have seen, these distributions assign probabilities to various numerical values of the random variable under consideration. Further, for the distributions most commonly used in practice, mathematical expressions can be obtained for the mean and variance of this random variable in terms of the parameters of the distribution. For example, if $X$ is the number of successes in $n$ independent experiments in which the probability of success is $\pi$ (that is, $X$ follows a Binomial distribution with parameters $n$ and $\pi)$, then it was stated that $E[X]=n \pi$ and $Var(X)=n \pi(1-\pi)$. 

A binomial random variable is actually a special case of a combination of random variables. For this case we have already learned how to calculate its mean and variance.

In this section we will learn how to derive and calculate the expected value and variance of any combination of random variables. This is extremely important as in practice we are often interested in the outcomes of a combination of random variables. In order to build up to these results we will firstly learn about transformations of individual random variables and how they affect their properties. You will then learn how ot derive some properties of linear combinations of multiple random variables. Finally you will learn about the special case of linear combinations of normally distributed random variables.


## Linear Transformations

Before extending the ideas, recall the definitions of mean and variance as expected values.

### Means and variances: a recap

Recall that the mean, or the expected value of a random variable $X$, is commonly denoted as either $E[X]$ or $\mu$. For a discrete random variable, the mean is defined as

\begin{equation*}
	E[X]=\mu=\sum_{x} x p(x) .
\end{equation*}

If the variable is continuous, the analogous definition is

\begin{equation*}
E[X]=\mu=\int_{-\infty}^{\infty} x f(x) dx 
\end{equation*}

The variance of a random variable, which provides a measure of the spread of the possible outcomes around the mean, is also defined as an expected value, namely:

\begin{eqnarray*}
	\operatorname{var}[X] &=&E\left[(X-\mu)^{2}\right] \\
	&=&\sum_{x}(x-\mu)^{2} p(x) \text{ discrete } \\
	&=&\int_{-\infty}^{\infty}(x-\mu)^{2} f(x) dx  \text{ continuous }
\end{eqnarray*}

However, for the distributions which were introduced (e.g. the binomial distribution or the normal distribution) we also learned how the mean and variance were related to the parameters that described these distributions.


## Linear transformations of random variables

Often, information is available about a random variable in one form, but we require this to be converted into another form via a linear transformation. Changing units of measurement provides an important example of this: prices may be expressed in UKP and converted to Euros at a specific exchange rate, or temperatures can be expressed in fahrenheit or celsius.

In fact we already encountered a linear transformation. That from a normally distributed random variable $X$ (where $X \sim N(\mu, \sigma^2)$)  to a standard normal distribution $Z$ (where $Z \sim N(0, 1)$). The way we did transform this was according to 

\begin{equation*}
	Z = \frac{X-\mu}{\sigma} = \frac{1}{\sigma}X-\frac{\mu}{\sigma}
\end{equation*}

the last term illustrating that the transformation is a linear one with a multiplicative factor $\frac{1}{\sigma}$ (like a slope coefficient)and a shift factor $-\frac{\mu}{\sigma}$ (like a constant). Let's learn from that example how the properties of a linear transformation of a random variable (rv) are related to those of the original rv. 

Let's consider the following linear transformation

\begin{equation*}
	Z = c + bX
\end{equation*}

where $X$ is a random variable with $E[X]=\mu$ and $Var[X] = \sigma^2$. $c$ and $b$ are constants. $Z$ is what we call a linear transformation of $X$.

We have the following results:

\begin{enumerate}
	\item $E[Z]=E[b X+c]=b E[X]+c$
	\item $Var[Z]=Var[b X+c]=b^{2} Var[X]$
\end{enumerate}  

For the discrete random variable case the algebra of the proof is very straightforward:

\begin{eqnarray*}
	E[b X+c] &=&\sum_{x}(b x+c) p(x) \\
	&=&\sum_{x}(b x p(x)+c p(x)) \\
	&=&b \sum_{x} x p(x)+c \sum_{x} p(x) \\
	&=&b E[X]+c,
\end{eqnarray*}

since $\sum_{x} p(x)=1$ (i.e. all probabilities sum to 1) and $\sum_{x} x p(x)=E[X]$, by definition of the expected value for a discrete random variable.

We learn that any multiplicative constant, like $b$ here, can be moved outside of the expectations operator, $E[]$ . This applies also to continuous variables, because corresponding operations carry over when integrals replace the summations above.

To calculate the variance of a linearly transformed rv we can ignore any level shift (the addition of $c$) and we can draw the multiplicative constant ($b$) outside of the variance operator, $Var[]$, but need to square it. Here we will not present any proof for that result. It can be derived using similar, but more involved arguments, as for the expected value.

These relationships between the original rv $X$ and its linear transform $Z$ are generally valid, regardless of how the variable $X$ is distributed.



::: {.callout-important}

#### Confirming the above result

Let us confirm that these relationships hold when we transform any normally distributed rv $X$ (where $X \sim N(\mu, \sigma^2)$)  to a standard normal distribution $Z$ (where $Z \sim N(0, 1)$). As discussed above, the linear transform used is
	
\begin{equation*}
	Z = \frac{X-\mu}{\sigma} = \frac{1}{\sigma}X-\frac{\mu}{\sigma}
\end{equation*}

So, here $c=-\frac{\mu}{\sigma}$ and $b= \frac{1}{\sigma}$. Let us apply the formulae established above:
	
\begin{eqnarray*}
		E[Z]&=&E[b X+c]\\
		&=& b E[X]+c\\
		&=& \frac{1}{\sigma} E[X] + (-\frac{\mu}{\sigma})\\
		&=& \frac{1}{\sigma} \mu + (-\frac{\mu}{\sigma})\\
		&=& \frac{\mu}{\sigma}  - \frac{\mu}{\sigma}= 0
\end{eqnarray*}

So indeed the expected value is $E[Z]=0$. 

\begin{eqnarray*}
		Var[Z]&=&Var[b X+c]\\
		&=& b^2 Var[X]\\
		&=& \left(\frac{1}{\sigma}\right)^2 Var[X] \\
		&=& \left(\frac{1}{\sigma}\right)^2 \sigma^2 \\
		&=& \frac{\sigma^2}{\sigma^2} = 1
\end{eqnarray*}

we have therefore established that $Var[Z]=1$, confirming the result we had previously just stated.

:::


There is also another element to complement the above result: namely, if $X$ has the form of a normal random variable, then so has $Z$. Indeed, this is a very powerful result concerning linear transformations of normal variables, which we simply state.

::: {.callout-important}

## Linear transormations of normal rvs are normal again

If $X \sim N(\mu, \sigma^2)$ then $Y=bX+c \sim N(b\mu+c,b^2\sigma^2)$ for constants $b$ and $c$.


This result that the form of the distribution does not change is specific to the normal distribution: for example, a linear transformation of a Binomial variable is not itself (generally) Binomial.

:::


::: {.callout-info}

#### Example

Playing a game by rolling fair die. If it costs 10p to play, and the player receives (in pence) double the number thrown, then expected winnings per game (measured in p) are `r fitb(-3)`p.

`r hide("Solution")`

\begin{equation*}
		E[2 X-10]=2 \times(3.5)-10=-3 .
\end{equation*}
	
Recognising that the expected value of rolling a fair dice is ‌E[X]=3.5. Hence a player is expected to lose ‌3p every time they play this game.

`r unhide()`

:::

::: {.callout-note icon=false}

#### Exercise

You flip a fair coin three times and the random variable ‌X records how many times the coin shows HEAD. You convince your friend that he should play a game with the following payoff. Every round (equivalent to three coin flips) will cost £1. He will receive £ 0.5 for every coin showing HEAD.

What type of random variable is $X$? 

`r mcq(c("normally distributed",answer = "binomially distributed","poisson distributed","uniformly distributed"))`
	
What are the expected value and variance of X?

$E[X] =$ `r fitb(1.5)`

$Var[X] =$ `r fitb(0.75)` 

`r hide("Solution")`
$E[X]= 3 \times 0.5 = 1.5$

$Var[X]= 3 \times 0.5 \times (1-0.5) = 0.75$
`r unhide()`

What is the expected value and the variance of the random variable $Y=0.5 \cdot X−1$?

$E[X] =$ `r fitb(-0.25)`

$Var[X] =$ `r fitb(0.1875)` 


`r hide("Solution")`
$E[Y]=0.5 \cdot E[X] - 1 = 0.5 \cdot 1.5 - 1 = -0.25$

$Var[Y]=0.5^2 \cdot Var[X] = 0.25 \cdot 0.75 = 0.1875$
`r unhide()`


:::

## Joint Probability Distributions

You would have already learned about correlations as a descriptive statistics. We discussed how to use correlation and regression to summarise the extent and nature of any linear relationship between two variables. Examples of variables we used in that earlier section were: Covid case rates and health expenditure for countries; height and weight of people; maths and stats grades for students.

Let's take that last example of students' grades in Advanced Mathematics and Statistics. You can think about this as two random variables, $M$ and $S$ for the maths and stats grade respectively.

The objective of much of statistics is to learn about population characteristics. An experiment is then any process which generates data. Just imagine we go into a second year class and we ask all students what grades they received in Maths and Stats in Year 1. These two pieces of information, generated by the experiment, are considered to be the values of two random variables ($M$ and $S$) defined on the sample space of an experiment (see the intro to probability section), then the discussion of random variables and probability distributions needs to be extended to the multivariate case. In the first instance to that of two variables, but eventually also to higher dimensions.

Let $X$ and $Y$ be the two random variables: for simplicity, they are considered to be discrete random variables. The outcome of the experiment is a pair of values $\left( x,y\right)$. The probability of this outcome is a joint probability which can be denoted

\begin{equation*}
	\Pr \left( X=x\cap Y=y\right) ,
\end{equation*}

emphasising the analogy with the probability of a joint event $\Pr \left( A\cap B\right)$, or, more commonly, by

\begin{equation*}
	\Pr \left( X=x,Y=y\right) .
\end{equation*}

The collection of these probabilities, for all possible combinations of $x$ and $y$, is the **joint probability distribution** of $X$ and $Y$, denoted

\begin{equation*}
	p\left( x,y\right) =\Pr \left( X=x,Y=y\right).
\end{equation*}

The **Axioms of Probability** discussed in the Introduction to Probability Section carry over to imply

* any possible event has a non-negative probability (but not larger than 1)  
	\begin{equation*}
		0\leqslant p\left( x,y\right) \leqslant 1,
	\end{equation*}
* The sum of all mutually exclusive $\left( x,y\right)$ combinations is calculated as the sum of the individual probabilities  
	\begin{equation*}
		\sum_{x}\sum_{y}p\left( x,y\right) =1,
	\end{equation*}  
	and delivers a probability of 1. This implies that it is certain that one of the possible outcomes does occur.



::: {.callout-info}

#### Example

Let $H$ and $W$ be the random variables representing the population of weekly incomes of two partners living in a household together, in some country. $H$ represents the income of the older partner and  $W$ the income of the younger partner. There are only three possible weekly incomes, UKP 0, UKP 100 or UKP 200. The joint probability distribution of $H$ and $W$ is represented as a table:


|                |                | $H$    |          |        |
|----------------|----------------|--------|----------|--------|
| Probabilities  |                | UKP 0  | UKP 100  | UKP 200 |
| Values of $W:$ | UKP 0          | $0.05$ | $0.15$   | $0.10$ |
|                | UKP 100        | $0.10$ | $0.10$   | $0.30$ |
|                | UKP 200        | $0.05$ | $0.05$   | $0.10$ |

Then we can read off, for example, that

\begin{equation*}
	\Pr \left( H=0,W=0\right) =0.05,
\end{equation*}

or that in this population, $5\%$ of households have zero weekly income for both partners.

In this example, the nature of the experiment underlying the population data is not explicitly stated, meaning that all we know are these empirical probabilities. Sometimes we say that we do not know the data generating process.

:::


::: {.callout-note icon=false}

#### Exercise

What are the following probabilities? (where we now, for simplicity, represent UKP 100 by 1).

* $Pr\left( H=1,W=0\right) =0.15$
* $Pr\left( H=2,W=1\right) =0.30$
* $Pr\left( H=2,W=2\right) =0.10$

The probability that $H=1$ is $Pr(H=1) =$ `r fitb(0.3)`.

`r hide("Solution")`
$Pr(H=1) = Pr(H=1, W=0) + Pr(H=1, W=0) +Pr(H=1, W=0) = 0.30$
`r unhide()`

:::


::: {.callout-info}

#### Example

Consider the following simple version of a lottery. Players in the lottery randomly choose one of 100 tickets which show numbers between $1$ and $5$, whilst a machine selects the lottery winners by randomly selecting one of five balls (numbered $1$ to $5$). Any player whose drawn number on a ticket coincides with the number on the ball is a winner. The machine selects one ball at random (so that each ball has an 0.2 chance of selection). The 100 tickets from which the players draw contain the numbers 1 to 5 with the following probabilities:

| Number chosen by player | Probability of being chosen |
|-------------------------|-----------------------------|
| $1$                     | $0.40$                      |
| $2$                     | $0.20$                      |
| $3$                     | $0.05$                      |
| $4$                     | $0.10$                      |
| $5$                     | $0.25$                      |
| **Total**               | $1.0$                       |

Let $X$ denote the number on the player's chosen and $Y$ the number chosen by the machine. If they are assumed to be independent events, then for each possible value of $X$ and $Y$, we will have

\begin{equation*}
	\Pr \left( X\cap Y\right) =\Pr \left( X\right) \Pr \left( Y\right) .
\end{equation*}

The table above gives the probabilities for $X$, and $\Pr \left( Y = y\right) =0.2$ for all $y=1,...,5$, so that a table can be drawn up displaying the joint distribution $p\left( x,y\right)$. \\For example $p(3,4)=Pr(X=3) \cdot Pr(Y=4) =0.05 \cdot 0.20 = 0.01$.

| Probabilities |  machine ($Y$) |       |      |      |      |              |
|---------------|----------------|-------|------|------|------|--------------|
| player ($X$)  | $1$            | $2$   | $3$  | $4$  | $5$  | Row Total    |
| 1             | `r fitb(0.08)` | `r fitb(0.08)`  | `r fitb(0.08)` | 0.08 | `r fitb(0.08)` | $\textcolor{orange}{0.40}$ |
| 2             | 0.04           | 0.04  | 0.04 | 0.04 | `r fitb(0.04)` | $\textcolor{orange}{0.20}$ |
| 3             | 0.01           | `r fitb(0.01)`  | 0.01 | 0.01 | `r fitb(0.01)` | `r fitb(0.05)` |
| 4             | 0.02           | `r fitb(0.02)`  | 0.02 | 0.02 | `r fitb(0.02)` | `r fitb(0.10)` |
| 5             | 0.05           | 0.05  | 0.05 | 0.05 | `r fitb(0.05)` | `r fitb(0.25)`|
| Column Total  | `r fitb(0.20)` | `r fitb(0.20)` | `r fitb(0.20)` | `r fitb(0.20)` | $\textcolor{blue}{0.20}$ | 0.20                   |

`r hide("Hint")`

Use the knowledge about marginal probabilities to complete the table. 
`r unhide()`

You may think that making the probabilities of the numbers on the tickets uneven was somewhat strange. That does mimic a very real issue. When people choose numbers (e.g. for lottery tickets or for passwords) they do not choose random numbers, they choose "lucky" numbers. Lucky numbers are often dates (birthdays, wedding days, etc.). That implies that people choose numbers from 1 - 12 and again numbers from 1 - 31 more often than numbers that are larger than 31. If you do choose such "lucky" numbers you are not less likely to win, but if you win you will have to share the prize with more people!

Make sure you understand how the joint probabilities are calculated, using your knowledge that $X$ and $Y$ are independent?
	
* $p\left( 2,1\right) = Pr(X=2) \cdot Pr(Y=1) = 0.20 \cdot 0.20 = 0.04$
* $p\left( 4,3\right) =$ `r fitb(0.02)`
* $p\left( 5,5\right) =$ `r fitb(0.05)`

:::



