<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Confidence Intervals – Statistics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./RegressionInference.html" rel="next">
<link href="./HypothesisTesting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ConfidenceIntervals.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphical_descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CorrelationRegressionCausation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DealingWithDataSets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dealing with real life datasets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IntroToProbability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introducing Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ConditionalProbability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DiscreteRVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete Random Variables and Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ContinuousRVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Random Variables and Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Normal_RV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normally Distributed Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Comb_of_RVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Combination of Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sampling_Dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./HypothesisTesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ConfidenceIntervals.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegressionInference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-point-and-interval-estimation" id="toc-introduction-to-point-and-interval-estimation" class="nav-link active" data-scroll-target="#introduction-to-point-and-interval-estimation"><span class="header-section-number">15.1</span> Introduction to Point and Interval Estimation</a>
  <ul class="collapse">
  <li><a href="#sampling-variability" id="toc-sampling-variability" class="nav-link" data-scroll-target="#sampling-variability"><span class="header-section-number">15.1.1</span> Sampling Variability</a></li>
  <li><a href="#interpreting-confidence-intervals" id="toc-interpreting-confidence-intervals" class="nav-link" data-scroll-target="#interpreting-confidence-intervals"><span class="header-section-number">15.1.2</span> Interpreting Confidence Intervals</a></li>
  <li><a href="#other-confidence-levels" id="toc-other-confidence-levels" class="nav-link" data-scroll-target="#other-confidence-levels"><span class="header-section-number">15.1.3</span> Other Confidence Levels</a></li>
  <li><a href="#which-distribution-to-use" id="toc-which-distribution-to-use" class="nav-link" data-scroll-target="#which-distribution-to-use"><span class="header-section-number">15.1.4</span> Which distribution to use?</a></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources"><span class="header-section-number">15.1.5</span> Additional Resources</a></li>
  </ul></li>
  <li><a href="#confidence-intervals-for-population-proportions" id="toc-confidence-intervals-for-population-proportions" class="nav-link" data-scroll-target="#confidence-intervals-for-population-proportions"><span class="header-section-number">15.2</span> Confidence intervals for population proportions</a>
  <ul class="collapse">
  <li><a href="#additional-resources-1" id="toc-additional-resources-1" class="nav-link" data-scroll-target="#additional-resources-1"><span class="header-section-number">15.2.1</span> Additional resources</a></li>
  <li><a href="#opinion-polling-reality" id="toc-opinion-polling-reality" class="nav-link" data-scroll-target="#opinion-polling-reality"><span class="header-section-number">15.2.2</span> Opinion polling reality</a></li>
  </ul></li>
  <li><a href="#summary-and-outlook" id="toc-summary-and-outlook" class="nav-link" data-scroll-target="#summary-and-outlook"><span class="header-section-number">15.3</span> Summary and Outlook</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction-to-point-and-interval-estimation" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="introduction-to-point-and-interval-estimation"><span class="header-section-number">15.1</span> Introduction to Point and Interval Estimation</h2>
<p>In the section on sampling distribution we established the link between population parameters and their sample estimators, in particular the link between the population mean and its sample average. In the Section on Hypothesis Testing we then established a particular technique (hypothesis testing) we can use when we want to learn from a (known) sample something about the unknown population parameter. Of course, different samples will yield different estimates of the population parameter: this is the idea of <strong>sampling variability</strong>. It is because of this sampling variability that hypothesis testing could only make probabilistic statements.</p>
<p>In this section we will learn about an alternative (yet linked) way to express the uncertainty arising from sampling variability. Confidence intervals are a popular tool to communicate this uncertainty, one which, in some respects, may deliver a more intuitive way of presenting the uncertainty we are facing (YouTube, 2min)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/qZDKiUmtpP4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<section id="sampling-variability" class="level3" data-number="15.1.1">
<h3 data-number="15.1.1" class="anchored" data-anchor-id="sampling-variability"><span class="header-section-number">15.1.1</span> Sampling Variability</h3>
<p>Let’s recall the link between population parameter (here population mean <span class="math inline">\(\mu\)</span>) and sample statistic (here sample mean <span class="math inline">\(\bar{X}\)</span>). Consider the simplest case of sampling from a normal distribution, $XN( ,^{2}) $ with the intention of estimating $$. The obvious estimator is the sample mean, <span class="math inline">\(\bar{X}\)</span>, with sampling distribution <span class="math inline">\(\bar{X}\thicksim N\left( \mu ,\sigma^{2}/n\right)\)</span>. Here, <span class="math inline">\(\mu\)</span> is unknown but for now we assume that <span class="math inline">\(\sigma ^{2}\)</span> is known.</p>
<p>The variance of the distribution of <span class="math inline">\(\bar{X}\)</span> measures the dispersion of this distribution, and thus gives some idea of the range of values of <span class="math inline">\(\bar{X}\)</span> that might be obtained in drawing different samples of size <span class="math inline">\(n\)</span>. This measure, <span class="math inline">\(\sigma^2_{\bar{X}}=\sigma^2/n\)</span>, is therefore a measure of sampling variability and can be combined with the actual sample estimate, <span class="math inline">\(\bar{x}\)</span>, in the following way:</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm k \sigma_{\bar{X}} ,
\end{equation*}\]</span></p>
<p>with the value <span class="math inline">\(k\)</span> chosen suitably (we will get to that later). What we get from this is an interval that is centred around the sample mean <span class="math inline">\(\bar{x}\)</span>. The actual (unknown) population mean will or will not be contained in this interval, we just don’t know.</p>
<p>So how could such an interval be useful? Before we get to this, let’s calculate a <strong>related but different</strong> interval we were able to calculate following our understanding of sampling distributions.</p>
<p>Assume that <span class="math inline">\(X \sim N(7,9)\)</span> and that you draw a sample of size <span class="math inline">\(n=20\)</span>. Then we can calculate the probability that <span class="math inline">\(\Pr(5.685 \leq \bar{X} \leq 8.314)\)</span>. To calculate this we use our knowledge that <span class="math inline">\(\bar{X} \sim N(7,9/20)\)</span> which then allows us to calculate the value of that probability to be</p>
<p><span class="math display">\[\begin{eqnarray*}
    \Pr(5.685 \leq \bar{X} \leq 8.314) &amp;=&amp; \Pr\left(\frac{5.685-7}{\sqrt{9/20}} \leq Z \leq \frac{8.314-7}{\sqrt{9/20}}\right)\\
    &amp;=&amp; \Pr\left(\frac{5.685-7}{\sqrt{9/20}} \leq Z \leq \frac{8.314-7}{\sqrt{9/20}}\right)\\
    &amp;=&amp; \Pr\left(-1.96 \leq Z \leq 1.96\right) = 0.95
\end{eqnarray*}\]</span></p>
<p>where you can get the probability from the normal probability table. So, if we knew that the population mean was 7, then we would expect that with a 95% probability we would get a sample mean between 5.685 and 8.314. Where did these two values actually come from? They were calculated from</p>
<p><span class="math display">\[\begin{equation*}
    \mu \pm k \sigma_{\bar{X}}
\end{equation*}\]</span></p>
<p>where we used <span class="math inline">\(\sigma^2_{\bar{X}}=9/20\)</span> and <span class="math inline">\(k=1.96\)</span> value as that is the value in the standard normal distribution that cuts off 2.5% in each tail. This is the interval into which, with a 95% probability we should expect the sample mean to fall, <strong>if we knew</strong> the population mean (<span class="math inline">\(\mu=7\)</span>).</p>
<p>Of course we do not know the population mean in most interesting applications and all we have is a sample mean <span class="math inline">\(\bar{x}\)</span>. Can we just replace the unknown population mean <span class="math inline">\(\mu\)</span> with <span class="math inline">\(\bar{x}\)</span>? Yes we can, that is how we get to</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm k \sigma_{\bar{X}} ,
\end{equation*}\]</span></p>
<p>If we again chose the <span class="math inline">\(k=1.96\)</span> we call this the 95% confidence interval for the population mean. Continuing with the example we now learn that we obtained a sample mean of 7.931. This now allows us to calculate a 95% confidence interval</p>
<p><span class="math display">\[\begin{equation*}
    7.931 \pm 1.96 \cdot \sqrt{9/20} \Rightarrow [6.2031,9.6589]
\end{equation*}\]</span></p>
<p>What interpretation can we give this confidence interval with lower limit/bound <span class="math inline">\(c_L = 6.2031\)</span> and upper limit/bound <span class="math inline">\(c_U=9.6589\)</span>? An intuitive interpretation would be “There is a 95% probability that the population mean is inside this interval.” Unfortunately that is an incorrect interpretation. This interpretation treats the unknown population mean as if it was a random variable, but it is not. It is assumed to be fixed but unknown. What is random is the outcome of the sample mean <span class="math inline">\(\bar{x}\)</span> and therefore the confidence interval (as the lower and upper limits, <span class="math inline">\(c_L\)</span> and <span class="math inline">\(c_U\)</span>, of that interval are centred around the particular outcome <span class="math inline">\(\bar{x}=7.931\)</span> of the random variable <span class="math inline">\(\bar{X}\)</span> these limits are also random variables, <span class="math inline">\(C_L\)</span> and <span class="math inline">\(C_U\)</span>). Recall, capital letters represent the random variable (like <span class="math inline">\(C_L\)</span>) and small letters represent sample draws of that random variable (e.g.&nbsp;<span class="math inline">\(c_L\)</span>).</p>
<p>Therefore, the correct interpretation is the following. If you did take 100 samples, then 95% of the associated confidence intervals should contain the population mean, <span class="math inline">\(\mu\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose that a random sample of size <span class="math inline">\(50\)</span> is drawn from the distribution of household incomes, where the latter is supposed to be <span class="math inline">\(N\left( \mu ,5\right)\)</span>, and that the mean of the sample is <span class="math inline">\(\bar{x}=18\)</span>. If we choose k=1.96, the 95% confidence interval is</p>
<p><span class="math display">\[\begin{equation*}
    18 \pm 1.96 \cdot \sqrt{5/50} \Rightarrow [17.3802,18.6198]
\end{equation*}\]</span></p>
<p>If you were to calculate the 99% confidence interval, the interval would</p>
<p><select class="webex-select"><option value="blank"></option><option value="">stay unchanged</option><option value="answer">become wider</option><option value="">become narrower</option></select></p>
<p>If you increased the sample size, the interval would</p>
<p><select class="webex-select"><option value="blank"></option><option value="">stay unchanged</option><option value="">become wider</option><option value="answer">become narrower</option></select></p>
</div>
</div>
</section>
<section id="interpreting-confidence-intervals" class="level3" data-number="15.1.2">
<h3 data-number="15.1.2" class="anchored" data-anchor-id="interpreting-confidence-intervals"><span class="header-section-number">15.1.2</span> Interpreting Confidence Intervals</h3>
<p>This interval is defined by the sample values of <span class="math inline">\(C_{L}\)</span> and <span class="math inline">\(C_{U}\)</span>: these are the lower and upper confidence bounds and they have sample realisations:</p>
<p><span class="math display">\[\begin{equation*}
    c_{L}=\bar{x}-1.96SE\left( \bar{X}\right) ,\;\;\;c_{U}=\bar{x}+1.96 SE\left( \bar{X}\right) .
\end{equation*}\]</span></p>
<p>The interval estimate</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm 1.96SE\left( \bar{X}\right)
\end{equation*}\]</span></p>
<p>contains the measure of sampling variability (<span class="math inline">\(SE\left( \bar{X}\right)=\sigma_{\bar{X}}\)</span>).</p>
<p>The choice of <span class="math inline">\(k\)</span> as <span class="math inline">\(k=1.96\)</span> is now determined by the desired confidence level. Why choose the latter to be 0.95 or 95%? This is really a matter of convention and you will often also see 90% or 99% confidence intervals.</p>
<p>It is a common abuse of language to call the interval</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm 1.96SE\left( \bar{X}\right)
\end{equation*}\]</span>%</p>
<p><strong>the</strong> confidence interval - indeed it is so common that this abuse will be allowed. Strictly, this is <strong>an</strong> interval estimate, which is now seen to be a combination of a point estimate, <span class="math inline">\(\bar{x}\)</span>, of <span class="math inline">\(\mu\)</span>, and a measure of sampling variability determined by the constant <span class="math inline">\(k\)</span>, which sets the confidence coefficient or level, in this case, 0.95.</p>
<p>There is a common misinterpretation of a confidence interval, based on this abuse of language, which says that <strong>the confidence interval</strong></p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm 1.96SE\left( \bar{X}\right)
\end{equation*}\]</span></p>
<p><strong><span class="math inline">\(\mu\)</span> 95% confidence</strong>. Why is this a misinterpretation? For the following reasons:</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is unknown but not random</li>
<li>so this “confidence interval” does or does not contain <span class="math inline">\(\mu\)</span>;</li>
<li>since <span class="math inline">\(\mu\)</span> is unknown, we will <strong>never</strong> know whether a particular conficence interval does or does not contain <span class="math inline">\(\mu\)</span>;</li>
</ul>
<p>A better interpretation is based on the relative frequency interpretation of probability. If samples are repeatedly drawn from the population, say <span class="math inline">\(X\thicksim N\left( \mu ,\sigma ^{2}\right)\)</span>, and the interval estimates (“confidence interval”) for a 95% confidence level calculated for each sample, about 95% of them will contain <span class="math inline">\(\mu\)</span>.</p>
<p>This video illustrates this interpretation using a simple Excel simulation (YouTube, 11 min)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Uby0i8GcJww" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>You can get the spreadsheet used from <a href="data/Simulatedconfidenceintervals.xlsx">here</a></p>
<p>The image illustrates thirty 90% confidence intervals from a population with mean 7. Of these two confidence intervals do not include the true population mean (they are highlighted in red).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ConfInt.png" class="img-fluid figure-img"></p>
<figcaption>Illustration of confidence intervals. 30 confidence interval which are centred around the point estimate <span class="math inline">\(\bar{x}\)</span> represented by grey dots. <span class="math inline">\(c_L\)</span> and <span class="math inline">\(c_U\)</span> are in blue. The yellow line indicates the population mean, <span class="math inline">\(\mu=7\)</span>. The red confidence intervals are the ones which do not contain the population mean</figcaption>
</figure>
</div>
<p>However, this doesn’t help when only a single sample is drawn. You just don’t know whether that particular confidence interval does, or does not contain the true population mean. The way you should really interpret a particular confidence interval is that it shows a point estimate (<span class="math inline">\(\bar{x}\)</span>) of what you wish to estimate and displays the amount of sampling uncertainty.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose that a random sample of size 50 is drawn from the distribution of household incomes, where the latter is supposed to be <span class="math inline">\(N\left( \mu ,5\right)\)</span>. Notice that <span class="math inline">\(\sigma ^{2}\)</span> here is supposed to be <strong>known</strong> to equal 5. Suppose that the mean of the sample is <span class="math inline">\(\bar{x}=18\)</span>. Then, the 95% confidence interval for <span class="math inline">\(\mu\)</span> is (allowing the abuse of language)</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm 1.96SE\left( \bar{X}\right) &amp;=&amp;18\pm 1.96\sqrt{\dfrac{5}{50}} \\
    &amp;=&amp;18\pm 0.62 \\
    &amp;=&amp;\left[ 17.38,18.62\right] .
\end{eqnarray*}\]</span></p>
<p>Here the measure of sampling variability around <span class="math inline">\(\bar{x}=18\)</span> is <span class="math inline">\(\pm 0.62\)</span>. One might reasonably conclude that since this measure of sampling variability is small compared to <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\bar{x}=18\)</span> is a relatively precise estimate of <span class="math inline">\(\mu\)</span>. To refer to <strong>precision</strong> here is fair, since we are utilising the variance of the sampling distribution of <span class="math inline">\(\bar{X}\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of size 20 is drawn from the distribution of household savings (measured in 1000s of UKP, negative numbers mean that a household is in debt), where the latter is supposed to be <span class="math inline">\(N\left( \mu ,9\right)\)</span>. Notice that <span class="math inline">\(\sigma ^{2}\)</span> here is supposed to be <strong>known</strong> to equal 9. Your sample mean is <span class="math inline">\(\bar{x}=-12\)</span>. Then, the 95% confidence interval for <span class="math inline">\(\mu\)</span> is</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm 1.96~SE\left( \bar{X}\right) &amp;=&amp;-12\pm 1.96\sqrt{\dfrac{9}{20}} \\
    &amp;=&amp;-12\pm 1.2003 \\
    &amp;=&amp;\left[ -13.2002,-10.7998\right] .
\end{eqnarray*}\]</span></p>
<p>How big should your sample be such that the measure of sampling variability (<span class="math inline">\(1.96~SE\left( \bar{X}\right)\)</span>) is smaller than 1?</p>
<p><span class="math inline">\(n\)</span> should be at least <input class="webex-solveme nospaces" size="2" data-answer="[&quot;35&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math inline">\(1.96~SE\left( \bar{X}\right)=1.96 \cdot \sqrt{\frac{\sigma^2}{n}}&lt;1\)</span>. Either try in Excel which value does reduce this value below 1, or solve the inequality to get <span class="math inline">\(n&gt;1.96^2 \cdot \sigma^2\)</span> which here delivers that the smalles <span class="math inline">\(n\)</span> that achieves that is 35.</p>
<p>This video goes through the workings required in the above example (YouTube, 10min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/ljPZY9Q41WE" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
</div>
</div>
</section>
<section id="other-confidence-levels" class="level3" data-number="15.1.3">
<h3 data-number="15.1.3" class="anchored" data-anchor-id="other-confidence-levels"><span class="header-section-number">15.1.3</span> Other Confidence Levels</h3>
<p>Instead of choosing <span class="math inline">\(k\)</span> so that</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( -k\leqslant \dfrac{\bar{X}-\mu }{SE\left( \bar{X}\right) }\leqslant k\right) =0.95,
\end{equation*}\]</span></p>
<p>we can choose <span class="math inline">\(k\)</span> such as to deliver any desired probability, usually expressed as <span class="math inline">\(1-\alpha\)</span>:</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( -k\leqslant \dfrac{\bar{X}-\mu }{SE\left( \bar{X}\right) }\leqslant k\right) =1-\alpha
\end{equation*}\]</span></p>
<p>Since</p>
<p><span class="math display">\[\begin{equation*}
    Z=\dfrac{\bar{X}-\mu }{SE\left( \bar{X}\right) }\thicksim N\left(0,1\right) ,
\end{equation*}\]</span></p>
<p>we can find from the table of the standard normal distribution the value (percentage point) <span class="math inline">\(z_{\alpha /2}\)</span> such that</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( Z&gt;z_{\alpha /2}\right) =\dfrac{\alpha }{2}.
\end{equation*}\]</span></p>
<p>This implies that</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( -z_{\alpha /2}\leqslant Z\leqslant z_{\alpha /2}\right) =1-\alpha.
\end{equation*}\]</span></p>
<p>This is clear from the familiar picture in the Figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/norm01.jpg" class="img-fluid figure-img"></p>
<figcaption>Illustration of how to find the value <span class="math inline">\(k\)</span>.</figcaption>
</figure>
</div>
<p>This delivers the following, commonly used values, to calculate confidence intervals assuming that the sample mean follows a normal distribution (as it does when the population is normal and the population variance is known):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\alpha\)</span></th>
<th><span class="math inline">\(k=z_{\alpha/2}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.20</td>
<td>1.28</td>
</tr>
<tr class="even">
<td>0.10</td>
<td>1.65</td>
</tr>
<tr class="odd">
<td>0.05</td>
<td>1.96</td>
</tr>
<tr class="even">
<td>0.01</td>
<td>2.58</td>
</tr>
</tbody>
</table>
<p>If we were to chose <span class="math inline">\(\alpha = 0.01\)</span> the confidence interval’s lower and upper confidence bounds for the earlier example (population normally distributed with <span class="math inline">\(\sigma^2=5\)</span>, sample size <span class="math inline">\(n=50\)</span> and sample mean <span class="math inline">\(\bar{x}= 18\)</span> ) would be calculated as:</p>
<p><span class="math display">\[\begin{eqnarray*}
    \left[ c_{L},c_{U}\right] &amp;=&amp;\bar{x}\pm z_{\alpha /2}SE\left( \bar{X}\right) \\
    &amp;=&amp;18\pm 2.58\sqrt{\dfrac{5}{50}} \\
    &amp;=&amp;18\pm 0.82 \\
    &amp;=&amp;\left[ 17.18,18.82\right] .
\end{eqnarray*}\]</span></p>
<p>Notice that the measure of sampling variability has increased from 0.62 for a 95% confidence interval to 0.82 for a 99% confidence interval. This illustrates the general proposition that the confidence interval gets wider as the confidence coefficient (<span class="math inline">\(1-\alpha\)</span>) is increased. There has been no change in the precision of estimation here.</p>
<p>Why the use of <span class="math inline">\(1-\alpha\)</span> in the probability statement underlying the confidence interval? The random variables <span class="math inline">\(C_L\)</span> and <span class="math inline">\(C_U\)</span> are designed here to make</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( \mu \in \left[ C_{L},C_{U}\right] \right) =1-\alpha
\end{equation*}\]</span></p>
<p>and therefore</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( \mu \notin \left[ C_{L},C_{U}\right] \right) =\alpha .
\end{equation*}\]</span></p>
<p>Recall that in this probability statement it is the lower and upper bounds which are random variables, and not the population mean <span class="math inline">\(\mu\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of size 20 is drawn from the distribution of household incomes, where the latter is supposed to be <span class="math inline">\(N\left( \mu ,9\right)\)</span>. Notice that <span class="math inline">\(\sigma ^{2}\)</span> here is <strong>known</strong> to be equa to 9. Your sample mean is <span class="math inline">\(\bar{x}=-12\)</span>. Then, the 90% confidence interval for <span class="math inline">\(\mu\)</span> is</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm 1.645~SE\left( \bar{X}\right) &amp;=&amp;-12\pm 1.645\sqrt{\dfrac{9}{20}} \\
    &amp;=&amp;-12\pm 1.1035 \\
    &amp;=&amp;\left[ -13.1035,-10.8965\right] .
\end{eqnarray*}\]</span></p>
<p>How big should your sample be such that the measure of sampling variability (<span class="math inline">\(1.645~SE\left( \bar{X}\right)\)</span>) is smaller than 1?</p>
<p><span class="math inline">\(n\)</span> should be at least <input class="webex-solveme nospaces" size="2" data-answer="[&quot;25&quot;]">.</p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math inline">\(1.645~SE\left( \bar{X}\right)=1.645 \cdot \sqrt{\frac{\sigma^2}{n}}&lt;1\)</span>. Either try in Excel which value does reduce this value below 1, or solve the inequality to get <span class="math inline">\(n&gt;1.645^2 \cdot \sigma^2\)</span>. This leads to <span class="math inline">\(n\)</span> having to be at least 25.</p>
</div>
</div>
</div>
</section>
<section id="which-distribution-to-use" class="level3" data-number="15.1.4">
<h3 data-number="15.1.4" class="anchored" data-anchor-id="which-distribution-to-use"><span class="header-section-number">15.1.4</span> Which distribution to use?</h3>
<p>We started the argument with a calculation we were familiar with from the discussion of sampling distributions. We asked a question like “What is <span class="math inline">\(\Pr(c_L \leq \bar{X} \leq c_U)\)</span>?” and then based our calculation on what we knew about the sampling distribution of <span class="math inline">\(\bar{X}\)</span>. In the case we discussed <span class="math inline">\(\bar{X} \sim N(\mu,\frac{\sigma^2}{n})\)</span> as the population was assumed to be normally distributed with known <span class="math inline">\(\sigma^2=5\)</span>.</p>
<p>The assumption, amongst these, which seemed the most problematic was that of a known population variance (<span class="math inline">\(sigma^2\)</span>). In a situation where we wish to estimate an unknown population mean (<span class="math inline">\(\mu\)</span>) it is unlikely that we know the population variance <span class="math inline">\(\sigma^2\)</span>. In the section on hypothesis testing we discussed how the sample mean <span class="math inline">\(\bar{X}\)</span> is distributed when <span class="math inline">\(\sigma^2\)</span> has to be estimated by the sample variance <span class="math inline">\(s^2\)</span>. The following table represents what we know about the sampling distribution of the standardised sample mean <span class="math inline">\(\bar{X}\)</span>, <span class="math inline">\(t=\frac{\bar{X}-\mu}{\sqrt{s^2/n}}\)</span> in this situation:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Sample Size (<span class="math inline">\(n\)</span>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dist of <span class="math inline">\(X\)</span></td>
<td>small</td>
<td>large</td>
</tr>
<tr class="even">
<td>Normal</td>
<td><span class="math inline">\(t \sim t_{n-1}\)</span></td>
<td><span class="math inline">\(t \sim N(0,1)\)</span></td>
</tr>
<tr class="odd">
<td>not Normal</td>
<td><span class="math inline">\(t \sim ?\)</span></td>
<td><span class="math inline">\(t \sim N(0,1)\)</span></td>
</tr>
</tbody>
</table>
<p>This will lead us to adjust the way in which we calculate confidence intervals. In the situation where we could assume that <span class="math inline">\(\bar{X}\)</span> was normally distributed the lower and upper confidence bounds were calculated as follows:</p>
<p><span class="math display">\[\begin{equation*}
    \left[ c_{L},c_{U}\right] =\bar{x}\pm z_{\alpha /2}SE\left( \bar{X}\right) = \bar{x}\pm z_{\alpha /2} \sqrt{\frac{\sigma^2}{n}}  
\end{equation*}\]</span></p>
<p>Now, we shall adjust this, acknowledging that we usually have to estimate the population variance from the sample, using <span class="math inline">\(s^2\)</span>:</p>
<p><span class="math display">\[\begin{equation*}
    \left[ c_{L},c_{U}\right] =\bar{x}\pm t_{n-1,\alpha /2}SE\left( \bar{X}\right) = \bar{x}\pm t_{n-1,\alpha /2} \sqrt{\frac{s^2}{n}}  
\end{equation*}\]</span></p>
<p>The interpretation stays exactly the same as earlier and you should note that the only difference is that we use the sample estmate <span class="math inline">\(s^2\)</span> and we use the t-distribution to obtain our estimate of the sampling variation $ t_{n-1,/2} $. You understand that, for large sample sizes the t-distribution tends towards the standard normal distribution.</p>
<p>This video walks you through the different cases (YouTube, 10min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/LdH4rqus9iw" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the same as the previous example, but now assuming that the population variance <span class="math inline">\(\sigma^{2}\)</span> is unknown. Household income in 1000s of UKP is $XN( ,^{2}) $, where <strong>both</strong> <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma ^{2}\)</span> are unknown. A random sample of size <span class="math inline">\(n=5\)</span> (previously 50) yields <span class="math inline">\(\bar{x}=18\)</span> (as before) and <span class="math inline">\(s^{2}=4.5\)</span>. Here,</p>
<p><span class="math display">\[\begin{equation*}
    T=\dfrac{\bar{X}-\mu }{\sqrt{\dfrac{S^{2}}{n}}}\thicksim t_{4}.
\end{equation*}\]</span></p>
<p>For a 95% confidence interval for <span class="math inline">\(\mu\)</span>, we need the percentage point <span class="math inline">\(t_{4,0.025}\)</span> such that</p>
<p><span class="math display">\[\begin{equation*}
    \Pr \left( T\leqslant t_{4,0.025}\right) =0.975.
\end{equation*}\]</span></p>
<p>Note that we need to find the values in the t-distribution that cut off <span class="math inline">\(\alpha/2\)</span> of the probability in the tail. From the the t-distribution this is found to be</p>
<p><span class="math display">\[\begin{equation*}
    t_{4,0.025}=2.776.
\end{equation*}\]</span></p>
<p>The confidence interval for <span class="math inline">\(\mu\)</span> is then</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm t_{n-1,\alpha /2}\sqrt{\dfrac{s^{2}}{n}} &amp;=&amp;18\pm \left(2.776\right) \sqrt{\dfrac{4.5}{5}} \\
    &amp;=&amp;18\pm 2.634 \\
    &amp;=&amp;\left[ 15.366,20.634\right] .
\end{eqnarray*}\]</span></p>
<p>For comparison with the original example, if we had used <span class="math inline">\(\sigma ^{2}=5\)</span> with a sample of size 5 the resulting normal-based confidence interval would be</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm z_{\alpha /2}\sqrt{\dfrac{\sigma ^{2}}{n}} &amp;=&amp;18\pm \left(1.96\right) \sqrt{\dfrac{5}{5}} \\
    &amp;=&amp;18\pm 1.96 \\
    &amp;=&amp;\left[ 16.04,19.96\right] .
\end{eqnarray*}\]</span>%</p>
<p>This normal-based confidence interval is narrower than the <span class="math inline">\(t\)</span> based one: this is the consequence of the extra dispersion of the <span class="math inline">\(t\)</span> distribution compared with the <span class="math inline">\(N\left( 0,1\right)\)</span> distribution. The underlying reason for the increased dispersion is, of course, the fact that we do not know the value of <span class="math inline">\(\sigma^2\)</span>. Although we have a sample estimate <span class="math inline">\(s^2\)</span> we need to acknowledge that there is sampling variation with respect to this estimate on top of the sampling variation we have for <span class="math inline">\(\bar{x}\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of size 10 is drawn from the distribution of household incomes, where the latter is known to be <span class="math inline">\(N\left( \mu ,\sigma^2\right)\)</span>. Notice that <span class="math inline">\(\sigma ^{2}\)</span> has to be estimated with the sample variance, here <span class="math inline">\(s^2 = 8.2\)</span>. Your sample mean is <span class="math inline">\(\bar{x}=-12\)</span>. Then, the 90% confidence interval for <span class="math inline">\(\mu\)</span> is</p>
<p><span class="math inline">\(\left[\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="8" data-answer="[&quot;-13.6599&quot;]"> , <input class="webex-solveme nospaces" data-tol="0.001" size="8" data-answer="[&quot;-10.3401&quot;]"> <span class="math inline">\(\right]\)</span></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Calculations are exactly as in the previous example. Note that you need to use the t-table.</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm t_{10-1,0.10/2}~SE\left( \bar{X}\right) &amp;=&amp;-12\pm 1.833\sqrt{\dfrac{8.2}{10}} \\
    &amp;=&amp;-12\pm 1.6599 \\
    &amp;=&amp;\left[ -13.6599,-10.3401\right] .
\end{eqnarray*}\]</span></p>
<p>Note that this confidence interval is centered around the sample mean of <span class="math inline">\(-12\)</span>.</p>
</div>
</div>
</div>
<p>From the earlier table you will see that the t-distribution is only the right distribution to use if you know that the population distribution is actually a normal distribution. But as when we discussed hypothesis testing, the central limit theorem will ensure that a sample mean is normally distributed if the sample size is sufficiently large. In that case we will construct a <span class="math inline">\(100\left( 1-\alpha \right)\)</span> confidence interval from</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}\pm z_{\alpha /2}\sqrt{\dfrac{s^{2}}{n}}.
\end{equation*}\]</span></p>
<p>Consider the earlier example (using <span class="math inline">\(n=50\)</span>), but now not assuming that sampling takes place from a normal distribution. We assume that the sample information is <span class="math inline">\(n=50\)</span>, <span class="math inline">\(\bar{x}=18\)</span> and <span class="math inline">\(s^{2}=4.5\)</span>. Then, an approximate <span class="math inline">\(95\%\)</span> confidence interval is (assuming that the sample size is sufficiently large for the CLT to do its magic) is calculated as follows:</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm z_{\alpha /2}\sqrt{\dfrac{s^{2}}{n}} &amp;=&amp;18\pm 1.96\sqrt{\dfrac{4.5}{50}} \\
    &amp;=&amp;18\pm 0.588 \\
    &amp;=&amp;\left[ 17.412,18.588\right] .
\end{eqnarray*}\]</span></p>
<p>In general, how this compares with the exact confidence interval based on knowledge of <span class="math inline">\(\sigma ^{2}\)</span> depends on how good <span class="math inline">\(s^{2}\)</span> is as an estimate of <span class="math inline">\(\sigma ^{2}\)</span>. Nothing can be said about this usually.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of size 70 is drawn from the distribution of household incomes. You recognise that you should not assume that these incomes are normally distributed. Notice that <span class="math inline">\(\sigma ^{2}\)</span> has to be estimated with the sample variance, here <span class="math inline">\(s^2 = 8.2\)</span>. Your sample mean is <span class="math inline">\(\bar{x}=-12\)</span>. Then, the 90% confidence interval for <span class="math inline">\(\mu\)</span> is:</p>
<p><span class="math inline">\(\left[\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="8" data-answer="[&quot;-12.5647&quot;]"> , <input class="webex-solveme nospaces" data-tol="0.001" size="8" data-answer="[&quot;-11.4353&quot;]"> <span class="math inline">\(\right]\)</span></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Note that we are now using the normal distribution.</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}\pm z_{0.10/2}~SE\left( \bar{X}\right) &amp;=&amp;-12\pm 1.65\sqrt{\dfrac{8.2}{70}} \\
    &amp;=&amp;-12\pm 0.5647 \\
    &amp;=&amp;\left[ -12.5647,-11.4353\right] .
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
</section>
<section id="additional-resources" class="level3" data-number="15.1.5">
<h3 data-number="15.1.5" class="anchored" data-anchor-id="additional-resources"><span class="header-section-number">15.1.5</span> Additional Resources</h3>
<ul>
<li><a href="https://www.khanacademy.org/math/statistics-probability/confidence-intervals-one-sample/old-confidence-interval-videos/v/small-sample-size-confidence-intervals">Salman Khan on such a confidence interval</a>.</li>
</ul>
</section>
</section>
<section id="confidence-intervals-for-population-proportions" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="confidence-intervals-for-population-proportions"><span class="header-section-number">15.2</span> Confidence intervals for population proportions</h2>
<p>As for hypothesis testing you will learn that we can perform inference on many unknown parameters. Here we will merely introduce one extra such confidence interval, a confidence interval for a population proportion <span class="math inline">\(\pi\)</span>. We assumed that a random sample is obtained from the distribution of a Bernoulli random variable, a random variable <span class="math inline">\(X\)</span> taking on values 0 and 1 with probabilities <span class="math inline">\(1-\pi\)</span> and <span class="math inline">\(\pi\)</span> respectively. The sample mean <span class="math inline">\(\bar{X}\)</span> here is the random variable representing the sample proportion of <span class="math inline">\(1^{\prime }s\)</span>, and so is usually denoted <span class="math inline">\(P\)</span> or <span class="math inline">\(\hat{P}\)</span>, “the” sample proportion. (Note, here we use <span class="math inline">\(\hat{P}\)</span> to denote the sample estimator of the proportion and <span class="math inline">\(\hat{p}\)</span> as the actual sample proportion. In some books and websites you will see <span class="math inline">\(P\)</span> and <span class="math inline">\(p\)</span> only representing these two objects. As the population proportion is usually labelled <span class="math inline">\(\pi\)</span> this would be sufficient.)</p>
<p>When you learned about descriptive statistics you learnt that proportions can be seen as means of a variable which only takes values of 0 and 1. It is therefore not a surprise that the CLT works on sample proportions (<span class="math inline">\(\hat{P}\)</span>) as well and makes them, for sufficiently large samples, normally distributed random variables.</p>
<p>Since</p>
<p><span class="math display">\[\begin{equation*}
    E\left[ \hat{P}\right] =\pi ,\;\;\;\;var\left[ \hat{P}\right] =\dfrac{\pi \left( 1-\pi \right) }{n},
\end{equation*}\]</span></p>
<p><span class="math display">\[\begin{equation*}
    \dfrac{\hat{P}-\pi }{\sqrt{var\left[\hat{P}\right] }}\thicksim N\left(0,1\right) \;\;\;\;\;\text{approximately.}
\end{equation*}\]</span></p>
<p>So, one could hope to use this to provide an approximate confidence interval for <span class="math inline">\(\pi\)</span>. There is a minor complication here in that $var$ depends on the unknown parameter <span class="math inline">\(\pi\)</span> , but, there is an obvious estimator (<span class="math inline">\(\hat{P}\)</span>) available which could used to provide an estimator of $var$.</p>
<p>Following the previous reasoning, we argue that</p>
<p><span class="math display">\[\begin{equation*}
    \dfrac{\hat{P}-\pi }{\sqrt{\dfrac{\hat{P}\left( 1-\hat{P}\right) }{n}}}\thicksim N\left(0,1\right) \;\;\;\;\;\text{approximately.}
\end{equation*}\]</span></p>
<p>This knowledge can then be used to construct a sample confidence interval from</p>
<p><span class="math display">\[\begin{equation*}
    \hat{p}\pm z_{\alpha /2}\sqrt{\dfrac{\hat{p}\left( 1-\hat{p}\right) }{n}}.
\end{equation*}\]</span></p>
<p>Note that this differed from the approach taken when we required the variance of <span class="math inline">\(\hat{P}\)</span> when hypothesis testing. In that case we did not use the sample proportion <span class="math inline">\(\hat{p}\)</span> but rather the hypothesised (under <span class="math inline">\(H_0\)</span>) population proportion to calculate <span class="math inline">\(Var[\hat{P}]\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of 300 households is obtained, with 28% of the sample owning a tablet computer. An approximate 95% confidence interval for the population proportion of households owning a tablet computer is</p>
<p><span class="math display">\[\begin{eqnarray*}
    \hat{p}\pm z_{\alpha /2}\sqrt{\dfrac{\hat{p}\left( 1-\hat{p}\right) }{n}} &amp;=&amp;0.28\pm \left(1.96\right) \sqrt{\dfrac{0.28\left( 1-0.28\right) }{300}} \\
    &amp;=&amp;0.28\pm 0.0508 \\
    &amp;=&amp;\left[ 0.229,0.331\right] .
\end{eqnarray*}\]</span></p>
<p>For such an apparently large sample size, this is quite a wide confidence interval. Better precision of estimation would require a larger sample size.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>A random sample of 1021 randomly selected students is asked whether they intend to vote at the next election (in whichever country they are registered to vote). In the sample 780 students indicate that they intend to vote at the next general election in their country. Calculate a 99% confidence interval for the population proportion of students intending to vote</p>
<p><span class="math inline">\(\left[\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.7297&quot;,&quot;.7297&quot;]"> , <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.7982&quot;,&quot;.7982&quot;]"> <span class="math inline">\(\right]\)</span></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Note that we are now using the normal distribution.</p>
<p><span class="math display">\[\begin{eqnarray*}
        \hat{p}\pm z_{\alpha /2}\sqrt{\dfrac{\hat{p}\left( 1-\hat{p}\right) }{n}} &amp;=&amp;0.7640\pm \left(2.58\right) \sqrt{\dfrac{0.7640\left( 1-0.7640\right) }{1021}} \\
        &amp;=&amp;0.7640\pm 0.0343 \\
        &amp;=&amp;\left[ 0.7297,0.7982\right] .
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
<section id="additional-resources-1" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="additional-resources-1"><span class="header-section-number">15.2.1</span> Additional resources</h3>
<ul>
<li>This is the Khan Academy example of a <a href="https://www.khanacademy.org/math/probability/statistics-inferential/confidence-intervals/v/confidence-interval-example">confidence interval for a proportion</a>. The standard error of <span class="math inline">\(\hat{P}\)</span> is calculated in a different way but with the same result.</li>
</ul>
</section>
<section id="opinion-polling-reality" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="opinion-polling-reality"><span class="header-section-number">15.2.2</span> Opinion polling reality</h3>
<p>Estimating proportions is a very common task. Market research companies will often do this on behalf of clients. One of the companies which is busy in this sphere is <a href="https://yougov.co.uk/">YouGov</a>. Visit their website to see the wide variety of research they undertake. One of the regular pieces of research undertaken is an investigation of voting intentions. Here is a link to the <a href="https://yougov.com/en-gb/trackers/voting-intention">voting intentions page</a>. You will remember from earlier discussions that, when sampling, we would normally assume that we have taken a random sample from the population of interest. One interesting aspect of such work is that organisations like YouGov will often reweigh the observations. This means that not all observations will get the same weights. We dealt with this in the descriptive statistics section. The reason why this is done is to ensure that the investigated sample has demographic properties that the population of interest is assumed to have.</p>
<p>In this we can get survey details for the 31 March 2023 YouGov voting intention survey. In there you can see (on the bottom of page 4) that YouGov targets (amongst others) the following characteristics</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Brexit Vote</th>
<th>Target percentage</th>
<th>Actual obs</th>
<th>Actual percentage</th>
<th>Weighted obs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Remain</td>
<td>35.2%</td>
<td>801</td>
<td>40.0%</td>
<td>705</td>
</tr>
<tr class="even">
<td>Leave</td>
<td>37.2%</td>
<td>768</td>
<td>38.4%</td>
<td>745</td>
</tr>
<tr class="odd">
<td>Did not vote / Did not know</td>
<td>27.5%</td>
<td>433</td>
<td>21.6%</td>
<td>551</td>
</tr>
</tbody>
</table>
<p>There were 2002 responses and for instance there were 801 respondents that voted remain in the Brexit vote. That is an actual percentage of 40% which is more than the 35.2% targeted. Therefore, the weights of these observations are down-weighted such that they effectively represent only 705 observations (approximately the target percentage). Equally, there were too few respondents who did not vote and therefore these observations receive a larger weight.</p>
<p>Below you can see a snippet from the resulting voting intention. The numbers in the table represent percentages.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/YouGovVotingIntention.png" class="img-fluid figure-img"></p>
<figcaption>Voting intention. Source: YouGov, 31 March 2023.</figcaption>
</figure>
</div>
<p>As you can see YouGov estimates that 46% of votes will go to the Labour party. When performing a hypothesis test or calculating a confidence interval you will need the standard error for the sample proportion <span class="math inline">\(\hat{P}\)</span>. When performing hypothesis tests we use the hypothesised proportion in the calculation of <span class="math inline">\(\sigma^2_{\hat{P}}\)</span>. When calculating a confidence interval we use, as in the previous example:</p>
<p><span class="math display">\[\begin{equation*}
    \sigma^2_{\hat{P}}=\dfrac{\hat{p}\left( 1-\hat{p}\right) }{n}
\end{equation*}\]</span></p>
<p>Unfortunately, when using weighted observations as in the YouGov example, this formula is not correct, as it does not take into account that some observations had a higher weight than others. How to calculate the standard error for a weighted sample proportion is beyond the scope of this document. For the example below use <span class="math inline">\(\sigma^2_{\hat{P}}\)</span> as introduced above, it will continue to be in the right ballpark.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the 90% confidence interval for the proportion of Labour votes.</p>
<p><span class="math inline">\([\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.4416&quot;,&quot;.4416&quot;]"> , <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.4784&quot;,&quot;.4784&quot;]"> <span class="math inline">\(]\)</span></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{eqnarray*}
    p\pm z_{\alpha /2}\sqrt{\dfrac{p\left( 1-p\right) }{n}} &amp;=&amp;0.46\pm \left(1.65\right) \sqrt{\dfrac{0.46\left( 1-0.46\right) }{2002}} \\
    &amp;=&amp;0.46\pm 0.0184 \\
    &amp;=&amp;\left[ 0.4416,0.4784\right] .
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
</section>
</section>
<section id="summary-and-outlook" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="summary-and-outlook"><span class="header-section-number">15.3</span> Summary and Outlook</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Summary Questions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose that a random sample of size 60 is drawn from the distribution of household incomes, where the latter is supposed to be <span class="math inline">\(N(\mu,8)\)</span>, and that the mean of the sample is <span class="math inline">\(\bar{x}=22\)</span>.</p>
<p>The following 95% confidence interval has been correctly calculated:</p>
<p>95% CI: <span class="math inline">\([21.2843, 22.7156]\)</span></p>
<p>Answer the following questions:</p>
<p>We are 95% confident that the average household income in this sample is between 21.2843 and 22.7156. <select class="webex-select"><option value="blank"></option><option value="">TRUE</option><option value="answer">FALSE</option></select></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>False, the CI contains the sample mean 100% of times as it is cenrtered around it.</p>
</div>
<p>95% of the household incomes are between 21.2843 and 22.7156. <select class="webex-select"><option value="blank"></option><option value="">TRUE</option><option value="answer">FALSE</option></select></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>False, the CI is for covering the population mean (<span class="math inline">\(\mu\)</span>) not a proportion of the original population.</p>
</div>
<p>There is 0.95 probability that the true mean household income falls in 21.2843 and 22.7156. <select class="webex-select"><option value="blank"></option><option value="">TRUE</option><option value="answer">FALSE</option></select></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>False, the population mean <span class="math inline">\(\mu\)</span> is not a random variable, the CI itself is. For a particular CI like the one calculated here <span class="math inline">\(\mu\)</span> is in the CI or it is not, we just don’t know which of the two it is.</p>
</div>
<p>The lower and upper limits of the confidence interval are random variables. <select class="webex-select"><option value="blank"></option><option value="answer">TRUE</option><option value="">FALSE</option></select></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>True, they are based on the sample mean and the sample mean is a random variable itself. Therefore the limits of the CI are also random variables.</p>
</div>
</div>
</div>
<p>In this section we discussed confidence intervals. They are a very powerful and popular way to communicate that any estimate for a population quantity (say the mean or proportion) is merely an estimate and that really we are not certain. As the p-value in hypothesis testing, the confidence interval has a slightly “stilted” interpretation. However, confidence intervals are a very intuitive way to communicate the uncertainty or margin of error.</p>
<p>Having said that, often the communication of opinion poll results (say in TV, TikTok or newspapers) does not acknowledge such uncertainty. Here is an example of typical reporting on opinion polls. An institution (here Quinnipac University, well known for their polling operation) <a href="https://poll.qu.edu/poll-release?releaseid=3863">conducted some opinion polls</a> and presents a write-up of the results. At the bottom of that report you do get a clear statement about the margins of error (typically calculated as 95% confidence intervals). Then some other organisation picks up on these poll results and does not mention any margin of error (here the respectable <a href="https://www.brookings.edu/blog/fixgov/2023/01/06/polls-show-americans-are-divided-on-the-significance-of-january-6/">Brookings Institute</a>. This is a very typical pattern which you can confirm by checking how another <a href="https://poll.qu.edu/poll-release?releaseid=3842">Quinnipac poll on the conservative US Supreme Court judge Thomas</a> was reported on by <a href="https://edition.cnn.com/2022/04/06/politics/justice-clarence-thomas-wife-ginni-poll-recusal/index.html">CNN</a>.</p>
<p>In the UK, the BBC actually does have <a href="https://www.bbc.com/editorialguidelines/guidance/surveys#reportingopinionpolls">guidance on how opinion polls are to be reported</a>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/BBCpolladvice.png" class="img-fluid figure-img"></p>
<figcaption>Guidance by the BBC on how its programmes should report on opinion polls.</figcaption>
</figure>
</div>
<p>But that does not ensure that this guidance is always adhered to as reading through <a href="https://www.bbc.com/news/world-us-canada-44324545">this BBC news story confirms</a>.</p>
<p>What should you take away from this? Reporting on statistical uncertainty is not easily done correctly (recall the awkward interpretations of p-values and confidence intervals). It is therefore perhaps not surprising that many news organisations shy away from such communication. It is therefore some of your skill, after having studies on this course, to properly understand such uncertainty and contribute to communicating it properly.</p>
<p>Here are two additional pieces of interesting reading in this area.</p>
<ul>
<li><a href="https://publications.parliament.uk/pa/ld201719/ldselect/ldppdm/106/10606.htm">This is an interesting report by the UK Parliament on the way Media report on polling results</a>.</li>
<li><a href="https://probability.kucharski.io">This is an interesting post by Adam Kucharski on the probabilities the public associate with terms like “very likely” or “almost impossible”.</a>. If you complete the short survey you will get a result like the below which shows you whether your interpretations coincide with those of others.<br>
<img src="images/probability-perception-results.png" class="img-fluid"></li>
</ul>
<p>:::</p>


</section>

</main> <!-- /main -->
<script src="include/webex.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./HypothesisTesting.html" class="pagination-link" aria-label="Hypothesis Testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./RegressionInference.html" class="pagination-link" aria-label="Hypothesis Testing">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>