<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Correlation, Regression and Causation – Statistics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./descriptive_stats.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./CorrelationRegressionCausation.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphical_descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CorrelationRegressionCausation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#descriptive-statistics-for-the-relation-between-two-or-more-variables" id="toc-descriptive-statistics-for-the-relation-between-two-or-more-variables" class="nav-link active" data-scroll-target="#descriptive-statistics-for-the-relation-between-two-or-more-variables"><span class="header-section-number">5.1</span> Descriptive statistics for the relation between two or more variables</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">5.2</span> Correlation</a>
  <ul class="collapse">
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources"><span class="header-section-number">5.2.1</span> Additional resources</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">5.3</span> Regression</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="descriptive-statistics-for-the-relation-between-two-or-more-variables" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="descriptive-statistics-for-the-relation-between-two-or-more-variables"><span class="header-section-number">5.1</span> Descriptive statistics for the relation between two or more variables</h2>
<p>When we considered graphical ways to describe data we already considered the situation of having more than two variables. Very common graphical representations in such situations are line graphs (with multiple lines) when dealing with time series data or scatter plots when dealing with cross-sectional data. In particular scatter plots allowed us to visualise how two series were related to each other.</p>
<p>Here we replicate a scatter plot used in an earlier section. This plot illustrates how the country level 14-day covid case rate (in 2022, Week 10) relates to the countries Health expenditure as a share of the countries GDP.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/scatter_covid_healthex.png" class="img-fluid figure-img"></p>
<figcaption>Scatter diagram, Health expenditure as percentage of GDP and 14-day Covid case rate, as per Week 10 in 2022.</figcaption>
</figure>
</div>
<p>It is somewhat difficult to see from this plot whether there was indeed a positive relationship between these two variables or not. In fact there are three aspects of a potential relationship you may be interested in. First, is it a positive or negative relationship, second, whether it appears to be a linear or nonlinear relationship and third, how strong is that relationship. In this section you will learn how to find numerical descriptive statistics that that speak to these aspects of such a relationship.</p>
<p>This video provides a short introduction to correlation</p>
{{&lt; https://youtu.be/cNyIMCjMvBA &gt;}}
</section>
<section id="correlation" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="correlation"><span class="header-section-number">5.2</span> Correlation</h2>
<p>A commonly used measure of association is the <strong>sample correlation coefficient</strong>, which is designed to tell us something about the characteristics of a scatter plot of observations on the variable <span class="math inline">\(Y\)</span> against observations on the variable <span class="math inline">\(X\)</span>. In particularly, are higher than average values of <span class="math inline">\(Y\)</span> associated with higher than average values of <span class="math inline">\(X\)</span>, and vice-versa? In the context of the above example we would ask whether higher values of health expenditure (as % of GDP) are related to higher Covid infection rates.</p>
<p>Consider the following data-set in which we observe the weight (<span class="math inline">\(Y_i\)</span>) measured in pounds and the height (<span class="math inline">\(X_i\)</span>) measured in inches of a sample of 12 people:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
</tr>
<tr class="even">
<td>Weight <span class="math inline">\(=Y_i\)</span></td>
<td>155</td>
<td>150</td>
<td>180</td>
<td>135</td>
<td>156</td>
<td>168</td>
<td>178</td>
<td>160</td>
<td>132</td>
<td>145</td>
<td>139</td>
<td>152</td>
</tr>
<tr class="odd">
<td>Height <span class="math inline">\(=X_i\)</span></td>
<td>70</td>
<td>63</td>
<td>72</td>
<td>60</td>
<td>66</td>
<td>70</td>
<td>74</td>
<td>65</td>
<td>62</td>
<td>67</td>
<td>65</td>
<td>68</td>
</tr>
</tbody>
</table>
<p>The best way to graphically represent the data is the following scatter plot:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/regression_scatter1.jpg" class="img-fluid figure-img"></p>
<figcaption>Scatter diagram, Weight and Height.</figcaption>
</figure>
</div>
<p>On this graph a horizontal line at <span class="math inline">\(y=154.1667\)</span> (at the sample mean <span class="math inline">\(\bar{y}\)</span>) and also a vertical line at <span class="math inline">\(x=66.8333\)</span> (at the sample mean <span class="math inline">\(\bar{x}\)</span>) are superimposed. This creates four areas. Points in the upper right quadrant are those for which the weight is higher than average <strong>and</strong> height is higher than average. One of these points (Observation <span class="math inline">\(i=3\)</span> with <span class="math inline">\(y_i=180, x_i=72\)</span>) is highlighted in the scatter plot along with its deviations from <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span>.</p>
<p>Points in the lower left quadrant are those for which weight is lower than average <strong>and</strong> height is lower than average. Since most points lie in these two quadrants, this suggests that higher than average weight is associated with higher than average height; whilst lower than average weight is associated with lower than average height. This is typical for a positive relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If there was no association, we would expect to see a roughly equal distribution of points in all four quadrants.</p>
<p>While it is often straightforward to see the qualitative nature of a relationship (positive, negative or unrelated) we want a numerical measure that describes this relationship such that we can also comment on the strength of the relationship. The basis of such a measure are again the deviations from the sample mean (as for the calculation of the variance and standard deviation), but now we have two such deviations for each observation, the deviation in the <span class="math inline">\(Y\)</span> variable, <span class="math inline">\(d_{y,i}=(y_i-\bar{y})\)</span>, and the deviation in the <span class="math inline">\(X\)</span> variable, <span class="math inline">\(d_{x,i}=(x_i-\bar{x})\)</span>. These are the deviations you can see in the above Figure.</p>
<p>In the case of the third observation with <span class="math inline">\(y_3=180\)</span> and <span class="math inline">\(x_3=72\)</span> we can see that both values are larger than the respective sample means <span class="math inline">\(\bar{y}\)</span> and <span class="math inline">\(\bar{x}\)</span> and therefore both, <span class="math inline">\(d_{y,i}\)</span> and <span class="math inline">\(d_{x,i}\)</span> are positive. \ <span class="math inline">\(d_{y,i}=(y_i-\bar{y})\)</span> = 180-154.1667 = 25.8333\ <span class="math inline">\(d_{x,i}=(x_i-\bar{x})\)</span> = 72-66.8333 = 5.1667</p>
<p>In fact this will be the case for all observations that lie in the <strong>upper right</strong> quadrant. For observations in the <strong>lower left</strong> quadrant we will find <span class="math inline">\(d_{y,i}\)</span> and <span class="math inline">\(d_{x,i}\)</span> to be smaller than 0. Observations in both these quadrants are reflective of a positive relationship. We therefore need to use the information in <span class="math inline">\(d_{y,i}\)</span> and <span class="math inline">\(d_{x,i}\)</span> in such a way that in both these cases we get a positive contribution to our statistic that numerically describes the relationship. Consider the term <span class="math inline">\((d_{y,i} \cdot d_{x,i})\)</span>; this term will be positive for all observations in either the <strong>upper right</strong> or <strong>lower left</strong> quadrant. For values in either the <strong>upper left</strong> or <strong>lower right</strong> quadrant, however, the terms <span class="math inline">\(d_{y,i}\)</span> and <span class="math inline">\(d_{x,i}\)</span> will have different signs and hence the term <span class="math inline">\((d_{y,i} \cdot d_{x,i})\)</span> will be negative, reflective of the fact that observations in these quadrants are representative of a negative relationship.</p>
<p>It should now be no surprise to find that our numerical measure of a relationship between two variables is based on these terms. In particular we will use what is called the sample covariance:</p>
<p><span class="math display">\[\begin{equation*}
    Cov(X,Y)=s_{X,Y}=\frac{1}{n-1}\sum_{i=1}^{n}\left( x_{i}-\bar{x}\right) \left( y_{i}-\bar{y}\right) =\frac{1}{n-1}\sum_{i=1}^{n} d_{x,i} d_{y,i}
\end{equation*}\]</span></p>
<p>You can see that this is the sum of <span class="math inline">\(d_{y,i}d_{x,i}\)</span> divided by <span class="math inline">\(n-1\)</span>. The reason for dividing by <span class="math inline">\(n-1\)</span> and not <span class="math inline">\(n\)</span> is similar to the reasoning used for the sample variance. In fact the measure that we typically use is the :</p>
<p><span class="math display">\[\begin{eqnarray*}
    Corr(X,Y)=r_{XY}&amp;=&amp;\frac{s_{X,Y} }{\sqrt{s^2_X s^2_Y}}\\
    &amp;=&amp; \frac{\frac{1}{n-1}\sum_{i=1}^{n}\left( x_{i}-\bar{x}\right) \left( y_{i}-\bar{y}\right) }{\sqrt{\frac{1}{n-1}\sum_{i=1}^{n}\left( x_{i}-\bar{x}\right)^{2}\,\frac{1}{n-1}\sum_{i=1}^{n}\left( y_{i}-\bar{y}\right) ^{2}}}\\
    &amp;=&amp; \frac{\sum_{i=1}^{n}\left( x_{i}-\bar{x}\right) \left( y_{i}-\bar{y}\right) }{\sqrt{\sum_{i=1}^{n}\left( x_{i}-\bar{x}\right)^{2}\,\sum_{i=1}^{n}\left( y_{i}-\bar{y}\right) ^{2}}}\\
\end{eqnarray*}\]</span></p>
<p>It is the sample covariance divided by the square root of the product of the two sample variances. In the last line we merely cancelled out the <span class="math inline">\(1/(n-1)\)</span> terms.</p>
<section id="excel-application" class="level4 callout-info" data-number="5.2.0.1">
<h4 data-number="5.2.0.1" class="anchored" data-anchor-id="excel-application"><span class="header-section-number">5.2.0.1</span> Excel application</h4>
<p>The calculations are best done in a Table format or using Excel.</p>
<p>This video shows the calculations by hand (YouTube, 21min)</p>
{{&lt; https://www.youtube.com/watch?v=xMDjtzT1G_w &gt;}}
<p>This video shows the calculations by Excel (YouTube, 11min)</p>
{{&lt; https://www.youtube.com/watch?v=YdtXe2vkKrw &gt;}}
<table class="caption-top table">
<caption>Table illustrating the calculations required to calculate a covariance. Values rounded to 4dp.</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Obs</th>
<th>Weight (Y)</th>
<th>Height (X)</th>
<th>(y_i-{y}$</th>
<th>(x_i-{x}$</th>
<th>((y_i-{y})^2$</th>
<th>((x_i-{x})^2$</th>
<th>((y_i-{y})(x_i-{x})$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>155</td>
<td>70</td>
<td>0.8333</td>
<td>3.1667</td>
<td>0.6944</td>
<td>10.0278</td>
<td>2.6389</td>
</tr>
<tr class="even">
<td>2</td>
<td>150</td>
<td>63</td>
<td>-4.1667</td>
<td>-3.8333</td>
<td>17.3611</td>
<td>14.6944</td>
<td>15.9722</td>
</tr>
<tr class="odd">
<td>3</td>
<td>180</td>
<td>72</td>
<td>25.8333</td>
<td>5.1667</td>
<td>667.3611</td>
<td>26.6944</td>
<td>133.4722</td>
</tr>
<tr class="even">
<td>4</td>
<td>135</td>
<td>60</td>
<td>-19.1667</td>
<td>-6.8333</td>
<td>367.3611</td>
<td>46.6944</td>
<td>130.9722</td>
</tr>
<tr class="odd">
<td>5</td>
<td>156</td>
<td>66</td>
<td>1.8333</td>
<td>-0.8333</td>
<td>3.3611</td>
<td>0.6944</td>
<td>-1.5278</td>
</tr>
<tr class="even">
<td>6</td>
<td>168</td>
<td>70</td>
<td>13.8333</td>
<td>3.1667</td>
<td>191.3611</td>
<td>10.0278</td>
<td>43.8056</td>
</tr>
<tr class="odd">
<td>7</td>
<td>178</td>
<td>74</td>
<td>23.8333</td>
<td>7.1667</td>
<td>568.0278</td>
<td>51.3611</td>
<td>170.8056</td>
</tr>
<tr class="even">
<td>8</td>
<td>160</td>
<td>65</td>
<td>5.8333</td>
<td>-1.8333</td>
<td>34.0278</td>
<td>3.3611</td>
<td>-10.6944</td>
</tr>
<tr class="odd">
<td>9</td>
<td>132</td>
<td>62</td>
<td>-22.1667</td>
<td>-4.8333</td>
<td>491.3611</td>
<td>23.3611</td>
<td>107.1389</td>
</tr>
<tr class="even">
<td>10</td>
<td>145</td>
<td>67</td>
<td>-9.1667</td>
<td>0.1667</td>
<td>84.0278</td>
<td>0.0278</td>
<td>-1.5278</td>
</tr>
<tr class="odd">
<td>11</td>
<td>139</td>
<td>65</td>
<td>-15.1667</td>
<td>-1.8333</td>
<td>230.0278</td>
<td>3.3611</td>
<td>27.8056</td>
</tr>
<tr class="even">
<td>12</td>
<td>152</td>
<td>68</td>
<td>-2.1667</td>
<td>1.1667</td>
<td>4.6944</td>
<td>1.3611</td>
<td>-2.5278</td>
</tr>
<tr class="odd">
<td>Sum</td>
<td>1850</td>
<td>802</td>
<td>0</td>
<td>0</td>
<td>2659.6667</td>
<td>191.6667</td>
<td>616.3333</td>
</tr>
</tbody>
</table>
<p>If you calculate <span class="math inline">\(r\)</span> for the above example you should obtain a value of</p>
<p><span class="math display">\[\begin{equation*}
    Corr(X,Y)=r_{XY}=\frac{616.3333}{\sqrt{2659.6667 \cdot 191.6667}} = 0.8632
\end{equation*}\]</span></p>
</section>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Complete the table below and calculate, sample means, sample variances and standard deviations, the sample covariance and the correlation for the following four observations of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<table class="caption-top table">
<caption>Table for correlation calculations.</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Obs</th>
<th>Weight (Y)</th>
<th>Height (X)</th>
<th><span class="math inline">\(y_i-\bar{y}\)</span></th>
<th><span class="math inline">\(x_i-\bar{x}\)</span></th>
<th><span class="math inline">\((y_i-\bar{y})^2\)</span></th>
<th><span class="math inline">\((x_i-\bar{x})^2\)</span></th>
<th><span class="math inline">\((y_i-\bar{y})(x_i-\bar{x})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4</td>
<td>10</td>
<td>-4</td>
<td>6</td>
<td>16</td>
<td>36</td>
<td>-24</td>
</tr>
<tr class="even">
<td>2</td>
<td>8</td>
<td>-2</td>
<td>0</td>
<td>-6</td>
<td>0</td>
<td>36</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6</td>
<td>7</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>14</td>
<td>1</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>—–</td>
<td>————</td>
<td>————</td>
<td>—————–</td>
<td>—————–</td>
<td>———————</td>
<td>———————</td>
<td>——————————–</td>
</tr>
<tr class="even">
<td>Sum</td>
<td>32</td>
<td>16</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{y} =\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;8&quot;]"></p>
<p><span class="math inline">\(\bar{x} =\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;4&quot;]"></p>
<p><span class="math inline">\(s_Y^2 =\)</span> <input class="webex-solveme nospaces" size="7" data-answer="[&quot;18.6667&quot;]"></p>
<p><span class="math inline">\(s_X^2 =\)</span> <input class="webex-solveme nospaces" size="2" data-answer="[&quot;30&quot;]"></p>
<p><span class="math inline">\(Cov(X,Y) = s_{Y,X} =\)</span> <input class="webex-solveme nospaces" size="3" data-answer="[&quot;-16&quot;]"></p>
<p><span class="math inline">\(Corr(X,Y) = r =\)</span> <input class="webex-solveme nospaces" size="7" data-answer="[&quot;-0.6761&quot;,&quot;-.6761&quot;]"></p>
</div>
</div>
<p>A few things are worth noting with respect to the <strong>correlation coefficient</strong>:</p>
<ul>
<li>It can be shown algebraically that <span class="math inline">\(-1 \leq r \leq 1\)</span>.</li>
<li>Positive (negative) numbers represent a positive (negative) relationship and a value of 0 represents the absence of any relationship. In our Excel application example <span class="math inline">\(r=0.8632\)</span> and hence the two variables display a strong positive correlation.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/correlation_coefficient.png" class="img-fluid figure-img"></p>
<figcaption>Correlation coefficient, strength and direction.</figcaption>
</figure>
</div>
<ul>
<li>The numerator contains the sum of the discussed cross products <span class="math inline">\(d_{y,i} \cdot d_{x,i}=(y_i-\bar{y})(x_i-\bar{x})\)</span></li>
<li>The term in the denominator of the equation for <span class="math inline">\(r\)</span> is related to the variances of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>. These terms are required to <strong>standardise</strong> the statistic to be between -1 and 1.</li>
<li>For the correlation the order of variables does not matter, i.e.&nbsp;<span class="math inline">\(r_{XY}=r_{YX}\)</span>.</li>
</ul>
<p>The <strong>covariance</strong> is actually also a measure of the relationship between these two variables, but it has many of the same shortcomings as the variance (see the Descriptive Statistics lesson). Therefore we want a standardised measure (to ensure that <span class="math inline">\(-1\leq r \geq 1\)</span>. This standardisation uses the square root of the two respective variances.</p>
<p>There are two very important limitations of the <strong>correlation coefficient</strong>:</p>
<ul>
<li>In general, this sort of analysis does not imply causation, in either direction. Variables may appear to move together for a number of reasons and not because one is causally linked to the other.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Correlation, NOT Causation
</div>
</div>
<div class="callout-body-container callout-body">
<p>For example, over the period 1945-64 the number of TV licences <span class="math inline">\((x)\)</span> taken out in the UK increased steadily, as did the number of convictions for juvenile delinquency <span class="math inline">\(\left( y \right)\)</span>. Thus a scatter of <span class="math inline">\(y\)</span> against <span class="math inline">\(x\)</span>, and the construction of the sample correlation coefficient reveals an apparent positive relationship. However, to therefore claim that increased exposure to TV causes juvenile delinquency would be extremely irresponsible.</p>
</div>
</div>
<p>Another example illustrating that correlation must not be mis-interpreted as a causal relationship is that of ice cream sales and shark attacks, illustrated in the following image.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/causation_correlation.png" class="img-fluid figure-img"></p>
<figcaption>Correlation is not causation.</figcaption>
</figure>
</div>
<p>If we were to calculate a correlation between the two series we clearly would obtain a positive correlation. But nobody would suggest that increased ice-cream sales cause shark attacks, or indeed that increased shark attacks caused higher ice cream sales.<br>
Here is a different discussion on this issue:&nbsp;Khan Academy: <a href="www.khanacademy.org/math/probability/regression/regression-correlation/v/correlation-and-causality">Do not confuse correlation with causation</a>.</p>
<ul>
<li>The sample correlation coefficient gives an index of the apparent linear relationship only. It <strong>assumes</strong> that the scatter of points must be distributed about some underlying straight line. This is discussed further below. However, the term relationship is not really confined to such linear relationships.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Relationship, NOT Linear Relationship
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the relationship between and . If we were to plot observations for the age and income of people in the age range of 20 to 50 we will clearly find a positive relationship. However, if we were to extend the age range to 80, we would most likely see that income decreases at the upper end of the age range. Therefore there is no linear age/income relationship across the full age range and the <strong>correlation coefficient</strong> cannot be used to describe such a relationship.</p>
</div>
</div>
<p>Imagine drawing a straight line of <strong>best fit</strong> through the scatter of points in the above Figure (for height and weight) simply from <strong>visual</strong> inspection. You would try and make it <strong>go through</strong> the scatter, in some way, and it would probably have a positive slope. Numerically, one of the things that the correlation coefficient does is assess the slope of such a line: if <span class="math inline">\(r&gt;0\)</span>, then the slope of the line of best fit should be positive, and vice-versa. Moreover, if <span class="math inline">\(r\)</span> is close to either 1 (or -1) then this implies that the scatter is quite closely distributed around the line of best fit. What the correlation coefficient doesn’t do, however, is tell us the exact position of line of best fit. This is achieved using <strong>regression</strong> analysis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Scatterplot_correlation.jpeg" class="img-fluid figure-img"></p>
<figcaption>Scatter plots and correlation.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following Figure which displays six scatterplots</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/SixCorrelations.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plots of six bivariate data samples.</figcaption>
</figure>
</div>
<p>Match the correlations to the plots with the correlations. Note that the scales are identical for all plots.:</p>
<p><span class="math inline">\(r_1 = 0.9226\)</span>: Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;1&quot;]"> <span class="math inline">\(r_2 = -0.8835\)</span>: Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;2&quot;]"> <span class="math inline">\(r_3 = 0.9931\)</span> Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;3&quot;]"> <span class="math inline">\(r_4 = -0.9936\)</span> Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;4&quot;]"> <span class="math inline">\(r_5 = -0.1988\)</span> Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;5&quot;]"> <span class="math inline">\(r_6 = 0.4813\)</span> Plot <input class="webex-solveme nospaces" size="1" data-answer="[&quot;6&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>The sign of the correlation tells you whether the correlation is positive or negative. The strength of the correlation tells you how close the points are to a straight line (not shown here but in the next section).</p>
<p>It is not straightforward to tell the plots for the last two correlations apart. Plot 6 shows some more points in the top right quadrant and hence is the one with the positive correlation.</p>
</div>
</div>
</div>
<section id="additional-resources" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="additional-resources"><span class="header-section-number">5.2.1</span> Additional resources</h3>
<ul>
<li><a href="https://www.khanacademy.org/math/probability/regression/regression-correlation/v/correlation-and-causality">Khan Academy: Do not confuse correlation with causation</a></li>
</ul>
</section>
</section>
<section id="regression" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="regression"><span class="header-section-number">5.3</span> Regression</h2>
<p>When thinking about correlations you learned that correlation values close to 1 or -1 imply that the points will lie close to an imaginary line, the “line of best fit”. The following image shows the six scatter plots we looked at above but now including the lines of best fit.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/SixCorrelations_wLOBF.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plots of six bivariate data samples and lines of best fit.</figcaption>
</figure>
</div>
<p>The lines of best fit drawn on the scatter can be represented algebraically as <span class="math inline">\(a+bx\)</span>. Here <span class="math inline">\(x\)</span> represents the value on the horizontal axis, <span class="math inline">\(a\)</span> is the intercept (i.e.&nbsp;the value on the vertical axis at <span class="math inline">\(x=0\)</span>) and <span class="math inline">\(b\)</span> is the slope (i.e.&nbsp;the value by which the line increases as we increase <span class="math inline">\(x\)</span> by one unit). The line is defined at any value of <span class="math inline">\(x\)</span> and not only those at which we have actual observations. Here you can see the line of best fit for for sample 1 with an indication of the intercept (<span class="math inline">\(a\)</span>) and the slope (<span class="math inline">\(b\)</span>). For the data in Sample 1 these values are <span class="math inline">\(a=-0.34\)</span> and <span class="math inline">\(b=1.1327\)</span>. Just take these as given for now, you will shortly learn how to calculate these.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Scatter_LOBF_Details.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plot for Sample 1 and line of best fit (red).</figcaption>
</figure>
</div>
<p>When you substitute any of the observed values <span class="math inline">\(x_i\)</span> into the line of best fit you get <span class="math inline">\(\widehat{y}_i=a+bx_i\)</span>. It is important to note that the result of this operation, <span class="math inline">\(\widehat{y}_i\)</span> is not the same as <span class="math inline">\(y_i\)</span>. Let us illustrate this in the above scatter plot. One of the scatter points is for <span class="math inline">\(x_i=6\)</span> and <span class="math inline">\(y_i=9\)</span> (the point is highlighted in red in the next plot.) If we plug in the values for <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, we get</p>
<p><span class="math display">\[\begin{equation*}
    \widehat{y}_i=a+bx_i = -0.34 + 1.1327 \cdot 6 = 6.4562
\end{equation*}\]</span></p>
<p>The difference between the two is what is often called the residual:</p>
<p><span class="math display">\[\begin{equation*}
    res_i=y_i-\widehat{y}_i =  y_i - (a + bx_i) = y_i - a - bx_i.
\end{equation*}\]</span></p>
<p>Here that residual is <span class="math inline">\(res_i=y_i-\widehat{y}_i =9-6.4562 = 2.538\)</span>.</p>
<dl>
<dt><img src="images/Scatter_LOBF_Details2.png" class="img-fluid" alt="Scatter plot for Sample 1, line of best fit and example residual."></dt>
<dd>
Scatter plot for Sample 1, line of best fit and example residual.
</dd>
</dl>


</section>

</main> <!-- /main -->
<script src="include/webex.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./descriptive_stats.html" class="pagination-link" aria-label="Numerical Descriptive Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>