<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Numerical Descriptive Statistics – Statistics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./CorrelationRegressionCausation.html" rel="next">
<link href="./graphical_descriptive.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./descriptive_stats.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphical_descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CorrelationRegressionCausation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">4.1</span> Introduction</a></li>
  <li><a href="#location-measures" id="toc-location-measures" class="nav-link" data-scroll-target="#location-measures"><span class="header-section-number">4.2</span> Location Measures</a>
  <ul class="collapse">
  <li><a href="#the-mean" id="toc-the-mean" class="nav-link" data-scroll-target="#the-mean"><span class="header-section-number">4.2.1</span> The mean</a></li>
  <li><a href="#the-median" id="toc-the-median" class="nav-link" data-scroll-target="#the-median"><span class="header-section-number">4.2.2</span> The median</a></li>
  <li><a href="#weighted-mean" id="toc-weighted-mean" class="nav-link" data-scroll-target="#weighted-mean"><span class="header-section-number">4.2.3</span> Weighted mean</a></li>
  <li><a href="#summary-of-average-measures" id="toc-summary-of-average-measures" class="nav-link" data-scroll-target="#summary-of-average-measures"><span class="header-section-number">4.2.4</span> Summary of average measures</a></li>
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles"><span class="header-section-number">4.2.5</span> Percentiles</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">4.2.6</span> Further Reading</a></li>
  </ul></li>
  <li><a href="#dispersion" id="toc-dispersion" class="nav-link" data-scroll-target="#dispersion"><span class="header-section-number">4.3</span> Dispersion</a></li>
  <li><a href="#measures-of-skewness-and-higher-order-moments" id="toc-measures-of-skewness-and-higher-order-moments" class="nav-link" data-scroll-target="#measures-of-skewness-and-higher-order-moments"><span class="header-section-number">4.4</span> Measures of skewness and higher order moments</a></li>
  <li><a href="#measures-of-inequality" id="toc-measures-of-inequality" class="nav-link" data-scroll-target="#measures-of-inequality"><span class="header-section-number">4.5</span> Measures of inequality</a></li>
  <li><a href="#further-resources" id="toc-further-resources" class="nav-link" data-scroll-target="#further-resources"><span class="header-section-number">4.6</span> Further Resources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.1</span> Introduction</h2>
<p>Inequality is one of the biggest issues societies around the world have to deal with. Some societies are organised in ways which result in income and wealth distributions which are fairly equal (such as Scandinavian countries), others however, such as the United States and many South American countries, are organised in ways which result in large income and wealth concentrations in the hands of small groups.</p>
<p>Inequalities arise not only in income and wealth, but also in terms of access to education and healthcare. It has also been documented that certain groups in society are not only disproportionally represented in lower income and wealth categories but also have unequal access to opportunities. It is for this reason that the issue of inequalities has lately regained prominence in the public discourse. Part of this discourse is that the field of economics has also increased its efforts to measure inequalities (for a summary refer to <a href="https://ourworldindata.org/income-inequality#the-history-of-inequality">Our World in Data</a>), understand the reasons for the existing inequalities and propose policies which could address inequalities which are deemed to be too extreme (for a current summary of such efforts see the <a href="https://ifs.org.uk/inequality/%7D%7BIFS%20Deaton%20Review">IFS Deaton Review</a>).</p>
<p>A short video summary on the task taken on by the IFS Deaton Review on Inequality is available from <a href="https://www.youtube.com/watch?v=iXwwbZzTFZc">here</a>.</p>
<p>In the context of this statistics unit we are interested in income distributions as they are a very good example of how we use statistics. In particular we will look at different ways to summarise distributions of variables.</p>
<p>Here is an image of the Income Distribution in the UK in 2019 form the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/incomeandwealth/bulletins/householddisposableincomeandinequality/financialyearending2019">ONS</a>.</p>
<div id="fig-UKIncDist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-UKIncDist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/UK_IncomeDistribution_2019.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-UKIncDist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: UK Income Distribution. Source: ONS.
</figcaption>
</figure>
</div>
<p>This is a histogram, a graphical representation of the UK income distribution. As you can see, most people in the UK earn incomes between UKP 10,000 and UKP 40,000. The word most is actually not a very well defined term. We will use better terms later. There is a fairly small proportion of people earning more than UKP 60,000 a year. The image says that the measure displayed in the image is “Equivalised household disposable income of individuals”. It is disposable because it is calculated as income after tax. Equivalised incomes take into account whether someone lives in a single household or households with multiple people, acknowledging that larger households require more income to achieve the same standard of living as smaller households.</p>
<p>What this histogram illustrates is how incomes in the UK population is distributed. In some sense this histogram displays all there is to know about the income distribution for everyone in the UK. We could look at similar histograms for other countries and compare these, or we could look at the same image from other years for the UK to compare. However, it turns out that this is not an easy task.</p>
<p>To make comparisons between income distributions easier, it is useful to summarise the complex information in this distribution. We call such summary numbers, summary or descriptive statistics. There is no one number which can represent all the information in this distribution. But there are particular summary statistics which represent particular aspects of this distribution. In the above histogram you can already see two such summary statistics, the mean and the median income. These are both location measures or measures of the average. Other summary statistics can tell us something about the dispersion or variance.</p>
<p>In the following we will introduce different measures of location, dispersion and skewness. But these are not the only summative or descriptive statistics there are. In particular when looking at income distributions there is a lot of interest in the amount of inequality. A number of measures have been developed ot represent the amount of inequality in a particular income distribution. We will briefly discuss such measures at the end of this lesson.</p>
<p>We shall look at three categories of numerical summaries:</p>
<ul>
<li>Measures of Location</li>
<li>Measures of Dispersion</li>
<li>Measures of Skewness</li>
</ul>
</section>
<section id="location-measures" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="location-measures"><span class="header-section-number">4.2</span> Location Measures</h2>
<p>A measure of <strong>location</strong> tells us something about what a <strong>typical</strong> value from a set of observations is. We sometimes use the expression <strong>central location</strong>, <strong>central tendency</strong> or, more commonly, <strong>average</strong>. We can imagine it as the value around which the observations in the sample are <strong>distributed</strong>.</p>
<p>In the above example of the UK income distribution two such measures are the median income (UKP 29,600) and the mean income (UKP 35,900). As we will see later, the fact that the mean is larger than the median actually tells us something important about the skewness of the distribution.</p>
<section id="the-mean" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="the-mean"><span class="header-section-number">4.2.1</span> The mean</h3>
<p>The simplest numerical summary (descriptive statistic) of location is the <strong>sample (arithmetic) mean</strong>:</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_{i}=\frac{(x_{1}+x_{2}+\ldots +x_{n})}{n}.
\end{equation*}\]</span></p>
<p>It is obtained by adding up all the values in the sample and dividing this total by the sample size. It uses all the observed values in the sample and is the most popular measure of location since it is particularly easy to deal with theoretically. You will see later that means play an important role when we come to statistical inference.</p>
<p>Let’s look at an example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You get the following 5 observations: 6, 2, 8, 10, 9</p>
<p><strong>What is the mean?</strong> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;7&quot;]"></p>
<p>** Which of the following are correct formulae for the calculation of the sample mean? (Multiple correct answers are possible)**</p>
<ul>
<li>A: <span class="math inline">\(\bar{x}=0.2 \cdot (6+2+8+10+9)\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">TRUE</option><option value="">FALSE</option></select></li>
<li>B: <span class="math inline">\(\bar{x}=\frac{1}{5} \cdot (6+2+8+10+9)\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">TRUE</option><option value="">FALSE</option></select></li>
<li>C: <span class="math inline">\(\bar{x}=(6+2+8+10+9)/5\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">TRUE</option><option value="">FALSE</option></select></li>
<li>D: <span class="math inline">\(\bar{x}=\frac{1}{4}(6+2+8+10+9)\)</span> <select class="webex-select"><option value="blank"></option><option value="">TRUE</option><option value="answer">FALSE</option></select></li>
<li>E: <span class="math inline">\(\bar{x}=\frac{1}{5}\cdot 6+\frac{1}{5}\cdot 2+\frac{1}{5}\cdot 8+\frac{1}{5}\cdot 10+\frac{1}{5}\cdot 9\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">TRUE</option><option value="">FALSE</option></select></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>You have the following information about a sample of values: 6,7,1,9,10. You also know that there were actually six observations in the sample and you know that the sample mean is 6. What is the missing observation?</p>
<p><input class="webex-solveme nospaces" size="1" data-answer="[&quot;3&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>The sample mean of 6 observations is 6, then the six observations add up ot 36. As the 5 given observations sum to 33, this implies that the missing information is 3.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>One way to estimate the number of insects and investigate the possible decline of the number of insects is to count insects “collected” on number plates (or to count insect splats). Read this <a href="https://news.sky.com/story/car-number-plate-squashed-bug-survey-shows-terrifying-decline-in-number-of-flying-insects-12605662">newsstory by Sky News</a>. As you can read there has been a large estimated decline of insects between 2004 when this study was performed first and 2021 when it was repeated. In the <a href="https://www.kentwildlifetrust.org.uk/sites/default/files/2022-05/Bugs%20Matter%202021%20National%20Report.pdf">the original research</a> you can also get the following pieces of information:</p>
<ul>
<li>In 2004, 196,448 insects were sampled over 14,466 journeys comprising 867,595 miles, a splat rate of 0.238 splats per mile.</li>
<li>In 2021, 11,712 insects were sampled over 3,348 journeys comprising 121,641 miles, a splat rate of 0.104 splats per mile.</li>
</ul>
<p><strong>What is the average number of insects splats found during a car journey in 2004 and 2021. (answer to 4 decimal points, 4dp, if not indicated otherwise)</strong></p>
<p>Average in 2004 = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;13.578&quot;]"></p>
<p>Average in 2021 = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;3.4982&quot;]"></p>
<p><strong>What is the average length of a journey (measured in miles) in 2004 and 2021.</strong></p>
<p>Average in 2004 = <input class="webex-solveme nospaces" size="7" data-answer="[&quot;59.9748&quot;]"></p>
<p>Average in 2021 = <input class="webex-solveme nospaces" size="7" data-answer="[&quot;36.3324&quot;]"></p>
<p><strong>What is the average number of insects splats found per driven mile 2004 and 2021.</strong></p>
<p>Average in 2004 = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2264&quot;,&quot;.2264&quot;]"></p>
<p>Average in 2021 = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.0963&quot;,&quot;.0963&quot;]"></p>
<p><strong>Why does just comparing the average splat rates per mile not give the best possible answer to the question of how much insects have declined?</strong></p>
<pre><code>    \begin{itemize}
        \item The sample in 2021 is significantly smaller than the sample in 2004.
        \item The car journeys in 2004 were significantly longer than those in 2021.
        \item Methods to measure the length of car journeys differed from 2004 (car odometer readings) to 2021 (an app calculated the journey length from satellite data)
    \end{itemize}</code></pre>
<div id="radio_EJOJQAQUOE" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_EJOJQAQUOE" value=""> <span>The sample in 2021 is significantly smaller than the sample in 2004.</span></label><label><input type="radio" autocomplete="off" name="radio_EJOJQAQUOE" value="answer"> <span>The car journeys in 2004 were significantly longer than those in 2021.</span></label><label><input type="radio" autocomplete="off" name="radio_EJOJQAQUOE" value=""> <span>Methods to measure the length of car journeys differed from 2004 (car odometer readings) to 2021 (an app calculated the journey length from satellite data)</span></label>
</div>
<div class="webex-solution">
<button>
Feedback
</button>
<p>The sample size should not be such a big issue. The sample in 2021 still feels fairly substantial. But the quite different average length of journey could indicate that the type of journeys undertaken could be quite different (e.g.&nbsp;relatively more build up areas in 2021), and that may make a difference for the number of insects collected. Different ways to measure important aspects like journey length might matter, but is unlikely to make a uge difference.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Special case - mean of binary variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>An important special case arises when we calculate the mean of a binary variable. Let’s say you have a sample of 7 people and you are interested in whether they have completed a university education. The data in the table below represent the available information.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Respondent</th>
<th>Uni Degree</th>
<th>u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="even">
<td>6</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Yes</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>The last column of the table is an alternative, and very useful way to represent this information. We created a new variable, <span class="math inline">\(u\)</span>, which takes the value 1 for all respondents who have a completed university degree and 0 for all others. We call this a binary variable, a variable which can take one of two outcomes.</p>
<p>When you calculate the sample mean of the new variable (<span class="math inline">\(u\)</span>) you obtain</p>
<p><span class="math display">\[\begin{equation*}
    \bar{u}=\frac{1}{7}\sum_{i=1}^{7} u_{i}=\frac{1}{7} \cdot 4 = \frac{4}{7} = 0.5714
\end{equation*}\]</span></p>
<p>This is the sample mean of the variable <span class="math inline">\(u\)</span> but also the proportion of respondents with a university degree. Here, and for future use, it is important that the sample proportion can be thought of as a sample mean (of the variable <span class="math inline">\(u\)</span>).</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What is the proportion of respondents who do not have a completed university degree?</strong></p>
<p><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.4286&quot;,&quot;.4286&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>As this is a binary variable this will be 1 - 0.5714. But it would also be the average calculated as follows: <span class="math inline">\(\frac{1}{7}\sum_{i=1}^{7} (1-u_{i})=\frac{1}{7} \cdot 3 = \frac{3}{7} = 0.4286\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="the-median" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="the-median"><span class="header-section-number">4.2.2</span> The median</h3>
<p>Another measure, with which you may be familiar, is the <strong>sample median</strong>. This does not use all the values in the sample and is obtained by finding the middle value in the sample, once all the observations have been ordered from the smallest value to the largest. Thus, <span class="math inline">\(50\%\)</span> of the observations are larger than the median and <span class="math inline">\(50\%\)</span> are smaller.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following sample of values: 6, 2, 8, 10, 9</p>
<p><strong>What is the mean?</strong> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;7&quot;]"></p>
<p><strong>What is the median?</strong> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;8&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>You get the median by re-arranging the values in ascending order and then identify the middle value, here: 2, 6, 8, 9, 10. As we have 5 observations the middle observation is the 3rd, hence 8.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>What to you do if you have an even number of observation? Say: 3, 9, 3, 4, 6, 7.\</p>
<p>You still line all the observations up in ascending order: 3, 3, 4, 6, 7, 9. Now you have two middle observation, the 3rd and the 4th, here these are 4 and 6. It is then the convention that we take the midpoint between these two values to get the median.</p>
<p><strong>What is the mean?</strong> <input class="webex-solveme nospaces" size="6" data-answer="[&quot;5.3333&quot;]"></p>
<p><strong>What is the median?</strong> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;5&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>So here the midpoint between 4 and 6 is 5. But really, any value between 4 and 6 meets the above definition of the median. Take for instance 4.5. 50% of observations are smaller than 4.5 and 50% are larger than 4.5. Therefore 4.5 also meets the definition of the median. But here we shall stick to the convention of using the average of the two middle values. (See the section on percentiles below for a follow up on this point)</p>
</div>
</div>
</div>
<p>As you can see from the above examples, to calculate the mean we use all the data in the sample. But for the median we only use the middle (or the two middle) observations. The median does not use all the data and is less influenced by extreme values (or outliers), compared to the sample mean. For example, when investigating income distributions it is found that the mean income is typically higher than the median income. You can see that also from the above graphical representation of the UK income distribution, where the mean income is around UKP 6000 larger than the median.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Return to the previous exercise with sample of values: 6, 2, 8, 10, 9. For these values the sample mean was 7 and the median was 8. Let us assume that the largest of these values is actually a 100 not a 10. What are the mean and median in this case?</p>
<p><strong>What is the mean?</strong> <input class="webex-solveme nospaces" size="2" data-answer="[&quot;25&quot;]"></p>
<p><strong>What is the median?</strong> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;8&quot;]"></p>
<p>Imagine the highest <span class="math inline">\(10\%\)</span> of earners in a country double their income, but the income of everyone else remains constant. What effect will that have on the mean on the one hand, and the median on the other?</p>
<p>The mean will <select class="webex-select"><option value="blank"></option><option value="answer">increase</option><option value="">not change</option><option value="">decrease</option></select></p>
<p>The median will <select class="webex-select"><option value="blank"></option><option value="">increase</option><option value="answer">not change</option><option value="">decrease</option></select></p>
</div>
</div>
</section>
<section id="weighted-mean" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="weighted-mean"><span class="header-section-number">4.2.3</span> Weighted mean</h3>
<p>In some situations, it makes more sense to use a <strong>weighted sample mean</strong>, rather than the arithmetic mean. Before we look at what a weighted mean does we shall reformulate the arithmetic mean to the following equivalent formula:</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{x}&amp;=&amp;\frac{1}{n}\sum_{i=1}^{n}x_{i}=\frac{(x_{1}+x_{2}+\ldots +x_{n})}{n}\\
    &amp;=&amp;\frac{1}{n} x_{1}+\frac{1}{n}x_{2}+\ldots +\frac{1}{n}x_{n}
\end{eqnarray*}\]</span></p>
<p>You can see from the last form that the mean is a weighted sum of all observations where each observation obtains the same weight of <span class="math inline">\(\frac{1}{n}\)</span>.</p>
<p>Let’s say you want to figure out what the Covid incidence in Belgium, France, Luxembourg and Netherlands is in Week 10 of 2022. You have the following table with observation (drawn from spreadsheet, Covid_ECDC.xlsx, sheet: CrossSection).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Week</th>
<th>Case Rate</th>
<th>Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Belgium</td>
<td>2022 - Week 10</td>
<td>879.8</td>
<td>11,566,041</td>
</tr>
<tr class="even">
<td>France</td>
<td>2022 - Week 10</td>
<td>1192.0</td>
<td>67,656,682</td>
</tr>
<tr class="odd">
<td>Luxembourg</td>
<td>2022 - Week 10</td>
<td>1726.2</td>
<td>634,730</td>
</tr>
<tr class="even">
<td>Netherlands</td>
<td>2022 - Week 10</td>
<td>4795.3</td>
<td>17,475,415</td>
</tr>
</tbody>
</table>
<p>Let’s say you calculate the arithmetic mean for the case rate (14-day average, calculated per 100,000 population) for these countries.</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}=\frac{1}{4}\sum_{i=BEL}^{NED}x_{i}=\frac{1}{4} \cdot 879.8 + \frac{1}{4} \cdot 1192.0 +\frac{1}{4} \cdot 1726.2 +\frac{1}{4} \cdot 4795.3  = 2,148.3
\end{equation*}\]</span></p>
<p>So the mean value is 2,148.3. Is that the case rate in the four countries taken together? \ No it is not. In the above calculation we weighted the data for France in the same way as that of Luxembourg although the latter only has about 1% of France’s population. If we wanted to use the above data to calculate what the Case rate across the four countries is we should take the different country sizes into account. Let’s supplement the above table with a new column which calculates the proportion of population each of the four countries has of the combined population (97,332,868).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Country</th>
<th>Week</th>
<th>Case Rate</th>
<th>Population</th>
<th>Pop prop, <span class="math inline">\(w_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Belgium</td>
<td>2022 - Week 10</td>
<td>879.8</td>
<td>11,566,041</td>
<td>0.119</td>
</tr>
<tr class="even">
<td>France</td>
<td>2022 - Week 10</td>
<td>1192.0</td>
<td>67,656,682</td>
<td>0.695</td>
</tr>
<tr class="odd">
<td>Luxembourg</td>
<td>2022 - Week 10</td>
<td>1726.2</td>
<td>634,730</td>
<td>0.006</td>
</tr>
<tr class="even">
<td>Netherlands</td>
<td>2022 - Week 10</td>
<td>4795.3</td>
<td>17,475,415</td>
<td>0.180</td>
</tr>
</tbody>
</table>
<p>As you can see, France has 69.5% (0.695) of the combined population and Luxembourg only 0.6% (0.006). So when we calculate the case rate across the four countries we should weigh France much higher. Note that the weights do sum to 1!</p>
<p>The way in which we calculate a case rate which then represents the (population weighted) average across the four countries is</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}_w=0.119 \cdot 879.8 + 0.695 \cdot 1192.0 +0.006 \cdot 1726.2 +0.180 \cdot 4795.3  = 1,806.659
\end{equation*}\]</span></p>
<p>Therefore the population weighted average is 1,806.659, a fair bit lower than the unweighted average.</p>
<p>Let’s look at the general formula for the weighted average:</p>
<p><span class="math display">\[\begin{equation*}
    \bar{x}_w=\sum_{i=1}^{n}w_{i}x_{i}=w_{1}x_{1}+w_{2}x_{2}+\ldots+w_{n}x_{n}.
\end{equation*}\]</span></p>
<p>where the weights <span class="math inline">\(\left( w_{1},\ldots ,w_{n}\right)\)</span> satisfy <span class="math inline">\(\sum_{i=1}^{n}w_{i}=1\)</span>. Note that equal weights of <span class="math inline">\(w_{i}=n^{-1}\)</span>, for all <span class="math inline">\(i\)</span>, gives the arithmetic mean. This type of average statistic if often used in the construction of index numbers (such as the Consumer Price Index, CPI) and it comes into play whenever we have data from different categories that are of different importance (as countries in the above example). In the calculation of the CPI this is relevant as price increases for food items are more important than price increases for music, as the purchases for the latter use a smaller proportion of a typical income.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following data on the youth unemployment rate in the following cities/towns</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>City</th>
<th>Unemployment Rate</th>
<th>Population (18-25 yrs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Springfield</td>
<td>29.9</td>
<td>6,241</td>
</tr>
<tr class="even">
<td>Duckburg</td>
<td>11.0</td>
<td>452,189</td>
</tr>
<tr class="odd">
<td>Ningzhou</td>
<td>13.9</td>
<td>7,457,632</td>
</tr>
<tr class="even">
<td>Gotham City</td>
<td>16.4</td>
<td>13,298,115</td>
</tr>
</tbody>
</table>
<p><strong>What is the arithmetic (unweighted) mean?</strong> <input class="webex-solveme nospaces" size="4" data-answer="[&quot;17.8&quot;]"></p>
<p><strong>What is the (population) weighted mean?</strong> <input class="webex-solveme nospaces" size="2" data-answer="[&quot;15&quot;]"></p>
</div>
</div>
<p>Note that in the above examples we used populations as the weighting variable. We also mentioned the calculation of a price index. In that example the weighting variable would be something like budget shares (food - high weight, music - low weight). The appropriate weighting variable depends on what you want to calculate.</p>
</section>
<section id="summary-of-average-measures" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="summary-of-average-measures"><span class="header-section-number">4.2.4</span> Summary of average measures</h3>
<p>All the above measures of location can be referred to as an <strong>average</strong>. One must, therefore, be clear about what is being calculated. Two politicians may quote two different values for the “average income in the U.K.”; both are probably right, but are computing two different measures!</p>
<p>There is another important difference between the <strong>arithmetic average</strong> and the <strong>median</strong>. The arithmetic average is really only applicable for continuous data, while the median can also be applied to discrete data which are ordinal (i.e.&nbsp;have a natural ranking). This makes the median applicable to a much wider range of data.</p>
<p>You may now ask what measure of central tendency is to be applied for nominal data (categorical data where the categories have no natural ordering). Neither the arithmetic average nor the median are applicable. The statistic to be used here is called the <strong>mode</strong> and it is that category that is represented the most amongst your dataset. Say you have 100 observations of which 55 are female and 45 male. Here the mode category for the gender variable is female.</p>
<p>One last note. Any of our statistics is based on a set of <span class="math inline">\(n\)</span> observations. This language assumes that the observations we have is a sample only. The statistic <span class="math inline">\(\bar{x}\)</span> is therefore often also called the <strong>sample mean</strong>. As we are usually interested in the mean of the entire population we use the sample mean as an estimate of the unknown population mean (which is often represented by <span class="math inline">\(\mu\)</span>). Using <span class="math inline">\(\bar{x}\)</span> to learn about <span class="math inline">\(\mu\)</span> is what we call inference and is an important later topic.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Samplemean.jpg" class="img-fluid figure-img"></p>
<figcaption>Population mean and sample mean.</figcaption>
</figure>
</div>
</section>
<section id="percentiles" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="percentiles"><span class="header-section-number">4.2.5</span> Percentiles</h3>
<p>So far all measures of location introduced are in some way measures of the typical, middle or average value. But we can think of other locations in a distribution. Consider the median. We lined up all the values (or in Excel you would sort the values) according to their size. Then you find a value which splits this line-up into half, or 50% smaller and 50% larger. That value was called the median. We choose 50% on either side as we were looking for something like the middle or average value.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Percentile.jpeg" class="img-fluid figure-img"></p>
<figcaption>50th Percentile.</figcaption>
</figure>
</div>
<p>That is not always what we want. In particular when looking at income distributions we are often interested in other percentage splits. For instance we may want to know what the income is which 20% of the population do not exceed. Or in other words the income where 20% earn less and 80% earn more. We shall call this the 20th percentile. Or we may be interested in the income which only 1% of the population exceed (or 99% earn less), the 99th percentile. The Occupy movement actually adopted “We are the 99%” as a <a href="https://en.wikipedia.org/wiki/We_are_the_99%25">political slogan</a>.</p>
<p>The median is therefore identical to the 50th percentile.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Percentile2.jpeg" class="img-fluid figure-img"></p>
<figcaption>Percentiles.</figcaption>
</figure>
</div>
<p>All these percentiles are calculated in the same manner, starting with a line-up of all observations in order of their size. Then find a value which splits the data as requested.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s consider the following sample with 10 observations, which are already in ascending order:\ 15, 18, 23, 28, 30, 35, 39, 48, 59, 80</p>
<p>What is the 50th percentile?</p>
<p>50th percentile = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;32.5&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>You may remember from the discussion of the median, that actually any value between 30 and 35 could be the median, but that the convention is, for the median, to use the midpoint between 30 and 35.</p>
</div>
</div>
</div>
<p>Before we move to calculate other percentiles, let us first ask what percentile, for example, 18 is. 18 is one of the observations in the sample. There is one observation which is lower than 18 and eight which are larger. Therefore, <span class="math inline">\(1/(1+8)=1/9=0.111111\)</span> or 11.1111% of observations are lower than 18.</p>
<p>What percentile is 23? <span class="math inline">\(2/(2+7)=2/9=0.222222\)</span> or 22.2222% of observations are lower than 23. Think of these as exact percentiles. There is no other value which could be this percentile.</p>
<p>So when we calculate the 20th percentile, then we know that the 20th percentile is somewhere between 18 and 23. If you again took the midpoint between the two observations you would get 20.5 and indeed you would have 20% of observations below (only 15 and 18) and 80% of observations above (all eight from 23 to 80). But 20.5 is not unique. 21.1 would have the same property. In fact for any number between 18 and 23 you could say that 20% of observations are below and 80% of observations are above. The convention to calculate such a percentile is as follows:</p>
<ul>
<li>Calculate how, relatively close the the percentile is to the two nearest exact percentiles: <span class="math display">\[\begin{equation*}
      \frac{0.2-0.1111}{0.2222-0.1111}=\frac{0.2-(1/9)}{(2/9)-(1/9)}= 0.8
  \end{equation*}\]</span> So the 20th percentile is at 80% of the distance between the 11.1111th percentile and the 22.2222th percentile.</li>
<li>Which value is 80% of the distance between the 11.1111th percentile (which is 18) and the 22.2222th percentile (which is 23)? <span class="math inline">\(18+0.8 \cdot (23-18) = 22\)</span>. This is the 20th percentile.</li>
</ul>
<p>In a similar way we are calculating the 90th percentile. We know that it has to lie between 59 and 80. We know that as 88.89% (=<span class="math inline">\(8/9\)</span>) of observations are smaller than 59, and therefore the 90% percentile has to be between 59 and 80, as 80 is the largest observation and hence the 100th percentile. Where is the 90th percentile relative to the 88.89th and the 100th percentile (which is here the largest observation of 80)? <span class="math inline">\((0.9-(8/9))/(1-8/9)= 0.1)\)</span>. It is 10% the distance between 59 and 80. Therefore the 90th percentile is <span class="math inline">\(59 + 0.1 \cdot (80-59) = 61.1\)</span>.</p>
<p>You can do this with any percentile.</p>
<section id="example-2" class="level4 callout-info" data-number="4.2.5.1">
<h4 data-number="4.2.5.1" class="anchored" data-anchor-id="example-2"><span class="header-section-number">4.2.5.1</span> Example</h4>
<p>What is the 27th percentile?</p>
<p><span class="math inline">\(23 + (0.27-(2/9))/(1/9) \cdot (28-23)= 23 + 0.43 \cdot 5 = 25.15\)</span></p>
</section>
<section id="percentile-calculation-in-excel-and-in-programming-languages" class="level4 callout-info" data-number="4.2.5.2">
<h4 data-number="4.2.5.2" class="anchored" data-anchor-id="percentile-calculation-in-excel-and-in-programming-languages"><span class="header-section-number">4.2.5.2</span> Percentile calculation in Excel and in Programming Languages</h4>
<p>The algorithm described above is exactly what softwares like Excel, R and Python do when they calculate percentiles. This is why we follow this convention. In Excel you can actually find two functions to calculate a percentile. The function you should use is the “PERCENTILE.INC” function.</p>
</section>
<p>There are a few special percentiles which you may come across at times and it is good to recognise these names.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Percentile</th>
<th>Alternative name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10th</td>
<td>Bottom/Lower decile</td>
</tr>
<tr class="even">
<td>20th</td>
<td>Bottom/Lower quintile</td>
</tr>
<tr class="odd">
<td>25th</td>
<td>Bottom/Lower quartile</td>
</tr>
<tr class="even">
<td>50th</td>
<td>Median</td>
</tr>
<tr class="odd">
<td>75th</td>
<td>Top/Upper quartile</td>
</tr>
<tr class="even">
<td>80th</td>
<td>Top/Upper quintile</td>
</tr>
<tr class="odd">
<td>90th</td>
<td>Top/Upper decile</td>
</tr>
</tbody>
</table>
</section>
<section id="further-reading" class="level3" data-number="4.2.6">
<h3 data-number="4.2.6" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">4.2.6</span> Further Reading</h3>
<p>The Khan Academy has a number of good resources:</p>
<ul>
<li><a href="https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/mean-and-median/v/statistics-intro-mean-median-and-mode">Intro to Measures of Central Tendency</a></li>
<li><a href="https://www.khanacademy.org/math/probability/descriptive-statistics/central_tendency/v/mean-median-and-mode">An example for mean , median and mode calculation</a></li>
<li><a href="https://www.khanacademy.org/math/statistics-probability/sampling-distributions-library/sample-means/v/statistics-sample-vs-population-mean">A short discussion of the relation between sample and population mean</a></li>
</ul>
</section>
</section>
<section id="dispersion" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="dispersion"><span class="header-section-number">4.3</span> Dispersion</h2>
<p>A measure of <strong>dispersion</strong> (or variability) tells us something about how much the values in a sample differ from one another. The easiest measure of dispersion is called the <strong>range</strong>. All it measures is the difference between the largest and the smallest value in your observations. While this can be an informative piece of information, it has many shortcomings. First and foremost that it is influenced by outliers. Further, it only uses the two most extreme observations in the calculation. We therefore ignore a whole lot of information.</p>
<p>What we are really after is a measure of how closely your observations are distributed around the central location.</p>
<p>Let’s start with a very simple example, two samples of data (<span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>) with two observations each. For both samples the sample mean is identical, <span class="math inline">\(\bar{x}=\bar{y}=4\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 25%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Sample X</th>
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(d_i=x_i-\bar{x}\)</span></th>
<th></th>
<th>Sample Y</th>
<th><span class="math inline">\(y_i\)</span></th>
<th><span class="math inline">\(d_i=y_i-\bar{y}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Obs 1</td>
<td>6</td>
<td>2</td>
<td></td>
<td>Obs 1</td>
<td>8</td>
<td>4</td>
</tr>
<tr class="even">
<td>Obs 2</td>
<td>3</td>
<td>-1</td>
<td></td>
<td>Obs 2</td>
<td>3</td>
<td>-1</td>
</tr>
<tr class="odd">
<td>Obs 3</td>
<td>3</td>
<td>-1</td>
<td></td>
<td>Obs 3</td>
<td>1</td>
<td>-3</td>
</tr>
</tbody>
</table>
<p>The columns <span class="math inline">\(x_i-\bar{x}\)</span> and <span class="math inline">\(y_i-\bar{y}\)</span> are the deviations from the respective arithmetic mean:</p>
<p><span class="math display">\[\begin{equation*}
    d_{i}=x_{i}-\bar{x}
\end{equation*}\]</span></p>
<p>This measure is at the core of most measures of dispersion. It describes how much a value differs from the <strong>mean</strong>. The following image illustrates how to think of these deviations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/SampleVariance.png" class="img-fluid figure-img"></p>
<figcaption>Deviations from the mean for Samples X and Y.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Looking at the above Table, which of the two samples are more dispersed?</p>
<p>Answer: <input class="webex-solveme nospaces" size="1" data-answer="[&quot;Y&quot;]"></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p>On average the observations from Sample Y are further away from the mean than those in Sample X.</p>
</div>
</div>
</div>
<p>What we want is a statistic, one value, which tells us something about the dispersion of the observations. As an average measure of deviation from <span class="math inline">\(\bar{x}\)</span>, we could consider the arithmetic mean of deviations, but this will <strong>always</strong> be zero. Confirm that for Sample X and Sample Y, but it will actually always be true. In other words the positive and negative deviations from <span class="math inline">\(\bar{x}\)</span> (or <span class="math inline">\(\bar{y}\)</span>) will always cancel each other out.</p>
<p>The key to understanding this is that, in terms of dispersion, it does not matter whether the deviation <span class="math inline">\(d_i\)</span> is positive or negative. We need to find ways to summarise the extend of deviation. We could either look at the absolute deviation <span class="math inline">\(\left| d_{i}\right|\)</span> (leading to the Mean Absolute Deviation - MAD - below) or at the squared deviation, <span class="math inline">\(d_{i}^2\)</span> (leading to Mean Squared Deviation - MSD. Based on these two measures of dispersion the following two statistics are available:</p>
<ul>
<li>MAD: <span class="math inline">\(\frac{1}{n}\sum_{i=1}^{n}\left| d_{i}\right| =\frac{1}{n}\sum_{i=1}^{n}\left| x_{i}-\bar{x}\right| &gt;0\)</span></li>
<li>MSE: <span class="math inline">\(\frac{1}{n}\sum_{i=1}^{n}d_{i}^{2}=\frac{1}{n}\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}&gt;0\)</span></li>
</ul>
<p>The MSD is easier to work with and lends itself to theoretical treatment. A more commonly used name for MSD is the <strong>variance</strong>. As you can see from the formula, it is calculated on the basis of <span class="math inline">\(n\)</span> observations. If the data represent your relevant population then the formula for MSD is referred to as the <strong>population variance</strong> and it is often represented by <span class="math inline">\(\sigma^2\)</span>. If your observations represent a sample, then the formula for MSD is changed by replacing the factor <span class="math inline">\(1/n\)</span> with <span class="math inline">\(1/(n-1)\)</span>:</p>
<p><span class="math display">\[\begin{equation*}
    s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}
\end{equation*}\]</span></p>
<p>This is what is usually called the <strong>sample variance</strong>, abbreviated with <span class="math inline">\(s^2\)</span>. The slightly changed factor is due to ensures that <span class="math inline">\(s^2\)</span> is an unbiased estimator for the unknown <span class="math inline">\(\sigma^2\)</span> which is the term we are usually interested in. In a later topic we will talk about this property of unbiasedness. For now, just accept this.</p>
<section id="example-3" class="level4 callout-info" data-number="4.3.0.1">
<h4 data-number="4.3.0.1" class="anchored" data-anchor-id="example-3"><span class="header-section-number">4.3.0.1</span> Example</h4>
<p>Calculate the sample variance of samples X and Y:\</p>
<p>Sample X: <span class="math inline">\(s^2=\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;3&quot;]"></p>
<p>Sample Y: <span class="math inline">\(s^2=\)</span> <input class="webex-solveme nospaces" size="2" data-answer="[&quot;13&quot;]"></p>
</section>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Degrees of Freedom
</div>
</div>
<div class="callout-body-container callout-body">
<p>To calculate the sample variance we divide the sum of the squared deviations by <span class="math inline">\(n-1\)</span> and not by the sample size <span class="math inline">\(n\)</span>. We call <span class="math inline">\(n-1\)</span> the degrees of freedom. Degrees of freedom are a concept that we will encounter frequently when it comes to statistical inference.</p>
<p>Consider Sample X above. We had three observations. We used the three observations to calculate the sample mean <span class="math inline">\(\bar{x}=4\)</span> which we then, in turn, need to calculate <span class="math inline">\(s^2\)</span>. Think about the following, you want to change sample values in a way which delivers the same sample mean. You changed two already, observation 1 you changed from 6 to 8 and observation 2 you changed from 3 to 4. What could the third observation be? Well in fact you cannot chose, it has to be 0. The only way to have a sample of three where two observations are 8 and 4 and the sample mean is 4 is for the third observation to be 0. So you actually only had 2 (or 3-1) degrees of freedom.</p>
</div>
</div>
<p>The variance measures have two major disadvantages:</p>
<ul>
<li>The value you get for either <span class="math inline">\(\sigma^2\)</span> or <span class="math inline">\(s^2\)</span> has no easy interpretation. This is obvious when you think about the units in which the variance is measured. If your data are, say, income data, then the unit of the variance is <span class="math inline">\(\pounds ^2\)</span>. But what is the meaning of a squared pound sterling.</li>
<li>The variances for different data sets are almost impossible to compare. The reason for that is best seen by realising that the value of the variance will change if you multiply each value by 2. However, if we multiply each observation by two, then really, nothing has changed about the dispersion of our data.</li>
</ul>
<p>In order to address the first of these shortcomings we often refer to a different measure of dispersion, the <strong>standard deviation</strong>. This is related to the variance. In fact, once you calculated the variance you can obtain the standard deviation by taking the square root of your calculated variance</p>
<ul>
<li>Population standard deviation: <span class="math inline">\(\sigma=\sqrt{\sigma^2}=\sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_{i}-\mu)^{2}}\)</span></li>
<li>Sample standard deviation: <span class="math inline">\(s=\sqrt{s^2}=\sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}}\)</span></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/PopSampleScheme.png" class="img-fluid figure-img"></p>
<figcaption>Variance and standard deviation.</figcaption>
</figure>
</div>
<p>Once you calculated your sample (or population) standard deviation, you can say that the average deviation of your observation from the mean is <span class="math inline">\(s\)</span> (or <span class="math inline">\(\sigma\)</span>). As the variance is always a positive measure, so is the square root of the variance, the <strong>standard deviation</strong>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>You have the following five observations:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21 32  7 34 50</code></pre>
</div>
</div>
<p>Assuming that this is the <strong>population</strong>, calculate the following (all to 4 dp):</p>
<p>Mean, <span class="math inline">\(\mu\)</span> = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;28.8&quot;]"></p>
<p>Variance, <span class="math inline">\(\sigma^2\)</span> = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;204.56&quot;]"></p>
<p>Standard deviation, <span class="math inline">\(\sigma\)</span> = <input class="webex-solveme nospaces" size="7" data-answer="[&quot;14.3024&quot;]"></p>
<p>Assuming that these observations are a <strong>sample</strong>, calculate the following (all to 4 dp):</p>
<p>Mean, <span class="math inline">\(\bar{x}\)</span> = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;28.8&quot;]"></p>
<p>Variance, <span class="math inline">\(s^2\)</span> = <input class="webex-solveme nospaces" size="5" data-answer="[&quot;255.7&quot;]"></p>
<p>Standard deviation, <span class="math inline">\(s\)</span> = <input class="webex-solveme nospaces" size="7" data-answer="[&quot;15.9906&quot;]"></p>
<p>A veterinarian weighed a sample of 6 puppies. Here are each of their weights (in kilograms): 1, 2, 7, 7, 10, 15.</p>
<p>The mean of these weights is <input class="webex-solveme nospaces" size="1" data-answer="[&quot;7&quot;]"> <span class="math inline">\(kg\)</span></p>
<p>The variance is <input class="webex-solveme nospaces" size="4" data-answer="[&quot;26.8&quot;]"> <span class="math inline">\(kg^2\)</span></p>
<p>The standard deviation is <input class="webex-solveme nospaces" size="4" data-answer="[&quot;5.18&quot;]"> <span class="math inline">\(kg\)</span></p>
<div class="webex-solution">
<button>
Feedback
</button>
<p><a href="https://youtu.be/9jjOrKp8BKg">Solution video, YouTube (7min)</a>.</p>
</div>
</div>
</div>
</section>
<section id="measures-of-skewness-and-higher-order-moments" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="measures-of-skewness-and-higher-order-moments"><span class="header-section-number">4.4</span> Measures of skewness and higher order moments</h2>
<p>Especially when we think back to the example of the income distribution, we recognise that the income distribution is not symmetric. Here is an image of a symmetric, left/negative skewed and right/positive skewed distribution.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/SkewedDist.png" class="img-fluid figure-img"></p>
<figcaption>Symmetric and skewed distributions.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>The income distribution in the UK is <select class="webex-select"><option value="blank"></option><option value="answer">symmetric</option><option value="answer">right skewed</option><option value="">left skewed</option></select>.</p>
</div>
</div>
<p>It is important to recognise that the relation between the mean and the median tells us something about the skewness of a distribution. This is best illustrated with the following images.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/SymmetricDist.png" class="img-fluid figure-img"></p>
<figcaption>Symmetric and skewed distributions.</figcaption>
</figure>
</div>
<p>When you are dealing with a symmetric distribution you will find the mean and the median to be the same. When we are dealing with sample data they may not be identical but very similar. The next image displays a typical left skewed distribution.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/LeftSkewedDist.png" class="img-fluid figure-img"></p>
<figcaption>Left Skewed distribution.</figcaption>
</figure>
</div>
<p>Here you can see that the mean is smaller than the median. We are having a few values of our random variable which are very small and they “drag down” the mean, but do not effect the median so much.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the UK income distribution the mean income is <select class="webex-select"><option value="blank"></option><option value="">smaller than</option><option value="">equal</option><option value="answer">larger than</option></select> the median income?</p>
</div>
</div>
<p>There are formal measures of skewness. We shall not introduce these in detail here. Not surprisingly one popular measure is based on comparing the sample mean and median.</p>
</section>
<section id="measures-of-inequality" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="measures-of-inequality"><span class="header-section-number">4.5</span> Measures of inequality</h2>
<p>Let us briefly return to the example of income inequality we started this lesson with. As you know, inequality is a major political and societal issue with lots of economic implications. We often differentiate between income and wealth inequality. But let’s briefly think about the income distribution introduced at the beginning of the chapter and reproduced here.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/UK_IncomeDistribution_2019.png" class="img-fluid figure-img"></p>
<figcaption>UK IncomeDistribution 2019.</figcaption>
</figure>
</div>
<p>Two of the descriptive statistics we introduced already speak to aspects of inequality. Firstly the variance or standard deviation is a measure of the variety of incomes we see. The larger this measure the more differences we see in incomes. The second measure which is important in the context of this discussion is the skewness. We saw that the income distribution is right (positively) skewed meaning that we have lots of incomes at the lower end and a few very large incomes.</p>
<p>A lot of effort has gone into measuring the amount of inequality in different countries and across time. An excellent example of this is the <a href="https://www.chartbookofeconomicinequality.com/">Chartbook of Economic Inequality</a>. This has been set up by <a href="https://www.tony-atkinson.com/">Anthony Atkinson</a> (1944-2017) who was a true giant in economic research into inequality.</p>
<p>Ideally one would want to develop one descriptive statistic that expresses all there is to learn from an income distribution about inequality. But there is no one such measure. The following measures, all of them essentially descriptive statistics describing certain aspects of an income distribution, are often used:</p>
<ul>
<li>The Gini Index. This is a measure which measures how far away from an equal distribution a particular income distribution is. Higher measures implying more inequality. In 2014 this measure was 34 in the UK, compared to 25.75 in 1980.</li>
<li>Income Shares. For instance what share to the top 1% income earners have of the total income. In the UK that is currently around 13%</li>
<li>Top percentiles as percentage of median income. For instance currently in the top decile income is around 200% of the Median income.</li>
<li>Percentage of people with income below a certain level. E.g. currently in the UK around 15% of people live in households with income less than 60% of the median income.</li>
</ul>
<p>Here we will not discuss the details of these measures. The following graph displays how these measures have evolved, for the UK, through time.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/UKinequality.png" class="img-fluid figure-img"></p>
<figcaption>Measures of income inequality, UK. Source: The Chartbook of Economic Inequality.</figcaption>
</figure>
</div>
<p>As you can see, inequality generally reduced through the 20th Century until around 1980. Since, the general direction of travel was that inequality increased.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find on the website of <a href="https://www.chartbookofeconomicinequality.com">The Chartbook of Economic Inequality</a> the equivalent country chart for Malaysia.</p>
<p>Which of the following statements are correct? (multiple answers are possible)</p>
<div id="radio_FVTARRSXOP" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_FVTARRSXOP" value=""> <span>The general development of inequality in Malaysia (since 1950) is similar to that in the UK.</span></label><label><input type="radio" autocomplete="off" name="radio_FVTARRSXOP" value="answer"> <span>The level of poverty has decreased fairly steadily.</span></label><label><input type="radio" autocomplete="off" name="radio_FVTARRSXOP" value="answer"> <span>Top earners have not increased their share of income.</span></label><label><input type="radio" autocomplete="off" name="radio_FVTARRSXOP" value="answer"> <span>In general Malaysia has decreasing inequality.</span></label><label><input type="radio" autocomplete="off" name="radio_FVTARRSXOP" value=""> <span>The Gini coefficients of the UK and Malaysia indicate that the Malaysian income distribution is more equal than that of the UK.</span></label>
</div>
<div class="webex-solution">
<button>
Feedback
</button>
<p>While the change in inequality has lately been in different directions in the UK (increasing) and Malaysia (decreasing), Malaysia has a higher Gini coefficient indicating a higher level of inequality than the UK.</p>
</div>
</div>
</div>
</section>
<section id="further-resources" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="further-resources"><span class="header-section-number">4.6</span> Further Resources</h2>
<p>On the Khan Academy you can find more practice:</p>
<ul>
<li>An example for the <a href="https://www.khanacademy.org/math/probability/descriptive-statistics/variance_std_deviation/v/variance-of-a-population">calculation of the population variance</a></li>
<li><a href="https://www.khanacademy.org/math/probability/descriptive-statistics/variance_std_deviation/v/sample-variance">Why do we need the sample variance?</a></li>
<li>These two clips illustrates nicely why the sample variance uses the factor <span class="math inline">\(1/(n-1)\)</span>. <a href="https://www.khanacademy.org/math/probability/descriptive-statistics/variance_std_deviation/v/review-and-intuition-why-we-divide-by-n-1-for-the-unbiased-sample-variance">First:</a> giving an intuitive explanation of why we need the factor <span class="math inline">\(1/(n-1)\)</span>. <a href="https://www.khanacademy.org/math/probability/descriptive-statistics/variance_std_deviation/v/simulation-showing-bias-in-sample-variance">Second:</a> useing a simulation to convince you.</li>
</ul>


</section>

</main> <!-- /main -->
<script src="include/webex.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./graphical_descriptive.html" class="pagination-link" aria-label="Graphical Descriptive Statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./CorrelationRegressionCausation.html" class="pagination-link" aria-label="Correlation, Regression and Causation">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>