<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Hypothesis Testing – Statistics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./Sampling_Dist.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./HypothesisTesting.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphical_descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CorrelationRegressionCausation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DealingWithDataSets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dealing with real life datasets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IntroToProbability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introducing Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ConditionalProbability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DiscreteRVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete Random Variables and Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ContinuousRVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Random Variables and Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Normal_RV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Normally Distributed Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Comb_of_RVs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Combination of Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Sampling_Dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./HypothesisTesting.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">14.1</span> Introduction</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">14.2</span> Hypothesis Testing</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses"><span class="header-section-number">14.3</span> Hypotheses</a></li>
  <li><a href="#null-hypotheses" id="toc-null-hypotheses" class="nav-link" data-scroll-target="#null-hypotheses"><span class="header-section-number">14.4</span> Null hypotheses</a></li>
  <li><a href="#alternative-hypotheses" id="toc-alternative-hypotheses" class="nav-link" data-scroll-target="#alternative-hypotheses"><span class="header-section-number">14.5</span> Alternative hypotheses</a></li>
  <li><a href="#types-of-error" id="toc-types-of-error" class="nav-link" data-scroll-target="#types-of-error"><span class="header-section-number">14.6</span> Types of Error</a></li>
  <li><a href="#p-values" id="toc-p-values" class="nav-link" data-scroll-target="#p-values"><span class="header-section-number">14.7</span> p-values</a></li>
  <li><a href="#decision-rules" id="toc-decision-rules" class="nav-link" data-scroll-target="#decision-rules"><span class="header-section-number">14.8</span> Decision Rules</a>
  <ul class="collapse">
  <li><a href="#an-alternative-decision-rule-design" id="toc-an-alternative-decision-rule-design" class="nav-link" data-scroll-target="#an-alternative-decision-rule-design"><span class="header-section-number">14.8.1</span> An alternative decision rule design</a></li>
  </ul></li>
  <li><a href="#different-sampling-distributions-for-the-sample-mean" id="toc-different-sampling-distributions-for-the-sample-mean" class="nav-link" data-scroll-target="#different-sampling-distributions-for-the-sample-mean"><span class="header-section-number">14.9</span> Different Sampling Distributions for the sample mean</a>
  <ul class="collapse">
  <li><a href="#working-with-the-t-distribution" id="toc-working-with-the-t-distribution" class="nav-link" data-scroll-target="#working-with-the-t-distribution"><span class="header-section-number">14.9.1</span> Working with the t-distribution</a></li>
  <li><a href="#intermediate-summary" id="toc-intermediate-summary" class="nav-link" data-scroll-target="#intermediate-summary"><span class="header-section-number">14.9.2</span> Intermediate Summary</a></li>
  </ul></li>
  <li><a href="#other-hypothesis-tests" id="toc-other-hypothesis-tests" class="nav-link" data-scroll-target="#other-hypothesis-tests"><span class="header-section-number">14.10</span> Other hypothesis tests</a>
  <ul class="collapse">
  <li><a href="#testing-for-a-population-proportion" id="toc-testing-for-a-population-proportion" class="nav-link" data-scroll-target="#testing-for-a-population-proportion"><span class="header-section-number">14.10.1</span> Testing for a population proportion</a></li>
  <li><a href="#testing-for-the-equality-of-means" id="toc-testing-for-the-equality-of-means" class="nav-link" data-scroll-target="#testing-for-the-equality-of-means"><span class="header-section-number">14.10.2</span> Testing for the equality of means</a></li>
  <li><a href="#testing-for-independence-of-two-categorical-random-variables" id="toc-testing-for-independence-of-two-categorical-random-variables" class="nav-link" data-scroll-target="#testing-for-independence-of-two-categorical-random-variables"><span class="header-section-number">14.10.3</span> Testing for independence of two categorical random variables</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">14.10.4</span> Summary</a></li>
  </ul></li>
  <li><a href="#extra-reading" id="toc-extra-reading" class="nav-link" data-scroll-target="#extra-reading"><span class="header-section-number">14.11</span> Extra reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">14.1</span> Introduction</h2>
<p>A short introductory video on hypothesis testing (YouTube, 2min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/HZpxXdzc1RM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Parameters in a population of interest are usually unknown. Say the average house price in Greater Manchester 2021, or the median, or the 90th percentile, or the variance of house prices, or the proportion of property transactions that happened at a price larger than UKP 1million. All of these are population parameters which typically are unknown.</p>
<p>You have learned that we can use the information in a sample, for instance the sample mean, to estimate such unknown population parameters. So we now know how to estimate population means, variances and proportions. In the section on sampling you learned that sample means <span class="math inline">\(\bar{X}\)</span> are random variables which have a distribution. In particular you learned from the CLT that the sample mean is, for a big enough sample, normally distributed.</p>
<p>While we talked about the sample mean <span class="math inline">\(\bar{X}\)</span> as an estimate for the population mean (<span class="math inline">\(\mu\)</span>), there are different population parameters we may be interested in and their sample estimators.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 43%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Population Parameter</th>
<th>Estimator</th>
<th>Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean: <span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\bar{X}=\dfrac{1}{n}\sum\limits_{i=1}^{n}X_{i}\)</span></td>
<td><span class="math inline">\(\bar{x}=\dfrac{1}{n}\sum\limits_{i=1}^{n}x_{i}\)</span></td>
</tr>
<tr class="even">
<td>variance: <span class="math inline">\(\sigma ^{2}\)</span></td>
<td><span class="math inline">\(S^{2}=\dfrac{1}{n-1}\sum\limits_{i=1}^{n}\left( X_{i}-\bar{X}\right) ^{2}\)</span></td>
<td><span class="math inline">\(s^{2}=\dfrac{1}{n-1}\sum\limits_{i=1}^{n}\left( x_{i}-\bar{x}\right) ^{2}\)</span></td>
</tr>
<tr class="odd">
<td>covariance: <span class="math inline">\(\sigma _{XY}\)</span></td>
<td><span class="math inline">\(S_{XY}=\dfrac{1}{n-1}\sum\limits_{i=1}^{n}\left( X_{i}-\bar{X}\right) \left( Y_{i}-\bar{Y}\right)\)</span></td>
<td><span class="math inline">\(s_{XY}=\dfrac{1}{n-1}\sum\limits_{i=1}^{n}\left( x_{i}-\bar{x}\right) \left( y_{i}-\bar{y}\right)\)</span></td>
</tr>
<tr class="even">
<td>correlation: <span class="math inline">\(\rho\)</span></td>
<td><span class="math inline">\(R=\dfrac{S_{XY}}{S_{X}S_{Y}}\)</span></td>
<td><span class="math inline">\(r=\dfrac{s_{XY}}{s_{X}s_{Y}}\)</span></td>
</tr>
<tr class="odd">
<td>proportion: <span class="math inline">\(\pi\)</span></td>
<td><span class="math inline">\(P\)</span></td>
<td><span class="math inline">\(p\)</span></td>
</tr>
</tbody>
</table>
<p>You will recognise all of these statistics from the descriptive statistics section. The estimators (in the middle column) are expressed as functions of random variables (random draws from the population, <span class="math inline">\(X_i\)</span>). The estimates are the actual values you calculate once you have a sample (formulated on the basis of sample values <span class="math inline">\(x_i\)</span>).</p>
<p>In this and the next section we will demonstrate how you can use a sample estimate (i.e.&nbsp;the realisation of a sample mean, <span class="math inline">\(\bar{x}\)</span>) to learn something about an unknown population mean (<span class="math inline">\(\mu\)</span>). In particular you will learn about two commonly used techniques, the hypothesis test (in this section) and the confidence interval (next section). Both inference techniques are only possible if you know what distribution your sample estimator follows. This is why the CLT is so crucial!</p>
</section>
<section id="hypothesis-testing" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">14.2</span> Hypothesis Testing</h2>
<p>Hypothesis testing is a widely used concept. In fact it is a very subtle concept and often applications (or communications of applications) do not pay significant tribute to the subtleness.</p>
<p>We start by reviewing what we were able to do following the introduction of the CLT.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a random variable <span class="math inline">\(M\)</span> which is known to be normally distributed <span class="math inline">\(M \sim N(3,25)\)</span>.</p>
<p>What is the probability that an individual draw of <span class="math inline">\(M\)</span> delivers a value which is smaller than 0?</p>
<p><span class="math inline">\(Pr(M&lt;0) = Pr\left(Z&lt;\frac{0-3}{5}\right) = Pr\left(Z&lt;-0.6\right)=0.2743\)</span></p>
<p>What is the distribution of <span class="math inline">\(\bar{M}\)</span> if <span class="math inline">\(\bar{M}\)</span> is the sample average calculated for a sample of size <span class="math inline">\(n=16\)</span>?</p>
<p><span class="math inline">\(\bar{M} \sim N\left(3,\frac{25}{16}\right)\)</span></p>
<p>Calculate the probability that a particular sample mean (of a sample of size <span class="math inline">\(n=16\)</span>) is smaller than 0.</p>
<p><span class="math inline">\(Pr(\bar{M}&lt;0) = Pr\left(Z&lt;\frac{0-3}{\sqrt{25/16}}\right) = Pr\left(Z&lt;-2.4\right)=0.0082\)</span></p>
</div>
</div>
<p>What you learned from this example is, that, if you know the distribution of the original random variable to be normal and if you know the population parameters, then you can calculate probabilities for certain outcomes of the sample mean random variable, here <span class="math inline">\(\bar{M}\)</span>.</p>
<p>Let’s look at another example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a random variable <span class="math inline">\(R\)</span>. which you know to have expected value <span class="math inline">\(E[R] = 10\)</span> and population variance <span class="math inline">\(Var[R]=16\)</span>. While you do not know how <span class="math inline">\(R\)</span> is distributed, you do have a sample of size <span class="math inline">\(n=100\)</span> which you are confident to be large enough to apply the CLT.</p>
<p>With that information you can derive that</p>
<p><span class="math display">\[\begin{equation*}
    \bar{R} \sim N\left(10,\frac{16}{100}\right)
\end{equation*}\]</span></p>
<p>Calculate the probability that a particular sample mean (of a sample of size <span class="math inline">\(n=100\)</span>) is larger than 11.2?</p>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{R}&gt;11.2) &amp;=&amp; Pr\left(Z&gt;\frac{11.2-10}{\sqrt{16/100}}\right)\\
     &amp;=&amp;Pr\left(Z&gt;\frac{1.2}{0.4}\right)= Pr\left(Z&gt;3.0\right)\\
     &amp;=&amp; 1-  Pr\left(Z \leq 3.0\right)\\
     &amp;=&amp;1- 0.9987=0.0013~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
</div>
<p>Let’s be clear about the interpretation. If we know that the population mean is 10 (and the population variance is 16) then the probability to draw a sample of size <span class="math inline">\(n=100\)</span> with a sample mean (<span class="math inline">\(\bar{R}\)</span>) larger than 11.2 is 0.0013, or 0.13%. So that is rather unlikely. We knew things about the population and calculated a probability about a sample outcome.</p>
<p>Now we turn the table. The reality of an applied researcher is that she has information about a sample but we need to find out something about the population. Here comes the trick in hypothesis testing. Let’s say you do have a sample of size <span class="math inline">\(n=100\)</span> and in that sample the sample mean was <span class="math inline">\(\bar{r}=11.2\)</span> (note now the small <span class="math inline">\(\bar{r}\)</span> as we are now talking about an actual realisation, one particular sample with that sample mean.). As we turned the table (we know sample information but we do not know the population mean <span class="math inline">\(\mu\)</span>) we now hypothesise that the population mean takes a certain value.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lets hypothesise that the sample mean was 10. Do you think that having obtained the actual sample mean of <span class="math inline">\(\bar{r}=11.2\)</span> is consistent with that hypothesised population mean of <span class="math inline">\(\mu=10\)</span>?</p>
<p><select class="webex-select"><option value="blank"></option><option value="">Yes</option><option value="answer">No</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>No, there is only a very small probability of getting a sample with such a mean (or larger) if the population mean indeed was 10, as the probability for that happening was previously calculated to be <span class="math inline">\(Pr(\bar{r} \geq 11.2)=0.0013\)</span>.</p>
</div>
<p>Feedback:</p>
</div>
</div>
<p>So, we conclude that the obtained sample mean of 11.2 is not consistent with the hypothesised population mean of 10, as there is too small a probability to actually obtain such a sample mean (or larger) if the true population mean was actually 10. What we have done here is basically, what we call a hypothesis test. We stated a hypothesis, looked at the evidence in the light of this hypothesis and decided that the evidence is too unlikely to have occurred if the hypothesis was true. The probability we calculated earlier, <span class="math inline">\(Pr(\bar{x} \geq 11.2)=0.0013\)</span>, now takes a very different interpretation: If the population mean was <span class="math inline">\(\mu=10\)</span>, then the probability of obtaining a sample mean (<span class="math inline">\(\bar{r}\)</span>) of 11.2 (or larger) is 0.13%. This is an incredibly important interpretation of the above probability. In fact it has its own name, it is called a <strong>p-value</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Hypothesis testing in “real life”
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here is a “real life” equivalent of the above strategy.</p>
<p>You return home from a long overseas holiday. You are jet-lagged and you sleep on the couch in your darkened flat for a long time. You wake up and just as you wonder whether the sun is shining (you hypothesise that the sun is shining) your flat mate enters the flat with soaking wet clothes (your flatmate is the sample information).</p>
<p>Is the evidence consistent with your hypothesis? No, it isn’t. You judge that it is unlikely that your flatmate entered the flat with wet clothes if the sun was shining. YOu there conclude that your original hypothesis is not correct.</p>
</div>
</div>
<p>There are some wrinkles in the work-out above. For instance we said that we did not know the population mean, and therefore had to hypothesise a value for <span class="math inline">\(\mu\)</span>, but we happily relied on calculations which also did require a known value for the population variance. As it turns out, as we perform a formal hypothesis test, we will have to solve the following issues.</p>
</section>
<section id="hypotheses" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="hypotheses"><span class="header-section-number">14.3</span> Hypotheses</h2>
<p>From the above example it should be obvious that the value which we hypothesised the population mean <span class="math inline">\(\mu\)</span> to be was crucial. Had we changed it, to say 11, the calculation of the p-value would have changed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Following on from the above example, there is a random variable <span class="math inline">\(R\)</span> with a population variance of <span class="math inline">\(Var[R]=16\)</span>. You have a sample (<span class="math inline">\(n=100\)</span>) with sample mean of <span class="math inline">\(\bar{r}=11.2\)</span>. You hypothesis that the population mean is <span class="math inline">\(\mu=11\)</span>. What is the probability of obtaining a sample mean of 11.2 (or larger) if the population mean was <span class="math inline">\(\mu=11\)</span>?</p>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{R}&gt;11.2) &amp;=&amp; Pr\left(Z&gt;\frac{11.2-11}{\sqrt{16/100}}\right)\\
    &amp;=&amp;Pr\left(Z&gt;\frac{0.2}{0.4}\right)= Pr\left(Z&gt;0.5\right)\\
    &amp;=&amp; 1-  Pr\left(Z \leq 0.5\right)\\
    &amp;=&amp;1- 0.6915=0.3085~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
</div>
<p>So clearly, how we set the hypothesis matters. If the population mean was hyothesised to be <span class="math inline">\(\mu=11\)</span> we would have a probability of around 30% of obtaining a sample mean of 11.2 or larger. That is a sizeable probability and we would not easily dismiss the hypothesis. It is apparent from this that the p-value is a property of the combination of the sample and the hypothesised population value.</p>
<p>In fact, when we perform a hypothesis test we need to think about a null and an alternative hypothesis.</p>
</section>
<section id="null-hypotheses" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="null-hypotheses"><span class="header-section-number">14.4</span> Null hypotheses</h2>
<p>A null hypothesis is a claim about the value of some population parameter, for example <span class="math inline">\(\mu =20,\pi=0.45\)</span> or <span class="math inline">\(\sigma ^{2}=1\)</span>. Recall that we have only used the population mean as an example but we could form hypotheses about other population parameters. For now we will stick with the population mean.</p>
<p>A null hypothesis can also be much more general than this, and refer to functions of population parameters. For example, we may obtain a random sample from a population with population mean <span class="math inline">\(\mu_1\)</span> ,and then a random sample from another population with mean <span class="math inline">\(\mu_2\)</span> and ask whether <span class="math inline">\(\mu _{1}=\mu _{2}\)</span> or equivalently <span class="math inline">\(\mu _{1}-\mu _{2}=0\)</span>.</p>
<p>The last example shows the link between the adjective “null” and the numerical value <span class="math inline">\(0\)</span>. The earlier examples can also be rephrased to emphasise this as <span class="math inline">\(\mu -20=0,\pi-0.45=0\)</span> and <span class="math inline">\(\sigma ^{2}-1=0\)</span>.</p>
<p>A null hypothesis expresses the preconception or expectation about the value of the population parameter. There is a standard, compact, notation for this:</p>
<p><span class="math display">\[\begin{equation*}
    H_{0}:\mu =\mu_{0}
\end{equation*}\]</span></p>
<p>expresses the null hypothesis that <span class="math inline">\(\mu =\mu_{0}\)</span> where <span class="math inline">\(\mu_0\)</span> represents a particular value like 20 above.</p>
<p>Deciding whether or not <span class="math inline">\(\mu =\mu _{0}\)</span> on the basis of sample information is usually called testing the hypothesis.</p>
<p>As you saw from the earlier example we may end up in the situation where we wish to dismiss (or formally reject) the null hypothesis. In fact, it turns out that when we perform a hypothesis test we are basically making a binary decision, we either reject, or not reject the null hypothesis.</p>
<p>It is important to note that even if we do not reject a null hypothesis, we are not saying that the null hypothesis is correct or the truth. For instance, in the earlier example, we possibly would not have rejected the null hypothesis that <span class="math inline">\(\mu=11\)</span>. But equally we would have not rejected the null hypothesis that <span class="math inline">\(\mu=11.4\)</span>. There would be many null hypotheses we would not want to reject.</p>
</section>
<section id="alternative-hypotheses" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="alternative-hypotheses"><span class="header-section-number">14.5</span> Alternative hypotheses</h2>
<p>What happens if we reject a null hypothesis, like the above hypothesis that <span class="math inline">\(\mu=10\)</span>? The strategy when performing a hypothesis is to divide the space of possibilities into two areas, the area covered by the null hypothesis and the rest, which we then call the alternative hypothesis. If we reject the null hypothesis we “adopt” the alternative hypothesis. You will see below that the alternative hypothesis is always a range of possible values. It does not point to any specific value. So, in rejecting the null hypothesis, we are not deciding in favour of another specific value of <span class="math inline">\(\mu\)</span>.</p>
<p>There are three different ways in which the alternative hypothesis can be set up (and the null hypothesis will be the complement). These are illustrated in the following image:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Hypotheses.png" class="img-fluid figure-img"></p>
<figcaption>Illustration of hypotheses setup.</figcaption>
</figure>
</div>
<p>You should always think of the null and alternative hypothesis as pairs. The value <span class="math inline">\(\mu_0\)</span> is the value we “hypothesise”.</p>
<p><span class="math display">\[\begin{eqnarray*}
        H_{0}:\mu \geq \mu _{0};    H_{A}:\mu &lt;\mu _{0}\\
        H_{0}:\mu \leq \mu _{0};    H_{A}:\mu &gt;\mu _{0}\\
        H_{0}:\mu = \mu _{0};   H_{A}:\mu \neq \mu _{0}\\
\end{eqnarray*}\]</span></p>
<p>Here, <span class="math inline">\(H_{A}\)</span> stands for the alternative hypothesis. In some textbooks, this is denoted <span class="math inline">\(H_{1}\)</span>, but is still called the alternative hypothesis. Notice that the null and alternative hypotheses are expected to be mutually exclusive: it would make no sense to reject <span class="math inline">\(H_{0}\)</span> if it was also contained in <span class="math inline">\(H_{A}\)</span>.</p>
<p>Note that for the one-sided tests, we sometimes state <span class="math inline">\(H_{0}:\mu = \mu _{0}\)</span> rather than <span class="math inline">\(H_{0}:\mu \geq \mu _{0}\)</span> or <span class="math inline">\(H_{0}:\mu \leq \mu _{0}\)</span>. This makes no substantial difference as we will see later. The alternative hypothesis will always reveal what sort of set-up you are looking at.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Which sort of alternative hypothesis should be chosen? This all depends on context and perspective. Suppose that a random sample of jars of jam coming off a packing line is obtained. The jars are supposed to weigh, on average, 454g. You have to decide, on the basis of the sample evidence, whether or not this is true. So, the null hypothesis here is</p>
<p><span class="math display">\[\begin{equation*}
    H_{0}:\mu =454.
\end{equation*}\]</span>%</p>
<p>What should be the alternative hypothesis?</p>
<div class="webex-solution">
<button>
Hint
</button>
<p>As a jam manufacturer, you may be happy to get away with selling, on average, lighter jars, since this gives more profit, but be unhappy at selling, on average, overweight jars, owing to the loss of profit. So, the manufacturer might choose the alternative hypothesis</p>
<p><span class="math display">\[\begin{equation*}
    H_{A}:\mu &gt;454.
\end{equation*}\]</span>%</p>
<p>A consumer, or a trading standards conscious jam manufacturer, might be more concerned about underweight jars, so the alternative might be</p>
<p><span class="math display">\[\begin{equation*}
    H_{A}:\mu &lt;454.
\end{equation*}\]</span>%</p>
<p>A mechanic from the packing machine company might simply want evidence whether or not the machine is working to specification, and would choose</p>
<p><span class="math display">\[\begin{equation*}
    H_{A}:\mu \neq 454
\end{equation*}\]</span>%</p>
<p>as the alternative.</p>
</div>
</div>
</div>
<p>This short video explains the thinking behind building the null and alternative hypotheses (YouTube, 4min)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/hCKwJBUsum8" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are working for a car manufacturer and you are testing whether the speedometers in your cars are working accurately. On your test track you are driving cars exactly at a speed of 110 km/h. You then take a sample of the speeds which are shown on the cars speedometers.</p>
<p>Which of the following hypotheses should you be testing?</p>
<ul>
<li>A: <span class="math inline">\(H_{0}:\mu \geq 110;   H_{A}:\mu &lt;110\)</span></li>
<li>B: <span class="math inline">\(H_{0}:\mu \leq 110;   H_{A}:\mu &gt;110\)</span></li>
<li>C: <span class="math inline">\(H_{0}:\mu = 110;  H_{A}:\mu \neq 110\)</span></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="answer">A</option><option value="">B</option><option value="">C</option></select></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>A good answer is <span class="math inline">\(H_{0}:\mu \geq 110;   H_{A}:\mu &lt;110\)</span>. You do not want the speed to show lower than it is. That would bring the drivers in your car into trouble with the police.</p>
<p>If your speeds showed too high your customers may actually drive somewhat slower than they think. Everyone wins. Therefore speeds showing too high is not really a concern. Check out this <a href="https://www.startrescue.co.uk/breakdown-cover/motoring-advice/safety-and-security/how-accurate-is-my-speedometer">website</a> which explains why this is by design.</p>
</div>
</div>
</div>
</section>
<section id="types-of-error" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="types-of-error"><span class="header-section-number">14.6</span> Types of Error</h2>
<p>After discussing the set-up of the hypotheses, we are now getting closer to understanding for what sort of p-values you should be rejecting the null hypothesis. As it turns out that is a crucial question and understanding this point will lead you to a very good understanding of what hypothesis testing does.</p>
<p>By setting the null and alternative hypothesis we basically divided all the possibilities for the population parameter into two categories. One called the null hypothesis and the other the alternative hypothesis. When we use a two-tailed (or two-sided) alternative, then the null hypothesis actually only consists of one particular value.</p>
<p>The unknown truth will be in either of the two categories and we will eventually make a decision of either rejecting or not rejecting the null hypothesis. This means there are four possible outcomes as illustrated in the following table.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/HypMatrix.png" class="img-fluid figure-img"></p>
<figcaption>Hypotheses and the Truth.</figcaption>
</figure>
</div>
<p>To explain this, let us return to the example of the jam manufacturer who investigates whether the filling machine works as it should. Let’s say they do worry about jars being filled with less than the advertised 454g, wanting to avoid unfavourable consumer feedback. They therefore design the following hypotheses:</p>
<p><span class="math display">\[\begin{eqnarray*}
    H_0&amp;:&amp;\mu \geq 454\\
    H_A&amp;:&amp;\mu &lt; 454
\end{eqnarray*}\]</span></p>
<p>If in truth, the population parameter is correctly described by the null hypotheses, i.e.&nbsp;the mean filling weight of the machine is 454g or higher, then performing a hypothesis test and coming to the conclusion that <span class="math inline">\(H_0\)</span> should not be rejected would be a correct decision. Equally, if in truth the filling machine had a mean filling weight of less than 454g and the hypothesis test made us conclude that we should reject <span class="math inline">\(H_0\)</span> would again be a correct decision.</p>
<p>However, if in truth the mean filling weight is larger or equal to 454g (<span class="math inline">\(H_0\)</span>) and after looking at a sample and performing a hypothesis test we conclude that we should reject <span class="math inline">\(H_0\)</span> then we would have made a mistake. We call this type of mistake a Type 1 error. And if in truth the average filling weight is below 454g but after performing a hypothesis test using sample information we decide to not reject <span class="math inline">\(H_0\)</span> then we have again made an incorrect decision, a Type 2 error.</p>
<p>Of course, the problem is that we do not know the truth! All we know is what we decided after performing a hypothesis test on the basis of sample information. We have to accept that, when we make a decision then there will be a probability that we are right and another probability that we are wrong.</p>
<p>The objective in designing a procedure to test an <span class="math inline">\(H_{0}\)</span> against an <span class="math inline">\(H_{A}\)</span> - i.e.&nbsp;decide whether to accept <span class="math inline">\(H_{0}\)</span> or to reject <span class="math inline">\(H_{0}\)</span>, is to ensure that a Type 1 error does not occur to often. More precisely, the objective is to design a procedure which fixes the probability of a Type 1 error occurring at a prespecified level, <span class="math inline">\(\alpha\)</span>, which is small and therefore presumably tolerable.</p>
</section>
<section id="p-values" class="level2" data-number="14.7">
<h2 data-number="14.7" class="anchored" data-anchor-id="p-values"><span class="header-section-number">14.7</span> p-values</h2>
<p>At this stage it is worth thinking a little more carefully about p-values.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You measure the weight of the jam (<span class="math inline">\(W\)</span>) in a random sample of 50 jam jars. You obtain a sample mean of <span class="math inline">\(\bar{w}=453.78\)</span>. You know the standard deviation of the filling machine to be 10g and indeed you know that the distribution of the weight coming from the filling machine is a normal distribution.</p>
<p>What is the p-value when testing the following hypotheses?</p>
<p><span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu \geq 454\\
    H_{A}&amp;:&amp;\mu &lt;454
\end{eqnarray*}\]</span></p>
<p>The p-value is the probability to obtain a sample mean of <span class="math inline">\(\bar{w}=453.78\)</span> (or more extreme) if in truth the population mean was 454. There are two elements of implementation we need to explain. First, what does “or more extreme” mean in this context. We are thinking from the alternative hypothesis here. The evidence that would make us reject <span class="math inline">\(H_0\)</span> is very low sample means. So more extreme than the actual sample mean in this example would be sample means even lower than <span class="math inline">\(\bar{w}\)</span>. Second, in order to calculate a p-value we need to fix a hypothesised population mean which comes from the null hypothesis. But <span class="math inline">\(H_0\)</span> is <span class="math inline">\(\mu \geq 454\)</span> which includes a range of potential population means. We shall always fix to the value at the margin, i.e.&nbsp;in this example <span class="math inline">\(\mu = 454\)</span>.</p>
<p>With this in mind we now know that we need to calculate <span class="math inline">\(Pr(\bar{W}&lt;453.78)\)</span>.</p>
<p><span class="math display">\[\begin{equation*}
    Pr(\bar{W}&lt;453.78) = Pr\left(Z&lt;\frac{453.78-454}{\sqrt{100/50}}\right)\\
\end{equation*}\]</span></p>
<p>To calculate the probability we refer to the sampling distribution of <span class="math inline">\(\bar{W}\)</span>. Graphically this is represented by the red area in the following picture:</p>
<p><img src="images/samplingdistribution1.png" class="img-fluid"></p>
<p>We can complete the calculation.</p>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{W}&lt;453.78) &amp;=&amp; Pr\left(Z&lt;\frac{453.78-454}{\sqrt{100/50}}\right)\\
    &amp;=&amp;Pr\left(Z&lt;-\frac{0.22}{1.4142}\right)= Pr\left(Z&lt;-0.1556\right)\\
    &amp;=&amp;0.4364~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
<p>The probability to obtain a sample mean of <span class="math inline">\(\bar{w}=453.78\)</span> (or more extreme, i.e.&nbsp;lower) if in truth the population mean was 454 is 43.65%.</p>
</div>
</div>
<p>In the above example we calculated the p-value to be almost 44%. What do we conclude from here about <span class="math inline">\(H_0\)</span>? Well, we would have to conclude that it is indeed quite likely to have obtained a sample mean of 453.78 or lower if the null hypothesis was true. This means that this sample did not deliver strong evidence against the null hypothesis. And this is indeed how you should think about p-values. The lower the p-value, the less likely it is that you should have obtained the sample you have if the null hypothesis was true.</p>
<p>In order to calculate this p-value we had to assume that the null hypothesis was true (here <span class="math inline">\(\mu=454\)</span>). This is very important to remember as it means that the p-value is not the probability that <span class="math inline">\(H_0\)</span> is true. It would actually be nice if we could calculate that probability of the null hypothesis being true. Unfortunately, just on the basis of the sample information we cannot calculate that probability.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You measure the weight of the jam (<span class="math inline">\(W\)</span>) in a random sample of 40 jam jars. You obtain a sample mean of <span class="math inline">\(\bar{w}=456.12\)</span>. You know the standard deviation of the filling machine to be 10g and indeed you know that the distribution of the weight coming from the filling machine is a normal distribution.</p>
<p>What is the p-value when testing the following hypotheses? <span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu \leq 454\\
    H_{A}&amp;:&amp;\mu &gt; 454
\end{eqnarray*}\]</span></p>
<p>Which of the following pictures best reflects the situation you are confronted with (red areas representing p-values).</p>
<ul>
<li>Picture <strong>A</strong></li>
<li>Picture <strong>B</strong></li>
<li>Picture <strong>C</strong></li>
<li>Picture <strong>D</strong></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">A</option><option value="answer">B</option><option value="">C</option><option value="">D</option></select></p>
<p><img src="images/pvalueexample1.png" class="img-fluid"></p>
<div class="webex-solution">
<button>
Explanation
</button>
<p>The sampling distribution has to be centred around the hypothesised mean of 454 (so C is false). Extreme is defined by the alternative hypothesis which, here is <span class="math inline">\(H_{A}:\mu &gt; 454\)</span>, hence we are looking at a right-tailed test represented by Picture B.</p>
</div>
<p>What is the p-value?</p>
<p><input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.0901&quot;,&quot;.0901&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{W}&gt;456.12) &amp;=&amp; Pr\left(Z&gt;\frac{456.12-454}{\sqrt{100/40}}\right)\\
    &amp;=&amp;Pr\left(Z&gt;\frac{2.12}{1.5811}\right)= Pr\left(Z&gt;1.3418\right)\\
    &amp;=&amp;1 - Pr\left(Z&lt;1.3418\right)\\
    &amp;=&amp;1-0.9099 = 0.0901~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
<p>What is the correct interpretation of the p-value?</p>
<ul>
<li><ol type="A">
<li>The p-value represents the probability that <span class="math inline">\(H_0\)</span> is correct.</li>
</ol></li>
<li><ol start="2" type="A">
<li>The p-value represents the probability that <span class="math inline">\(H_A\)</span> is correct.</li>
</ol></li>
<li><ol start="3" type="A">
<li>The p-value represents the probability that assuming <span class="math inline">\(H_0\)</span> is correct we should obtain a sample (or more extreme) as we did.</li>
</ol></li>
<li><ol start="4" type="A">
<li>The p-value represents the probability that the sample mean is larger than 0.</li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">A</option><option value="">B</option><option value="answer">C</option><option value="">D</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Recall that, to calculate the p-value we need to assume that <span class="math inline">\(H_0\)</span> is correct. It then represents the probability, under that assumption, that we should obtain a sample with a sample mean at least as extreme as the one we observed.</p>
</div>
</div>
</div>
<p>In this example you obtained a p-value of 9%. This means that, if the null hypothesis was true, there is a probability of 9% to get a sample as extreme (meaning as high or higher than the sample mean). What does that mean? Would you now reject the null hypothesis or not? Is this p-value low enough for you to reject <span class="math inline">\(H_0\)</span>? All we can say at this stage is that, if the null hypothesis was true we should expect to see sample as extreme as this around 1 in 10 times.</p>
<p>In the previous two examples we explored how to calculate p-values for one-sided hypothesis tests. In the following example we explore how to calculate p-values for a two-sided alternative. We keep working with the same information as the previous example but change the hypothesis.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You measure the weight of the jam (<span class="math inline">\(W\)</span>) in a random sample of 40 jam jars. You obtain a sample mean of <span class="math inline">\(\bar{w}=456.12\)</span>. You know the standard deviation of the filling machine to be 10g and indeed you know that the distribution of the weight coming from the filling machine is a normal distribution.</p>
<p>What is the p-value when testing the following hypotheses?</p>
<p><span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu = 454\\
    H_{A}&amp;:&amp;\mu \neq 454
\end{eqnarray*}\]</span></p>
<p>Here the alternative is a two sided alternative. Evidence against the null hypothesis would now be collected from sample means which are either sufficiently smaller or larger than the hypothesised population mean (<span class="math inline">\(\mu = 545\)</span>). Recall that the p-value looks for the probability to observe a sample with a sample mean at least as extreme as the one observed. Let’s look at the image which illustrates this situation. The obtained sample mean is <span class="math inline">\(\bar{w}=456.12\)</span> and at least as extreme as that would immediately be associated with values larger or equal than that value (the probability indicated by the red area). But when the alternative is a two-sided one, then we would also consider sample mean values in the left-hand tail as potential evidence against the null hypothesis. We therefore also consider the equivalent probability in the left hand tail (the probability indicated by the orange area) when calculating the p-value.</p>
<p><img src="images/pvalueexample2.png" class="img-fluid"></p>
<p>We therefore have to calculate the following probability to get the p-value of a two-sided test.</p>
<p><span class="math display">\[\begin{eqnarray*}
    \underbrace{Pr(\bar{W}&lt;451.88)}_{orange} &amp;+&amp; \underbrace{Pr(\bar{W}&gt;456.12)}_{red} \\
    &amp;=&amp; Pr\left(Z&lt;\frac{451.88-454}{\sqrt{100/40}}\right)+Pr\left(Z&gt;\frac{456.12-454}{\sqrt{100/40}}\right)\\
    &amp;=&amp;Pr\left(Z&lt;-\frac{2.12}{1.5811}\right)+Pr\left(Z&gt;\frac{2.12}{1.5811}\right)\\
    &amp;=&amp; Pr\left(Z&lt;-1.3418\right)+Pr\left(Z&gt;1.3418\right) \\
    &amp;=&amp; 2 \cdot Pr\left(Z&lt;1.3418\right)~\text{by symmetry of N dist}\\
    &amp;=&amp; 2 \cdot 0.0901 = 0.1802~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
<p>We conclude that the probability of getting a sample outcome as extreme as the one we got, assuming that the null hypothesis is true, is 18%. This is a sizeable probability and we should expect a sample as extreme as the one we had (deviating from the hypothesised population mean as much as our sample) once in every five samples (as the p-value is approximately 20%).</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate p-values for the following examples. In all examples assume that the sampling distribution is a normal distribution.</p>
<p>What is the p-value when testing the following hypotheses?</p>
<p>Random Variable: <span class="math inline">\(X\)</span>: <span class="math inline">\(\sigma_X = 4\)</span> \ Sample: <span class="math inline">\(n=20, \bar{x} = 7.3\)</span></p>
<p><span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu \geq 8\\
    H_{A}&amp;:&amp;\mu &lt; 8
\end{eqnarray*}\]</span></p>
<p><span class="math inline">\(p-value=\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.2177&quot;,&quot;.2177&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{X}&lt;7.3) &amp;=&amp; Pr\left(Z&lt;\frac{7.3-8}{\sqrt{4^2/20}}\right)\\
    &amp;=&amp;Pr\left(Z&lt;-\frac{0.7}{0.8944}\right)=Pr\left(Z&lt;-0.7826\right)\\
    &amp;=&amp;0.2177~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
<p>Random Variable: <span class="math inline">\(Z\)</span>: <span class="math inline">\(\sigma_Z = 6\)</span> \ Sample: <span class="math inline">\(n=40, \bar{x} = 11.9\)</span></p>
<p><span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu \leq 9\\
    H_{A}&amp;:&amp;\mu &gt; 9
\end{eqnarray*}\]</span></p>
<p><span class="math inline">\(p-value=\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.0011&quot;,&quot;.0011&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{Z}&gt;11.9) &amp;=&amp; Pr\left(Z&gt;\frac{11.9-9}{\sqrt{6^2/40}}\right)\\
    &amp;=&amp;Pr\left(Z&gt;\frac{2.9}{0.9487}\right)=Pr\left(Z&gt;3.0569\right)\\
    &amp;=&amp;1-Pr\left(Z&lt;3.0569\right)\\
    &amp;=&amp;1-0.9989 = 0.0011~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
<p>Random Variable: <span class="math inline">\(Q\)</span>: <span class="math inline">\(\sigma_Q = 7\)</span> \ Sample: <span class="math inline">\(n=100, \bar{x} = -0.372\)</span></p>
<p><span class="math display">\[\begin{eqnarray*}
    H_{0}&amp;:&amp;\mu = 1\\
    H_{A}&amp;:&amp;\mu \neq 1
\end{eqnarray*}\]</span></p>
<p><span class="math inline">\(p-value=\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="4" data-answer="[&quot;0.05&quot;,&quot;.05&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{eqnarray*}
    Pr(\bar{Q}&lt;-0.372)+Pr(\bar{Q}&gt;2.372) &amp;=&amp; Pr\left(Z&lt;\frac{-0.372-1}{\sqrt{7^2/100}}\right)+Pr\left(Z&gt;\frac{2.372-1}{\sqrt{7^2/100}}\right)\\
    &amp;=&amp;Pr\left(Z&lt;\frac{-1.372}{0.7}\right)+Pr\left(Z&gt;\frac{1.372}{0.7}\right)\\
    &amp;=&amp;2 \cdot Pr\left(Z&lt;-1.96\right)\\
    &amp;=&amp;2 \cdot 0.025 = 0.05~\text{from the Normal distribution table}
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
<p>So you calculated a range of different p-values. The smaller the p-value the stronger is the evidence from the sample against the null hypothesis.</p>
</section>
<section id="decision-rules" class="level2" data-number="14.8">
<h2 data-number="14.8" class="anchored" data-anchor-id="decision-rules"><span class="header-section-number">14.8</span> Decision Rules</h2>
<p>In the previous section we discussed how to calculate p-values (always assuming you know the population variance and the distribution of the sampling distribution). We discussed that smaller p-values indicate stronger evidence (from the sample) against <span class="math inline">\(H_0\)</span>. In some sense that is all there is to know from the methodology of hypothesis testing. However, hypothesis testing results in a binary decision, either reject or do not reject the null hypothesis. If we want to move from a continuous p-value to a binary decision we need to provide a decision rule.</p>
<p>Let’s consider for a moment you would always reject the null hypothesis if the p-value was smaller than 0.05. What that implies is that if you were to perform 100 tests for which the null hypothesis is correct, then you should expect to reject 5 (5%) of these. So in other words, by setting such a decision rule you are controlling the probability for a Type 1 error.</p>
<p>Example decision rule: <strong>Reject <span class="math inline">\(H_0\)</span> if p-value is smaller than 0.05 (significance level, <span class="math inline">\(\alpha\)</span>).</strong></p>
<p>What about the Type 2 error? A Type 2 error is when we fail to reject an incorrect null hypothesis. It is the situation where we hypothesise that <span class="math inline">\(\mu\)</span> is the population mean but in actual fact the population mean is <span class="math inline">\(\mu + \delta\)</span> where <span class="math inline">\(\delta \neq 0\)</span>. For very small values of <span class="math inline">\(\left|\delta\right|\)</span> it is very unlikely that we reject the incorrect null hypothesis as the difference between the hypothesised population mean and the actual population mean is very small. In other words, the probability of making a Type 2 error is large. The larger the discrepancy (larger <span class="math inline">\(\left|\delta\right|\)</span>), the smaller is the probability that we make a Type 2 error. However, once you set the decision rule like above you have to accept a certain probability for the Type 2 error. It turns out that you could decrease the probability of a Type 1 error, i.e.&nbsp;reject <span class="math inline">\(H_0\)</span> only if the p-value, say, is smaller than <span class="math inline">\(\alpha = 0.01\)</span>, but if you do that, then you will be increasing the probability of a Type 2 error.</p>
<p>For a given sample size you can either control the Type 1 error probability (and that is what we usually do) or the Type 2 error probability but not both. However, increasing the sample size can reduce the probability of a Type 2 error while keeping the Type 1 error probability constant.</p>
<p>In this video we use a simulation to explain how sample size and significance level relate to the probabilities of making Type I or Type II errors (YouTube, 26min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/0HmVqAtU57U" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>You can get the spreadsheet used from <a href="data/Simulatedhypothesistest.xlsx">here</a></p>
<section id="an-alternative-decision-rule-design" class="level3" data-number="14.8.1">
<h3 data-number="14.8.1" class="anchored" data-anchor-id="an-alternative-decision-rule-design"><span class="header-section-number">14.8.1</span> An alternative decision rule design</h3>
<p>As stated above, the decision rule for a hypothesis test can be formulated as follows:</p>
<p><strong>Reject <span class="math inline">\(H_0\)</span> if p-value is smaller than <span class="math inline">\(\alpha\)</span> (the significance level).</strong></p>
<p>The significance level (<span class="math inline">\(\alpha\)</span>) is to be set by the researcher in advance and the calculation of the p-value will depend on the sample evidence and on the hypotheses formulated. As the p-value has a very clear (if somewhat awkward) interpretation (The probability of getting an outcome which is at least as extreme as the sample result <strong>assuming</strong> that the null hypothesis is true), it is very useful to think of decision rules in this manner.</p>
<p>However, you may come across alternative decision rules (which, if formulated correctly) will always give you the same result as using the p-value decision rule. Consider the following situation: You have exactly the same information as we assumed previously, you know your sample size <span class="math inline">\(n\)</span>, you know that the sampling distribution of the sample mean is a normal distribution and you have set a significance level <span class="math inline">\(\alpha\)</span>.</p>
<p>With this information we can return to a previous example and ask a slightly different question.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a random variable <span class="math inline">\(R\)</span>, which you <strong>hypothesise</strong> to have expected value <span class="math inline">\(E[R]=\mu = 10\)</span> and you want to test this against the alternative that the population mean is larger than that:</p>
<p><span class="math display">\[\begin{equation*}
    H_{0}:\mu \leq 10;  H_{A}:\mu &gt;10
\end{equation*}\]</span></p>
<p>Further, you know that the population variance is <span class="math inline">\(Var[R]=\sigma^2=16\)</span>. While you do not know how <span class="math inline">\(R\)</span> is distributed, you do have a sample of size <span class="math inline">\(n=100\)</span> which you are confident to be large enough to apply the CLT.</p>
<p>With that information and assuming that <span class="math inline">\(\mu=10\)</span>, you can derive the sampling distribution:</p>
<p><span class="math display">\[\begin{eqnarray*}
    \bar{R} &amp;\sim&amp; N\left(\mu,\sigma^2_{\bar{R}}=\frac{\sigma^2}{n}\right)\\
    &amp;\sim&amp; N\left(10,\frac{16}{100}\right)
\end{eqnarray*}\]</span></p>
<p>or in standardised form</p>
<p><span class="math display">\[\begin{equation*}
    \frac{\bar{R}-\mu}{\sigma_{\bar{R}}} \sim N\left(0,1\right)
\end{equation*}\]</span></p>
<p>Before looking at the actual sample mean, what type of sample evidence would make you reject <span class="math inline">\(H_0\)</span> if you set the significance level at <span class="math inline">\(\alpha=0.05\)</span>? In other words, we want to find a value <span class="math inline">\(\bar{r}^{high}\)</span> which will trigger a rejection of the null hypothesis. This should happen if <span class="math inline">\(Pr(\bar{R}&gt;\bar{r}^{high}|\mu=10)&lt;\alpha=0.05\)</span>, where the conditioning on the assumption that <span class="math inline">\(\mu=10\)</span> is made explicit.</p>
<p><span class="math display">\[\begin{equation*}
    Pr\left(\bar{R}&gt;\bar{r}^{high}|\mu=10\right) = Pr\left(Z&gt;\frac{\bar{r}^{high}-10}{\sqrt{\frac{16}{100}}}|\mu=10\right)=0.05
\end{equation*}\]</span></p>
<p>For ease of notation we will not show the conditioning (<span class="math inline">\(|\mu=10\)</span>) any longer, but you should always keep in mind that we are only able to make these calculations as we are setting <span class="math inline">\(\mu\)</span> to the hypothesised value.</p>
<p>We reformulated the problem stated in terms of the random variable <span class="math inline">\(\bar{R}\)</span> into one formulated in terms of the standard normally distributed random variable <span class="math inline">\(Z\)</span>. The reason for doing so is that we can tell from a standard normal distribution table that <span class="math inline">\(Pr(Z&gt;1.645)=1-Pr(Z\leq1.645)=1-0.95 = 0.05\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pvalztable1.png" class="img-fluid figure-img"></p>
<figcaption>Extract from the standard normal distribution table, identifying that <span class="math inline">\(Pr(Z&gt;1.645)=1-Pr(Z\leq1.645)=1-0.95 = 0.05\)</span>. The required <span class="math inline">\(Z\)</span> value is somewhere between 1.64 and 1.65. We average to 1.645.</figcaption>
</figure>
</div>
<p>From here we can infer that</p>
<p><span class="math display">\[\begin{eqnarray*}
    \frac{\bar{r}^{high}-10}{\sqrt{\frac{16}{100}}} &amp;=&amp; 1.645\\
    \bar{r}^{high}-10&amp;=&amp;1.645 \cdot \sqrt{\frac{16}{100}}=1.645 \cdot 0.4\\
    \bar{r}^{high}&amp;=&amp;10+1.645 \cdot 0.4=10.658
\end{eqnarray*}\]</span></p>
<p>Therefore, <strong>if the sample mean turns out to be higher than 10.658, we shall reject <span class="math inline">\(H_{0}:\mu \leq 10\)</span> at a 5% significance level</strong>. This can be seen as a decision rule.</p>
</div>
</div>
<p>This video applies the same thinking as that in the above example (YouTube, 10min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/heFliHemfVA" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>We have used all the knowledge we accumulated previously to design a decision rule prior to actually observing the sample mean. We needed knowledge of the test statistic (the sample mean here) its sampling distribution, the sample size (<span class="math inline">\(n\)</span>) and the significance level (<span class="math inline">\(\alpha\)</span>).</p>
<p>With all that knowledge we were able to derive the following decision rule.</p>
<ul>
<li>For testing <span class="math inline">\(H_{0}:\mu \leq 10;   H_{A}:\mu &gt;10\)</span> the decision rule is<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the sample mean exceeds 10.658.</strong><br>
Which is equivalent to saying:<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the test statistic <span class="math inline">\(Z=\frac{\bar{r}-10}{\sqrt{\frac{16}{100}}}\)</span> exceeds 1.645.</strong></li>
</ul>
<p>It most common to see these decision rules formulated in terms of the <span class="math inline">\(Z\)</span> statistic rather than the sample mean. The values at which we would reject <span class="math inline">\(H_0\)</span> are also called <strong>critical values</strong>.</p>
<p>Graphically we can represent the situation as follows:</p>
<p><img src="images/pvalueexamplerighttail.png" class="img-fluid"></p>
<p>If we had wanted to to test a left-tailed hypothesis, the decision rule would have been</p>
<ul>
<li>For testing <span class="math inline">\(H_{0}:\mu \geq 10;   H_{A}:\mu &lt;10\)</span> the decision rule is<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the sample mean is smaller than 9.342 (=10-0.658).</strong><br>
Which is equivalent to saying<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the test statistic <span class="math inline">\(Z=\frac{\bar{r}-10}{\sqrt{\frac{16}{100}}}\)</span> is smaller than -1.645.</strong></li>
</ul>
<p>And the graphical representation is as follows</p>
<p><img src="images/pvalueexamplelefttail.png" class="img-fluid"></p>
<p>Lastly we have to establish how this type of decision rule would look if we were to test a two-sided hypothesis. Let is first state the hypothesis and the resulting decision rule in our example and then explain it graphically.</p>
<ul>
<li>For testing <span class="math inline">\(H_{0}:\mu = 10;  H_{A}:\mu \neq 10\)</span> the decision rule is<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the sample mean exceeds 10.784 or is smaller than 9.216.</strong><br>
Which is equivalent to saying<br>
<strong>Reject <span class="math inline">\(H_0\)</span>, at a significance level <span class="math inline">\(\alpha = 0.05\)</span>, if the test statistic <span class="math inline">\(Z=\frac{\bar{r}-10}{\sqrt{\frac{16}{100}}}\)</span> exceeds 1.96 or is smaller than -1.96.</strong></li>
</ul>
<p><img src="images/pvalueexampletwotail.png" class="img-fluid"></p>
<p>The 5% probability (<span class="math inline">\(\alpha\)</span>) is now divided into two 2.5% regions in each tail (red areas). So where do the <span class="math inline">\(Z\)</span> values of -1.96 and 1.96 come from? They do come from the standard normal distribution table as the values which cut off 0.025 in the left and right tail respectively.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pvalztable2.png" class="img-fluid figure-img"></p>
<figcaption>Extract from the standard normal distribution table, identifying that <span class="math inline">\(Pr(Z&gt;1.96)=1-Pr(Z\leq1.96)=1-0.975 = 0.025\)</span>. Also <span class="math inline">\(Pr(Z&lt;-1.96)= 0.025\)</span>.</figcaption>
</figure>
</div>
<p>In this video we show how the application of different decision rules all lead to the same decision in a hypothesis test (YouTube, 15min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/vl8QxJmhDUA" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Looking back at the previous calculations it should be obvious that the decision rules could be calculated/formulated before you observe the sample value. The decision rule was dependent on</p>
<ul>
<li>the hypothesised population value <span class="math inline">\(\mu\)</span>,</li>
<li>the sample size <span class="math inline">\(n\)</span>,</li>
<li>the sampling distribution, and</li>
<li>the chosen significance level.</li>
</ul>
<p>Once you have formulated the decision rule you merely need to observe the sample mean and calculate <span class="math inline">\(Z=\frac{\bar{r}-10}{0.4}\)</span>. Once you have done that you can easily see whether your calculated <span class="math inline">\(Z\)</span> value falls in the rejection region or not.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why do we need Hypothesis tests?
</div>
</div>
<div class="callout-body-container callout-body">
<p>After the previous discussion you may wonder why the discipline has developed the tradition of hypothesis testing. And in some sense you are right in that going from the continous p-value to the binary decision entails a loss of information.</p>
<p>One explanation is that it has been used as a decision tool. This means that the information coming from the hypothesis test has been used to decide whether a certain course of action should be followed or not.</p>
<p>Indeed, if the information from the hypothesis test is the only information used to decide on a course of action, then using a formal hypothesis testing framework (which means presenting a significance level <span class="math inline">\(\alpha\)</span>, a pair of hypothesis and a resulting decision rule) will force you to consider the probabilities of committing a Type 1 and 2 error. The probability of making a Type 1 error is explicitly encoded as <span class="math inline">\(Pr(\)</span>Type 1 error<span class="math inline">\()=\alpha\)</span>. The probability of the Type 2 error is not explicit, but the applied researcher will be aware that its probability is inversely related to the probability of a Type 1 error.</p>
</div>
</div>
<p>In the following exercises we ask you to formulate decision rules.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>In all examples assume that the sampling distribution is a normal distribution.</p>
<p>Formulate decision rules.</p>
<p>Random Variable: <span class="math inline">\(X\)</span>: <span class="math inline">\(\sigma_X = 4\)</span><br>
Sample: <span class="math inline">\(n=20\)</span><br>
Hypothesis: <span class="math inline">\(H_{0}:\mu \leq 25; H_{A}:\mu &gt; 25\)</span><br>
Significance level: <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>The three possible decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <span class="math inline">\(&lt; 0.05\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(Z\)</span> is <span class="math inline">\(&gt;\)</span> <span class="math inline">\(1.645\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{x}\)</span> is <select class="webex-select"><option value="blank"></option><option value="">&lt;</option><option value="">=</option><option value="answer">&gt;</option></select> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;26.4713&quot;]">.</li>
</ul>
<p>If the sample mean is 26.8. What is your decision?</p>
<p><select class="webex-select"><option value="blank"></option><option value="answer">Reject H0</option><option value="">Do not reject H0</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The critical value is calculated as <span class="math inline">\(25+1.645*(4/\sqrt{20})\)</span>. As the sample mean is larger than that critical value we reject <span class="math inline">\(H_0\)</span>.</p>
</div>
<p>Random Variable: <span class="math inline">\(Y\)</span>: <span class="math inline">\(\sigma_Y = 6\)</span><br>
Sample: <span class="math inline">\(n=40\)</span><br>
Hypothesis: $ H_{0}:; H_{A}:&lt; 0$<br>
Significance level: <span class="math inline">\(\alpha = 0.10\)</span></p>
<p>The three possible decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.1&quot;,&quot;.1&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(Z\)</span> is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;-1.28&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{y}\)</span> is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;-1.2143&quot;]">.</li>
</ul>
<p>If the sample mean is -0.8. What is your decision?</p>
<p><select class="webex-select"><option value="blank"></option><option value="">Reject H0</option><option value="answer">Do not reject H0</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The critical value is calculated as <span class="math inline">\(0-1.28*(6/\sqrt{40})\)</span>. As the sample mean is not smaller than this critical value we do not reject <span class="math inline">\(H_0\)</span>.</p>
</div>
<p>Random Variable: <span class="math inline">\(Q\)</span>: <span class="math inline">\(\sigma_Q = 7\)</span><br>
Sample: <span class="math inline">\(n=100\)</span><br>
Hypothesis: $ H_{0}:= 12; H_{A}: $<br>
Significance level: <span class="math inline">\(\alpha = 0.01\)</span></p>
<p>The three possible decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.1&quot;,&quot;.1&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(Z\)</span> is <span class="math inline">\(&lt;\)</span> <input class="webex-solveme nospaces" size="6" data-answer="[&quot;-2.575&quot;]"> or <span class="math inline">\(&gt;\)</span> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;2.575&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{q}\)</span> is <span class="math inline">\(&lt;\)</span> <input class="webex-solveme nospaces" size="7" data-answer="[&quot;10.1975&quot;]"> or <span class="math inline">\(&gt;\)</span> <input class="webex-solveme nospaces" size="7" data-answer="[&quot;13.8025&quot;]">.</li>
</ul>
<p>If the sample mean is 13.5. What is your decision?</p>
<p><select class="webex-select"><option value="blank"></option><option value="">Reject H0</option><option value="answer">Do not reject H0</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>We get the Z value by looking at the normal table to see which value cuts of (0.01/2) of the probability in each tail. That is <span class="math inline">\(\pm 2.575\)</span>. The critical values are calculated as <span class="math inline">\(12 \pm 2.575*(7/\sqrt{100})\)</span>.</p>
</div>
</div>
</div>
<p>As you can see from the prior examples, the sample size plays a crucial role in the calculation of the critical values in a hypothesis test. By increasing the sample size, you can actually decrease the probability of making a Type 2 error (not rejecting an incorrect <span class="math inline">\(H_0\)</span>). The mechanism at work is that the standard error of your sample statistic (here mainly the sample mean but it could be any other sample statistic) is an inverse function to the sample size <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[\begin{equation*}
    \sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}}  
\end{equation*}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>In an earlier example we worked with the following information:</p>
<p>Random Variable: <span class="math inline">\(Q\)</span>: <span class="math inline">\(\sigma_Q = 7\)</span><br>
Sample: <span class="math inline">\(n=100\)</span><br>
Hypothesis: <span class="math inline">\(H_{0}:\mu = 12;    H_{A}:\mu \neq 12\)</span><br>
Significance level: <span class="math inline">\(\alpha = 0.01\)</span></p>
<p>The resulting decision rule was:</p>
<p>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{q}\)</span> is <span class="math inline">\(&lt;\)</span> <span class="math inline">\(10.1975\)</span> or <span class="math inline">\(&gt;13.8025\)</span>.</p>
<p>How large would the sample size have to be such that a sample mean of 13.5 will trigger a rejection of <span class="math inline">\(H_0\)</span>?</p>
<p>The critical value, in this example is calculated according to</p>
<p><span class="math display">\[\begin{equation*}
    13.8025=12+2.575 \cdot (7/\sqrt{100})
\end{equation*}\]</span></p>
<p>We now wonder what should be the <span class="math inline">\(n\)</span> in</p>
<p><span class="math display">\[\begin{equation*}
    13.5=12+2.575 \cdot (7/\sqrt{n})
\end{equation*}\]</span></p>
<p>All we need to do is to solve the above equation for <span class="math inline">\(n\)</span></p>
<p><span class="math display">\[\begin{eqnarray*}
    13.5&amp;=&amp;12+2.575 \cdot (7/\sqrt{n})\\
    13.5-12&amp;=&amp;2.575 \cdot (7/\sqrt{n})\\
    \sqrt{n}&amp;=&amp;\frac{2.575 \cdot 7}{1.5}= 12.0167\\
    n&amp;=&amp;12.0167^2=144.4003
\end{eqnarray*}\]</span></p>
<p>This means that the sample size required is 144.4003, or in practice 145.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following knowledge</p>
<p>Random Variable: <span class="math inline">\(X\)</span>: <span class="math inline">\(\sigma_X = 4\)</span><br>
Hypothesis: <span class="math inline">\(H_{0}:\mu \leq 25; H_{A}:\mu &gt; 25\)</span><br>
Significance level: <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>How large a sample would you need to make sure that you can reject the null hypothesis (at <span class="math inline">\(\alpha=0.05\)</span>) if the sample mean is 0.01 larger than the hypothesised population mean?</p>
<p><input class="webex-solveme nospaces" size="4" data-answer="[&quot;4327&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Use the following argument:</p>
<p><span class="math display">\[\begin{eqnarray*}
    25.1&amp;=&amp;25+1.645 \cdot (4/\sqrt{n})\\
    25.1-25&amp;=&amp;1.645 \cdot (4/\sqrt{n})\\
    \sqrt{n}&amp;=&amp;\frac{1.645 \cdot 4}{0.1}= 65.8\\
    n&amp;=&amp;65.8^2=4,326.64
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
</section>
</section>
<section id="different-sampling-distributions-for-the-sample-mean" class="level2" data-number="14.9">
<h2 data-number="14.9" class="anchored" data-anchor-id="different-sampling-distributions-for-the-sample-mean"><span class="header-section-number">14.9</span> Different Sampling Distributions for the sample mean</h2>
<p>So far we only dealt with the situation in which the sampling distribution was a normal distribution;</p>
<p><span class="math display">\[\begin{equation*}
    \bar{X} \sim N(\mu,\sigma_{\bar{X}})
\end{equation*}\]</span></p>
<p>There are two situations in which we established that the sampling distribution of the sample mean is a normal distribution.</p>
<ol type="1">
<li>The population distribution is a normal distribution itself and we know the population variance, <span class="math inline">\(\sigma_X\)</span>, <span class="math inline">\(X \sim N(?,\sigma)\)</span>. The population is unknown (if it was known there was no need for hypothesis testing of the mean). In this situation <span class="math inline">\(\bar{X} \sim N(\mu,\sigma_{\bar{X}})\)</span> at any sample size.</li>
<li>We know the population variance, <span class="math inline">\(\sigma_X\)</span> but don’t know the distribution the population random variable <span class="math inline">\(X\)</span> follows, but the sample size is sufficiently large for <span class="math inline">\(\bar{X}\)</span> to be normally distributed (by the power of the Central Limit Theorem).</li>
</ol>
<p>It is worth repeating the main conclusion of the CLT here:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The Central Limit Theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">\(\bar{X}\)</span> is obtained from a random sample of size <span class="math inline">\(n\)</span> from a population with mean $$ and variance <span class="math inline">\(\sigma ^{2}\)</span>, then, irrespective of the distribution sampled,</p>
<p><span class="math display">\[\begin{equation*}
        \dfrac{\bar{X}-\mu }{SE\left[ \bar{X}\right] }=\dfrac{\bar{X}-\mu}{ \sigma /\sqrt{n} }=\dfrac{\bar{X}-\mu}{\sigma_{\bar{X} }}\rightarrow N\left( 0,1\right) \;\;\;\text{as }n\rightarrow \infty .
\end{equation*}\]</span></p>
<p>That is, the probability distribution of <span class="math inline">\(\dfrac{\bar{X}-\mu }{SE\left[ \bar{X}\right] }\)</span> approaches the standard normal distribution as $n$.</p>
</div>
</div>
<p>So, both of the earlier results rely on us “knowing” the standard deviation <span class="math inline">\(\sigma\)</span> of the random variable <span class="math inline">\(X\)</span>. This is the reason why, throughout this section, when we presented examples we always gave you information on this standard deviation. This created somewhat awkward situations where we said that the population mean <span class="math inline">\(\mu\)</span> was not known but the population standard deviation <span class="math inline">\(\sigma\)</span> was known. That is, of course, a situation which often is unrealistic.</p>
<p>We therefore need to consider the case where <span class="math inline">\(\sigma\)</span> is also unknown. When that is the case (almost always!) then we will replace the unknown <span class="math inline">\(\sigma\)</span> with a sample estimate <span class="math inline">\(s\)</span>, which we learned how to calculate earlier. This means that we will be operating with the following term</p>
<p><span class="math display">\[\begin{equation*}
    t= \dfrac{\bar{X}-\mu }{S /\sqrt{n}  }
\end{equation*}\]</span></p>
<p>This term is commonly called a <span class="math inline">\(t-\)</span>statistic for reasons that will soon become obvious. Fortunately, all the principles discussed previously continue to apply when we do so. Here we will point out what details will change.</p>
<p>In what follows we will discuss four realistic cases (all of which assume that <span class="math inline">\(\sigma\)</span> is unknown and is estimated by <span class="math inline">\(s\)</span>). For each of these four cases we will want to establish how <span class="math inline">\(t\)</span> is distributed. The complication that arises is that the <span class="math inline">\(t\)</span> statistic, now, incorporates two random variables, <span class="math inline">\(\bar{X}\)</span> the sample mean and <span class="math inline">\(S\)</span> the sample standard deviation (which is why it is written as a capitalised letter in the above t-statistic). This makes deriving the distribution of <span class="math inline">\(t\)</span> less straightforward.</p>
<p>If the result is that <span class="math inline">\(t \sim N(0,1)\)</span> then all the details discussed previously will apply, in particular how you can calculate p-values or critical values and therefore make decisions on hypotheses. If the answer is anything else but <span class="math inline">\(t \sim N(0,1)\)</span> we will have to discuss the changed procedures. The following table outlines the four cases (<strong>all assuming that <span class="math inline">\(\sigma\)</span> needs to be estimated with <span class="math inline">\(s\)</span></strong>):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Sample Size (<span class="math inline">\(n\)</span>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dist of <span class="math inline">\(X\)</span></td>
<td>small</td>
<td>large</td>
</tr>
<tr class="even">
<td>Normal</td>
<td><span class="math inline">\(t \sim ?\)</span></td>
<td><span class="math inline">\(t \sim ?\)</span></td>
</tr>
<tr class="odd">
<td>not Normal</td>
<td><span class="math inline">\(t \sim ?\)</span></td>
<td><span class="math inline">\(t \sim ?\)</span></td>
</tr>
</tbody>
</table>
<p>We shall briefly discuss these four cases in turn.</p>
<ul>
<li><span class="math inline">\(X\sim N\)</span>, <span class="math inline">\(n\)</span> small. In this case <span class="math inline">\(t \sim t-distribution\)</span> with <span class="math inline">\(n-1\)</span> degrees of freedom (<span class="math inline">\(t_{n-1}\)</span>). (You will soon learn about this distribution).</li>
<li><span class="math inline">\(X\sim N\)</span>, <span class="math inline">\(n\)</span> large. In this case <span class="math inline">\(t \sim t-distribution\)</span> with <span class="math inline">\(n-1\)</span> degrees of freedom (<span class="math inline">\(t_{n-1}\)</span>) but you will soon learn that for large <span class="math inline">\(n\)</span> this implies <span class="math inline">\(t \sim N(0,1)\)</span>.</li>
<li><span class="math inline">\(X\sim not~N\)</span>, <span class="math inline">\(n\)</span> small. In this case <span class="math inline">\(t \sim ?\)</span>. In other words we cannot specify the type of distribution, as it is hugely data dependent. If you wanted to make inference in such a case you will have to apply data-driven methods which are beyond the scope of this course unit (like bootstrapping).</li>
<li><span class="math inline">\(X\sim not~N\)</span>, <span class="math inline">\(n\)</span> large. In this case <span class="math inline">\(t \sim N(0,1)\)</span>. This is thanks to (another) CLT (one which allows for unknown <span class="math inline">\(\sigma\)</span>).</li>
</ul>
<p>We can therefore complete the above table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Sample Size (<span class="math inline">\(n\)</span>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dist of <span class="math inline">\(X\)</span></td>
<td>small</td>
<td>large</td>
</tr>
<tr class="even">
<td>Normal</td>
<td><span class="math inline">\(t \sim t_{n-1}\)</span></td>
<td><span class="math inline">\(t \sim N(0,1)\)</span></td>
</tr>
<tr class="odd">
<td>not Normal</td>
<td><span class="math inline">\(t \sim ?\)</span></td>
<td><span class="math inline">\(t \sim N(0,1)\)</span></td>
</tr>
</tbody>
</table>
<p>This implies that, whenever we have a large sample size the procedures detailed earlier apply exactly, just with the sample standard deviation, <span class="math inline">\(s\)</span>, replacing the role of the known <span class="math inline">\(\sigma\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why a t-Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Details of why the <span class="math inline">\(t\)</span> statistic follows a <span class="math inline">\(t\)</span> distribution are not for this course unit. But it is worth noting that a <span class="math inline">\(t\)</span> distribution arises when you combine a normally distributed random variable, <span class="math inline">\(\bar{X}\)</span>, with a <span class="math inline">\(\chi^2\)</span> distributed random variable, <span class="math inline">\(S^2\)</span>. Details are not important other than to realise that <span class="math inline">\(t\)</span> combines two random variables. You will soon encounter the <span class="math inline">\(\chi^2\)</span> distribution in another context, which follows from a different combination of multiple random variables.</p>
</div>
</div>
<p>Let us work through an example that represents a situation where we are confident that the CLT applies. As discussed previously, an often quoted “rule-of-thumb” is that <span class="math inline">\(n&gt;30\)</span> generally allows you to make this judgement. I would certainly say that with <span class="math inline">\(n&gt;100\)</span> you are pretty much on the safe site unless you have extremely skewed distributions. If you have any doubt, you should just state your doubt.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have the following information:<br>
Random Variable: <span class="math inline">\(X\)</span> distribution unknown, note that <span class="math inline">\(\sigma\)</span> is unknown<br>
Sample: <span class="math inline">\(n=80\)</span>, <span class="math inline">\(s = 4\)</span>, assume that CLT applies<br>
Hypothesis: <span class="math inline">\(H_{0}:\mu \leq 25; H_{A}:\mu &gt; 25\)</span><br>
Significance level: <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>With that information we should be able to formulate decision rules. We will do that in three versions, in terms of the <span class="math inline">\(p\)</span>-vale, the test statistic (here a <span class="math inline">\(t\)</span>-test) and the sample statistic (here <span class="math inline">\(\bar{x}\)</span>). In applications one is sufficient as they all give the same result.</p>
<p>The three equivalent decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <span class="math inline">\(&lt; 0.05\)</span>.<br>
This is merely the statement of the general p-value decision rule using the chosen significance level.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t\)</span> is <span class="math inline">\(&gt;\)</span> <span class="math inline">\(1.645\)</span>.<br>
The value from 1.645 comes from the normal distribution table as in this situation <span class="math inline">\(t \sim N(0,1)\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{x}\)</span> is <span class="math inline">\(&gt;\)</span> <span class="math inline">\(25.7357\)</span>.<br>
The critical value is calculated as <span class="math inline">\(25+1.645*(4/\sqrt{80})\)</span>.</li>
</ul>
<p>Note that we could formulate these decision rules before we know the value of the sample mean. In fact the first two rules can be formulated without knowing anything about the sample other than the sample size, <span class="math inline">\(n\)</span>. For the third we also needed to know the sample standard deviation, <span class="math inline">\(s\)</span>.</p>
<p>If the actual sample mean was 26.12, what would be your decision?</p>
<p>From here it is easiest to apply the last decision rule. We would reject <span class="math inline">\(H_0\)</span> as <span class="math inline">\(26.12&gt;25.7357\)</span>. We could also calculate the <span class="math inline">\(t\)</span>-statistic:</p>
<p><span class="math display">\[\begin{equation*}
    t= \dfrac{\bar{x}-\mu }{s /\sqrt{n}  } = \dfrac{26.12-25 }{4 /\sqrt{80}  } = 2.5044
\end{equation*}\]</span></p>
<p>According to the 2nd decision rule we would also reject. And on the basis of this <span class="math inline">\(t\)</span>-statistics we could also calculate the p-value, which is 0.0062 (which we get from the Normal distribution). This is smaller than the significance level of 0.05 and leads us (as it should) to the same rejection decision.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>For both examples you can assume that the sample size is large enough for a CLT to be applicable.</p>
<p>Random Variable: <span class="math inline">\(Y\)</span> is normally distributed<br>
Sample: <span class="math inline">\(n=40, s = 6\)</span><br>
Hypothesis: $ H_{0}:; H_{A}:&lt; 0$<br>
Significance level: <span class="math inline">\(\alpha = 0.10\)</span></p>
<p>The three possible decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.1&quot;,&quot;.1&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(Z\)</span> is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;-1.28&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{y}\)</span> is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;-1.5606&quot;]">.</li>
</ul>
<p>If the sample mean is -0.8. What is your decision?</p>
<p><select class="webex-select"><option value="blank"></option><option value="">Reject H0</option><option value="answer">Do not reject H0</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The critical value is calculated as <span class="math inline">\(0-1.28*(6/\sqrt{40})\)</span>. The value from 1.28 comes from the normal distribution table as in this situation <span class="math inline">\(t \sim N(0,1)\)</span>.</p>
</div>
<p>Random Variable: <span class="math inline">\(Q\)</span> distribution is unknown<br>
Sample: <span class="math inline">\(n=100, s = 7\)</span><br>
Hypothesis: $ H_{0}:= 12; H_{A}: $<br>
Significance level: <span class="math inline">\(\alpha = 0.01\)</span></p>
<p>The three possible decision rules are:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <select class="webex-select"><option value="blank"></option><option value="answer">&lt;</option><option value="">=</option><option value="">&gt;</option></select> <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.01&quot;,&quot;.01&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|Z|\)</span> is <select class="webex-select"><option value="blank"></option><option value="">&lt;</option><option value="">=</option><option value="answer">&gt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;2.575&quot;]">.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{y}\)</span> is <span class="math inline">\(&lt;\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;10.1975&quot;]"> or <span class="math inline">\(&gt;\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;13.8025&quot;]">.</li>
</ul>
<p>If the sample mean is 13.5. What is your decision?</p>
<p><select class="webex-select"><option value="blank"></option><option value="">Reject H0</option><option value="answer">Do not reject H0</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>We get the Z value by looking at the normal table to see which value cuts of (<span class="math inline">\(0.01/2=0.005\)</span>) of the probability in each tail (we half the significance level as this is a two-tailed test). That is <span class="math inline">\(\pm 2.575\)</span>. The critical value is calculated as <span class="math inline">\(12 \pm 2.575*(7/\sqrt{100})\)</span>. The value from 2.575 comes from the normal distribution table as in this situation, with a large sample size, <span class="math inline">\(t \sim N(0,1)\)</span>.</p>
</div>
</div>
</div>
<section id="working-with-the-t-distribution" class="level3" data-number="14.9.1">
<h3 data-number="14.9.1" class="anchored" data-anchor-id="working-with-the-t-distribution"><span class="header-section-number">14.9.1</span> Working with the t-distribution</h3>
<p>This now leaves us to discuss how to work the case where we know that the random variable from which we sample is normally distributed, the population standard deviation is unknown and the sample size is small (such that we are not confident that the CLT applies). In the above table it was indicated that, in such a situation,</p>
<p><span class="math display">\[\begin{equation*}
    t= \dfrac{\bar{X}-\mu }{S /\sqrt{n}  }\sim t_{n-1}
\end{equation*}\]</span></p>
<p>We will have to work with a new statistical table. The Table for the t-distribution. You can get one version from <a href="data/tTable.pdf">here</a>.</p>
<p>Let’s say we want to perform a hypothesis test in such a setting. Let’s work through an example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>We have the following information:</p>
<p>Random Variable: <span class="math inline">\(X\)</span> distribution is normal with <span class="math inline">\(\sigma\)</span> unknown<br>
Sample: <span class="math inline">\(n=20\)</span>, <span class="math inline">\(s = 4\)</span><br>
Hypothesis: <span class="math inline">\(H_{0}:\mu \leq 25; H_{A}:\mu &gt; 25\)</span><br>
Significance level: <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>With that information we should be able to formulate decision rules. We will do that in three versions, in terms of the <span class="math inline">\(p\)</span>-vale, the test statistic (here a <span class="math inline">\(t\)</span>-test) and the sample statistic (here <span class="math inline">\(\bar{x}\)</span>). In applications one is sufficient as they all give the same result.</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if p-value is <span class="math inline">\(&lt; 0.05\)</span>.<br>
This is merely the statement of the general p-value decision rule using the chosen significance level.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t\)</span> is <span class="math inline">\(&gt;\)</span> <span class="math inline">\(1.729\)</span>.<br>
The value from 1.725 comes from the <span class="math inline">\(t\)</span> distribution with 19 (<span class="math inline">\(=n-1=20-1\)</span>) degrees of freedom as, in this situation, we know that <span class="math inline">\(t \sim t_{n-1}\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(\bar{x}\)</span> is <span class="math inline">\(&gt;\)</span> <span class="math inline">\(26.5465\)</span>.<br>
The critical value is calculated as <span class="math inline">\(25+1.729*(4/\sqrt{20})\)</span>.</li>
</ul>
<div class="webex-solution">
<button>
How can we get that critical t-value?
</button>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tTableuse1.png" class="img-fluid figure-img"></p>
<figcaption>Illustration of how to read a critical value from the t-Table.</figcaption>
</figure>
</div>
</div>
<p>If the actual sample mean was 26.12, what would be your decision? From here it is easiest to apply the last decision rule. We would not reject <span class="math inline">\(H_0\)</span> as <span class="math inline">\(26.12&lt;26.5465\)</span>. We could also calculate the <span class="math inline">\(t\)</span>-statistic:</p>
<p><span class="math display">\[\begin{equation*}
    t= \frac{\bar{x}-\mu }{s /\sqrt{n}  } = \frac{26.12-25 }{4 /\sqrt{20}  } = \frac{1.12}{0.8944}= 1.2522
\end{equation*}\]</span></p>
<p>According to the 2nd decision rule we would also not reject as the <span class="math inline">\(t\)</span>-statistic does not exceed its critical value of 1.729. And on the basis of this <span class="math inline">\(t\)</span>-statistics we could also calculate the p-value. From the <span class="math inline">\(t\)</span>-distribution table we know that the critical value for a one sided <span class="math inline">\(t\)</span> test at <span class="math inline">\(\alpha=0.1\)</span> and 19 degrees of freedom (dof) is 1.328. As the <span class="math inline">\(t\)</span>-statistic is 1.2522, we can say that the p-value has to be larger than 0.10. We cannot give any more precise p-value using the table. You can use Excel to give you a more precise p-value. Use the formula “=1-T.DIST(1.2522,19,TRUE)” which delivers the precise p-value of 0.1128. In any case, as our significance level is 0.05 we fail to reject the null hypothesis. As it should be, all decision rules give the same result.</p>
</div>
</div>
<p>This is a work through a t-test with a two-tailed <span class="math inline">\(H_A\)</span> (YouTube, 23min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/IOvzVIzWgdU" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>The University’s welfare manager is concerned about students spending too much on unhealthy food items every week (let <span class="math inline">\(U\)</span> be the weekly spend on unhealthy food measured in pounds). He asks a random sample of <span class="math inline">\(n=\)</span> 20 students to keep a weekly food shopping diary. From previous studies the manager is confident that <span class="math inline">\(U\)</span> is normally distributed. Five years ago the average spend (<span class="math inline">\(\mu\)</span>) was 61 pounds and she is concerned that this value has increased since.</p>
<p>From the sample the welfare manager learns that <span class="math inline">\(\bar{u} = 79\)</span> and the sample standard deviation is <span class="math inline">\(s=10\)</span>. Test the following hypotheses, using <span class="math inline">\(\alpha = 0.05\)</span>:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 61\)</span><br>
<span class="math inline">\(H_A: \mu &gt; 61\)</span></li>
</ul>
<p>What is the distribution of the test-statistic <span class="math inline">\(t = \frac{\bar{U}-\mu}{s/\sqrt{n}}\)</span>?</p>
<ul>
<li><ol type="A">
<li><span class="math inline">\(N(0,1)\)</span></li>
</ol></li>
<li><ol start="2" type="A">
<li><span class="math inline">\(N(0,n)\)</span></li>
</ol></li>
<li><ol start="3" type="A">
<li><span class="math inline">\(t_{10}\)</span></li>
</ol></li>
<li><ol start="4" type="A">
<li><span class="math inline">\(t_{20}\)</span></li>
</ol></li>
<li><ol start="5" type="A">
<li><span class="math inline">\(t_{19}\)</span></li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">(A)</option><option value="">(B)</option><option value="">(C)</option><option value="">(D)</option><option value="answer">(E)</option></select></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>As we can assume that <span class="math inline">\(U\)</span> is normally distributed but we need to use the sample variance to approximate the variance, this test statistic is t-distributed with <span class="math inline">\(n-1\)</span> degrees of freedom.</p>
</div>
<p>Decision Rule:</p>
<p>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t\)</span> <select class="webex-select"><option value="blank"></option><option value="">&lt;</option><option value="">=</option><option value="answer">&gt;</option></select> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;1.729&quot;]"></p>
<p>What is the value of the test-statistic?</p>
<p><span class="math inline">\(t =\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;8.0498&quot;]"></p>
<p>What is the value of the test’s p-value?</p>
<p><span class="math inline">\(p-value &lt;\)</span> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;5e-04&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>You get the critical value exactly as in the above example from t-distribution table with 19 degrees of freedom and from the column with 0.95.</p>
<p><span class="math inline">\(t=\frac{\bar{U}-\mu}{s/\sqrt{n}}=\frac{79-61}{10/\sqrt{20}}=8.0498\)</span></p>
<p>To get the p-value we only look at the values in the <span class="math inline">\(k=19\)</span> row. And then we place the obtained sample t-statistic amongst the values we can see there. The most extreme value here is 3.883 associated with the prob that <span class="math inline">\(Pr(t\leq 3.883)=0.9995\)</span>. If our t-stat was 3.883 then the p-value would have been 0.0005. However, our test stat is even further in the tail of the distribution and therefore we know that the p-value is <span class="math inline">\(&lt;0.0005\)</span>. We cannot be more precise using the table.</p>
</div>
<p>What is the most accurate conclusion?</p>
<ul>
<li><ol type="A">
<li>There is evidence that students spend more on unhealthy foods than 5 years ago.</li>
</ol></li>
<li><ol start="2" type="A">
<li>There is insufficient to suggest that students spend more on unhealthy foods than 5 years ago.</li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="answer">(A)</option><option value="">(B)</option></select></p>
<p>After presenting these results to a colleague working in the economics department she recognises that she has to redo the test acknowledging that in general food prices were affected by inflation over the last five years. In fact food prices increased by 20% over that period.</p>
<p>What should change in the test’s setup to acknowledge that food prices increased?</p>
<ul>
<li><ol type="A">
<li>The significance level should be increased.</li>
</ol></li>
<li><ol start="2" type="A">
<li>The significance level should be decreased.</li>
</ol></li>
<li><ol start="3" type="A">
<li>The sample size should be increased by 20%.</li>
</ol></li>
<li><ol start="4" type="A">
<li>The population mean in the hypotheses should change to <span class="math inline">\(\mu = 73.2\)</span>.</li>
</ol></li>
<li><ol start="5" type="A">
<li>The population mean in the hypotheses should change to <span class="math inline">\(\mu = 50.84\)</span>.</li>
</ol></li>
<li><ol start="6" type="A">
<li>The test should be changed to a left tailed test.</li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">(A)</option><option value="">(B)</option><option value="">(C)</option><option value="answer">(D)</option><option value="">(E)</option><option value="">(F)</option></select></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Today the equivalent of 61 pounds five years ago is <span class="math inline">\(61 \cdot 1.2\)</span>.</p>
</div>
<p>What is the most accurate conclusion after re-doing the test with the appropriate adjustment?</p>
<ul>
<li><ol type="A">
<li>There is insufficient evidence to suggest that students spend more on unhealthy foods than 5 years ago.</li>
</ol></li>
<li><ol start="2" type="A">
<li>There is evidence that students spend more on unhealthy foods than 5 years ago.</li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">(A)</option><option value="answer">(B)</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>After changing the hypotheses to <span class="math inline">\(H_0: \mu = 73.2\)</span> and <span class="math inline">\(H_A: \mu &gt; 73.2\)</span> you should obtain a <span class="math inline">\(t-\)</span>statistic of 2.5938. This delivers a p-value smaller than 0.01 and larger than 0.005. Therefore we still reject the null hypothesis and conclude that students spend more on unhealthy food than five years ago.</p>
</div>
</div>
</div>
</section>
<section id="intermediate-summary" class="level3" data-number="14.9.2">
<h3 data-number="14.9.2" class="anchored" data-anchor-id="intermediate-summary"><span class="header-section-number">14.9.2</span> Intermediate Summary</h3>
<p>The sections above introduced the concept of hypothesis testing. It used your knowledge of sampling distribution to allow you to make (probabilistic statements) about unknown population characteristics, based on just one sample. The example used here is that where we are interested in an unknown population mean.</p>
<p>In this video I walk through two examples and l explain in detail how you decide what distribution the test statistic follows (assuming the null hypothesis is true) (YouTube, 35min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/CayhsIJCyMs" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>The video uses <a href="data/HT_for_mean_Overview_YT.pdf">this scheme</a> which can help you in deciding which distribution to use in your hypothesis test.</p>
</section>
</section>
<section id="other-hypothesis-tests" class="level2" data-number="14.10">
<h2 data-number="14.10" class="anchored" data-anchor-id="other-hypothesis-tests"><span class="header-section-number">14.10</span> Other hypothesis tests</h2>
<p>In everything we discussed before we assumed that we were testing a hypothesis about an unknown population mean. We used that example to explain the principle of hypothesis testing. However, there are many different population parameters you may wish to test hypotheses about. You may wish to test hypotheses about the type of population distribution, about the population variance or about population correlations between two random variables. Later you will learn how we test hypothesis about regression coefficients. Here we will introduce you to three more hypothesis tests. Testing of a population proportion, testing for the equality of two population means and testing for independence of two categorical random variables.</p>
<p>This is a short intro to the common elements of hypothesis testing you should recognise as we introduce the next three hypothesis tests (YouTube, 2min)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/vxgGUmzrUlI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<section id="testing-for-a-population-proportion" class="level3" data-number="14.10.1">
<h3 data-number="14.10.1" class="anchored" data-anchor-id="testing-for-a-population-proportion"><span class="header-section-number">14.10.1</span> Testing for a population proportion</h3>
<p>Proportions often describe features of a population we are very interested in. Here are some examples</p>
<ul>
<li>The proportion of local Manchester trains running on time.</li>
<li>The proportion of students reading the course material.</li>
<li>The proportion of students who replace studying with asking ChatGPT.</li>
<li>The proportion of restaurant customers who are vegan.</li>
<li>The proportion of adults likely to vote.</li>
<li>The proportion of employees wishing to work from home.</li>
<li>The proportion of visitors to a website that have a university degree.</li>
</ul>
<p>You can see that many interesting characteristics of a population can be expressed as a proportion and a university, a teacher, a business, a political party, a government and any other institution may well be interested in estimating such a proportion in a population. We call such a population proportion <span class="math inline">\(p\)</span>. Usually that population proportion <span class="math inline">\(p\)</span> is unknown and we have to rely on survey (sample) evidence. There is a host of companies which have made a business out of providing such evidence (e.g.&nbsp;<a href="https://yougov.co.uk/">YouGov</a>, <a href="https://www.pewresearch.org/">Pew Research Center</a> and <a href="https://nielseniq.com/global/en/">GFK</a>.</p>
<p>In the section on descriptive statistics you learned that proportions can be thought about as a mean of a binary variable. The example used was a small sample of survey respondents who were asked whether they have a University degree.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Respondent</th>
<th>Uni Degree</th>
<th>u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Yes</td>
<td>1</td>
</tr>
<tr class="even">
<td>6</td>
<td>No</td>
<td>0</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Yes</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>In this sample 4 out of 7 indicated that they had a university degree. That is a percentage of 57.14%. But you could also calculate the sample mean of a variable <span class="math inline">\(U\)</span> that takes the value of 1 if a respondent has a university degree and 0 if they have not:</p>
<p><span class="math display">\[\begin{equation*}
    \bar{u}=\frac{1}{7}\sum_{i=1}^{7} u_{i}=\frac{1}{7} \cdot 4 = \frac{4}{7} = 0.5714
\end{equation*}\]</span></p>
<p>This is the sample mean of the variable <span class="math inline">\(U\)</span>. When thinking of proportions we will often call this the estimated sample proportion <span class="math inline">\(\hat{p}\)</span>. When you understand that a sample proportion <span class="math inline">\(\hat{p}\)</span> can be thought of as a mean, then it will not be surprising that much of the details of a hypothesis test for a population proportion are similar to tests of a population mean. Recall that a sample mean <span class="math inline">\(\bar{x}\)</span> was a realisation of a random variable <span class="math inline">\(\bar{X}\)</span>. Now, a particular sample proportion <span class="math inline">\(\hat{p}\)</span> is a realisation of a random variable <span class="math inline">\(\hat{P}\)</span>.</p>
<p>In the case of testing for the population mean, at the core of the testing procedure was the knowledge of the sampling distribution of <span class="math inline">\(\bar{X}\)</span>. In the case of testing for a population proportion we need to know what the sampling distribution of <span class="math inline">\(\hat{P}\)</span> is. Without any further detail we state here that (again using the power of a CLT) the sampling distribution of the <span class="math inline">\(\hat{P}\)</span> is:</p>
<p><span class="math display">\[\begin{equation*}
    \hat{P} \sim N(p,\sigma^2_{\hat{P}}).
\end{equation*}\]</span></p>
<p>As this result is due to a CLT this is a large sample result. You need to know how to calculate the variance of the sample proportion:</p>
<p><span class="math display">\[\begin{equation*}
    \sigma^2_{\hat{P}} = \frac{p(1-p)}{n}.
\end{equation*}\]</span></p>
<p>The variance of the sample proportion is a function of the underlying population proportion. When we perform a hypothesis test we will assume a certain value for <span class="math inline">\(p\)</span>, say <span class="math inline">\(p_0\)</span>. We will therefore use that value in the calculation of the test statistic. Recall that all calculations of a hypothesis test are undertaken under the assumption that the null hypothesis is correct. Therefore we shall use the following test statistic</p>
<p><span class="math display">\[\begin{equation*}
    Z= \frac{\hat{p}-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}} \sim N(0,1)
\end{equation*}\]</span></p>
<p>Let’s work through an example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A university is interested in the proportion of students who think that they receive a good learning experience. A random sample of 1,021 students is asked whether they agree or not agree with the statement that they have received a good learning experience. Of those 841 agreed with the statement and 180 disagreed.</p>
<p>The University’s target is to have 85% of its students feel that they have a good learning experience and they therefore wish to test the following hypothesis (with an <span class="math inline">\(\alpha = 0.01\)</span>):</p>
<p><span class="math display">\[\begin{equation*}
    H_0: p \geq 0.85;~H_A:p &lt; 0.85
\end{equation*}\]</span></p>
<p>This allows us to calculate <span class="math inline">\(\sigma^2_{\hat{P}}=\frac{0.85 \cdot (1-0.85)}{1021} = 0.0001249\)</span> and therefore <span class="math inline">\(\sigma_{\hat{P}}=\sqrt{\sigma^2_{\hat{P}}}= \sqrt{0.0001249}=0.0112\)</span>.</p>
<p>Note, if you calculate the variance you will often get very small numbers. If you want to achieve 4dp precision for <span class="math inline">\(s_{\hat{P}}\)</span> you will have to keep more digits than 4 for <span class="math inline">\(s^2_{\hat{P}}\)</span>. If you rounded <span class="math inline">\(s^2_{\hat{P}}\)</span> to 0.0001 and then taken the square root you would have gotten 0.0100.</p>
<p>The decision rule is that <span class="math inline">\(H_0\)</span> should be rejected if the p-value is smaller than 0.01.</p>
<p>The sample proportion is <span class="math inline">\(\hat{p}=\frac{841}{1021} = 0.8237\)</span>.</p>
<p>This now allows us to calculate the test statistic:</p>
<p><span class="math display">\[\begin{equation*}
    Z= \frac{0.8237-0.85}{0.0112} = \frac{-0.0263}{0.0112} = -2.3482
\end{equation*}\]</span></p>
<p>With this value we can go to the standard normal table and identify that <span class="math inline">\(Pr(Z &lt; -2.35) = 0.0094\)</span> and therefore the p-value is 0.0094, which is smaller than 0.01 and hence we decide to reject <span class="math inline">\(H_0\)</span>.</p>
<p><img src="images/NormalTableExtract3.png" class="img-fluid"></p>
<p>The University, on this instance, would have to concede that they have not reached their target.</p>
</div>
</div>
<p>Hopefully you realise that the process of hypothesis testing for a proportion is very similar to testing a population mean. All you need to know is how to estimate <span class="math inline">\(\sigma^2_{\hat{P}}\)</span>. That in combination with the knowledge that (for large samples) the test statistic is normally distributed delivers all the information you need.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are producer of iPhone covers. You have just that the latest colour trend is to use a Tangerine Disco colour schemes (well that was trendy in the 2026 version, trends will have totally changed if you read this any later). You are sceptical and before investing into new designs you decide to ask a random sample of your customers whether they would be interested to buy such a phone cover for their next phone.</p>
<p>You decide that it will be worth investing into this new trend if more than 20% of your customers indicate that they would indeed consider buying such a phone cover.</p>
<p>What should be your set of hypotheses to test?</p>
<ul>
<li><ol type="A">
<li><span class="math inline">\(H_0: p = 0.2;~H_A:p \neq 0.2\)</span></li>
</ol></li>
<li><ol start="2" type="A">
<li><span class="math inline">\(H_0: p \leq 0.2;~H_A:p &gt; 0.2\)</span></li>
</ol></li>
<li><ol start="3" type="A">
<li><span class="math inline">\(H_0: p \geq 0.2;~H_A:p &lt; 0.2\)</span></li>
</ol></li>
<li><ol start="4" type="A">
<li><span class="math inline">\(H_0: p \leq 0.19;~H_A:p &gt; 0.19\)</span></li>
</ol></li>
<li><ol start="5" type="A">
<li><span class="math inline">\(H_0: p \geq 0.21;~H_A:p &lt; 0.21\)</span></li>
</ol></li>
</ul>
<p><select class="webex-select"><option value="blank"></option><option value="">A.</option><option value="answer">B.</option><option value="">C.</option><option value="">D.</option><option value="">E.</option></select></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math inline">\(H_0: p \leq 0.2;~H_A:p &gt; 0.2\)</span> is the right hypothesis. You want to be confident that there are more than 20% of customers interested. So you stick that into the alternative hypothesis and only reject <span class="math inline">\(H_0\)</span> (no investment) if there is sufficient evidence that it should be rejected.</p>
</div>
<p>In a sample of 367 randomly selected customers you find 92 customers that are interested in a 70s colour scheme phone cover.</p>
<p>What is the sample proportion?</p>
<p><span class="math inline">\(\hat{p} =\)</span> <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2507&quot;,&quot;.2507&quot;]"></p>
<p>What is the test statistic?</p>
<p><span class="math inline">\(z =\)</span> <input class="webex-solveme nospaces" data-tol="1e-04" size="6" data-answer="[&quot;2.4282&quot;]"></p>
<p>What is the p-value?</p>
<p>$p-value = $ <input class="webex-solveme nospaces" data-tol="0.001" size="6" data-answer="[&quot;0.0075&quot;,&quot;.0075&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>The sample proportion is: <span class="math inline">\(\hat{p} = \frac{92}{367}=0.2507\)</span><br>
The test stat is: <span class="math inline">\(Z = \frac{\hat{p}-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}} = \frac{0.2507-0.2}{\sqrt{\frac{0.2 (1-0.2)}{367}}} = \frac{0.0507}{0.02088} = 2.4282\)</span><br>
And the p-value is: <span class="math inline">\(p-value = 0.0075\)</span> which comes from the standard normal table or from EXCEL.</p>
</div>
<p>At what level of significance would you reject <span class="math inline">\(H_0\)</span>? (multiple correct answers are possible)</p>
<ul>
<li><span class="math inline">\(\alpha = 0.2\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">Reject H0</option><option value="">Do not reject H0</option></select></li>
<li><span class="math inline">\(\alpha = 0.1\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">Reject H0</option><option value="">Do not reject H0</option></select></li>
<li><span class="math inline">\(\alpha = 0.05\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">Reject H0</option><option value="">Do not reject H0</option></select></li>
<li><span class="math inline">\(\alpha = 0.01\)</span> <select class="webex-select"><option value="blank"></option><option value="answer">Reject H0</option><option value="">Do not reject H0</option></select></li>
<li><span class="math inline">\(\alpha = 0.001\)</span> <select class="webex-select"><option value="blank"></option><option value="">Reject H0</option><option value="answer">Do not reject H0</option></select></li>
</ul>
</div>
</div>
</section>
<section id="testing-for-the-equality-of-means" class="level3" data-number="14.10.2">
<h3 data-number="14.10.2" class="anchored" data-anchor-id="testing-for-the-equality-of-means"><span class="header-section-number">14.10.2</span> Testing for the equality of means</h3>
<p>Let us continue thinking about you as the potential producer of iPhone covers. In the previous section you have discovered that there is potentially enough interest from your customers to purchase new phone covers in a 70s colour scheme. In that same survey where you asked that question, you also asked whether customers may be interested in purchasing new phone covers in “walnut retro” (rated on place seven in the 2026 version of <a href="https://www.vistaprint.com/hub/color-trends">this listing of trendy colour schemes</a>. For that you equally had fairly strong interest. However, you only want to pay designers for one of these two schemes. It is your suspicion that there is no difference in the price you could charge for such a phone cover. However, your marketing department decides to run a survey in which they ask customers how much they would be willing to pay for the respective premium phone cover.</p>
<p>The marketing team actually send out two different questionnaires such that you get the sample information on your customers’ willingness to pay from two different samples.</p>
<p>Here is the information you get (<span class="math inline">\(\bar{w}\)</span> represents the average willingness to pay in the respective sample):</p>
Sample “tangerine disco”:
Sample “walnut retro”:
<p>Let <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span> be the respective values for the unknown population willingness to pay. How would you use this information to test whether your suspicion that the willingness to pay is identical is correct?</p>
<p>If you look up any Business or Economics Statistics textbook you are likely to find a chapter on “Comparing two population means”. From there you will find the information that the test statistic for testing <span class="math inline">\(H_0: \mu_2 - \mu_1 = 0; ~H_A: \mu_2 - \mu_1 \neq 0\)</span> is</p>
<p><span class="math display">\[\begin{equation*}
    t = \frac{(\bar{w}_2-\bar{w}_1)-(\mu_2 - \mu_1)}{\sqrt{\frac{s^2_p}{n_1}+\frac{s^2_p}{n_2}}}
\end{equation*}\]</span></p>
<p>where <span class="math inline">\(s^2_p\)</span> is a pooled estimate of the variance</p>
<p><span class="math display">\[\begin{equation*}
    s^2_p = \frac{(n_1 - 1)s^2_1+(n_2-1)s^2_2}{n_1+n_2-2}
\end{equation*}\]</span></p>
<p>This follows a t-distribution with <span class="math inline">\(n_1+n_2-2\)</span> degrees of freedom if</p>
<ol type="1">
<li>the two samples are independent</li>
<li>the two populations are normally distributed</li>
<li>the two population variances are identical (although unknown), which is why we estimate one pooled variance from the two samples</li>
</ol>
<p>Following our earlier discussion it is clear that these are quite restrictive assumptions, in particular that on the population normality and the equality of population variance. In our example above there is no a-priori reason to think that this should be the case.</p>
<p>As it turns out, the appropriate testing procedure, if any of these assumptions are breached, is the subject of substantial debate in the community of statisticians (For a good summary read the introduction and conclusion of Nguyen, D.T. et al.&nbsp;(2016) “Parametric Tests for Two Population Means under Normal and Non-Normal Distributions,” Journal of Modern Applied Statistical Methods: Vol. 15 : Issue 1 , Article 9. DOI: 10.22237/jmasm/1462075680).</p>
<p>In the case of unequal variances and/or non-normal distributions, the test statistic is the Satterthwaite t-test for the equality of means:</p>
<p><span class="math display">\[\begin{equation*}
    t = \frac{(\bar{w}_2-\bar{w}_1)-(\mu_2 - \mu_1)}{\sqrt{\frac{s^2_1}{n_1}+\frac{s^2_2}{n_2}}}
\end{equation*}\]</span></p>
<p>This is almost the same as the earlier one with the difference being that we do not first calculate a pooled variance estimate, but just use the variance estimates of the two samples (<span class="math inline">\(s^1_1\)</span> and <span class="math inline">\(s^2_2\)</span>) directly. There is also an adjusting (downwards) of the degrees of freedom in the t-distribution used to calculate the p-value. For instance, in the above example the degrees of freedom, if the assumptions were met, would be <span class="math inline">\(n_1+n_2-2= 187+132-2=317\)</span>. For the Satterthwaite t-test the degrees of freedom are adjusted downwards. The downwards adjustment is more severe if the sample variances are very unequal (no details of the Satterthwaite adjustment are needed).</p>
<p>As we know that for large degrees of freedom the t-distribution converges to the <span class="math inline">\(N(0,1)\)</span> distribution, the correction in the degrees of freedom will only matter if the corrected degrees of freedom make a substantial difference in the distribution. A very conservative correction would be to use the smaller of <span class="math inline">\(n_1-1\)</span> and <span class="math inline">\(n_2-1\)</span> as the degrees of freedom instead. In this case this would be <span class="math inline">\(132-1 = 131\)</span> degrees of freedom. Even with these degrees of freedom the t-distribution is still well approximated by the <span class="math inline">\(N(0,1)\)</span> distribution. You can see in the table below that 120 is the largest degrees of freedom reported. If the degrees of freedom are larger than that we approximate the t-distribution with the <span class="math inline">\(N(0,1)\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tTableExtract2.png" class="img-fluid figure-img"></p>
<figcaption>Extract from the t-distribution table, illustrating that for degrees of freedom larger than 120 the t-distribution is well approximated by the standard normal distribution.</figcaption>
</figure>
</div>
<p>This means that we can continue our example without having to assume population normality and equal variances. Let us calculate the test-statistic;</p>
<p><span class="math display">\[\begin{eqnarray*}
    t &amp;=&amp; \frac{(\bar{w}_2-\bar{w}_1)-(\mu_2 - \mu_1)}{\sqrt{\frac{s^2_1}{n_1}+\frac{s^2_2}{n_2}}} \\
     &amp;=&amp;\frac{(12.01-11.54)-0}{\sqrt{\frac{1.23^2}{187}+\frac{0.94^2}{132}}}\\
     &amp;=&amp;\frac{0.47}{0.1216} = 3.8651
\end{eqnarray*}\]</span></p>
<p>What is the resulting p-value? We go to the t-distribution table and see that 3.8651 is to the right of 3.297 (using <span class="math inline">\(N(0,1)\)</span>). That means that the tail probability <span class="math inline">\(Pr(t&gt;3.8651)\)</span> has to be smaller than 0.0005 (which is the tail probability for 3.297). As we are performing a two-tailed test we have to double that tail probability to get the p-value. We therefore know that the p-value is smaller than <span class="math inline">\(0.001~(=2 \cdot 0.0005)\)</span>. This implies that there is very little support from the data for <span class="math inline">\(H_0: \mu_2 - \mu_1 = 0\)</span>. We would reject the null hypothesis that there is equal willingness to pay for the “tangerine disco” and the “walnut retro” themed phone covers at significance levels as low as 0.001. The data suggest that the company could charge more for “walnut retro” themed phone covers.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Testing for equality of means in EXCEL
</div>
</div>
<div class="callout-body-container callout-body">
<p>In Excel’s data analysis tool-pack you can chose three different options for testing for the equality of means, as shown in the image.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Excel two sample mean choice.png" class="img-fluid figure-img"></p>
<figcaption>Choice of two sample mean tests in EXCEL.</figcaption>
</figure>
</div>
<p>The option “Two-Sample Assuming Equal Variances” will apply the t-test using the pooled variance estimator and using <span class="math inline">\(n_1+n_2-2\)</span> degrees of freedom. The option “Two-Sample Assuming Unequal Variances” does calculate the Satterthwaite t-test with adjusted degrees of freedom.</p>
<p>The “Paired Two Sample for Means” is a test we did not discuss here. This is the version you want to use when you get two observations from each subject, e.g.&nbsp;the same person tells you what they are willing to pay for phone cases in the two different colour schemes.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>You obtain the following two sets of sample information:</p>
<p>Sample A: * $n_A = 58 $ * ${x}_A = 4.85 $ * <span class="math inline">\(s_A = 0.69\)</span></p>
<p>Sample B: * $n_B = 46 $ * ${x}_B = 5.15 $ * <span class="math inline">\(s_B =  0.54\)</span></p>
<p>You wish to test the following hypotheses: <span class="math inline">\(H_0: \mu_B - \mu_A = 0; ~H_A: \mu_B - \mu_A &gt; 0\)</span>.</p>
<p>Calculate the test statistic:</p>
<p><span class="math inline">\(t=\)</span> <input class="webex-solveme nospaces" size="6" data-answer="[&quot;2.4872&quot;]"></p>
<p>If you were very concerned about unequal population variances and non-normal population distributions, what would be the degrees of freedom you would use?</p>
<p>adjusted d.o.f = <input class="webex-solveme nospaces" size="2" data-answer="[&quot;45&quot;]"></p>
<p>What is the test statistic’s p-value in this scenario?</p>
<p><input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.001&quot;,&quot;.001&quot;]"> <span class="math inline">\(&lt; p-value &lt;\)</span> <input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.005&quot;,&quot;.005&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p><span class="math display">\[\begin{equation*}
    t = \frac{(5.15-4.85)-0}{\sqrt{\frac{0.69^2}{58}+\frac{0.54^2}{46}}} = 2.4872
\end{equation*}\]</span></p>
<p>d.o.f.: The smaller of (58-1) and (46-1), hence 45.</p>
<p>p-value: <span class="math inline">\(0.005&lt;p-value&lt;0.01\)</span> (use the closest degrees of freedom available, here 40. The test statistic is between 2.423 and 2.704, which have tail probabilities 0.001 and 0.005. hence the p-value is between these two values.)</p>
</div>
<p>If you were confident that the population distributions were normally distributed and had equal population variances, what would be the degrees of freedom you would use?</p>
<p>d.o.f = <input class="webex-solveme nospaces" size="3" data-answer="[&quot;102&quot;]"></p>
<p>What is the test statistics p-value in this scenario?</p>
<p><input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.005&quot;,&quot;.005&quot;]"> <span class="math inline">\(&lt; p-value &lt;\)</span> <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.01&quot;,&quot;.01&quot;]"></p>
<div class="webex-solution">
<button>
Solution
</button>
<p>d.o.b: <span class="math inline">\(n_A+n_B + 2 = 102\)</span>.</p>
<p>p-value: <span class="math inline">\(0.005&lt;p-value&lt;0.01\)</span> (use the closest degrees of freedom available, here 90. The test statistic is between 2.368 and 2.632, which have tail probabilities 0.001 and 0.005. hence the p-value is between these two values.)</p>
</div>
</div>
</div>
</section>
<section id="testing-for-independence-of-two-categorical-random-variables" class="level3" data-number="14.10.3">
<h3 data-number="14.10.3" class="anchored" data-anchor-id="testing-for-independence-of-two-categorical-random-variables"><span class="header-section-number">14.10.3</span> Testing for independence of two categorical random variables</h3>
<p><a href="data/titanic.xlsx">Here</a> you can find a spreadsheet with information on (a subset of) the Passengers on the ill-fated 1912 voyage on the Titanic. This is an image of the first few entries on that spreadsheet.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Titanic_spreadsheet.png" class="img-fluid figure-img"></p>
<figcaption>An snapshot of the titanic.xlsx spreadsheet.</figcaption>
</figure>
</div>
<p>Two of the pieces of information we have on each passenger is which class they were booked in and whether they survived (1=yes, 0=no). Both of these are categorical variables and a good way to display that information is in a contingency table.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Obs (<span class="math inline">\(O_{ij}\)</span>)</th>
<th>Class</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived</td>
<td>1st</td>
<td>2nd</td>
<td>3rd</td>
<td>Total</td>
</tr>
<tr class="even">
<td>No = 0</td>
<td>129</td>
<td>161</td>
<td>573</td>
<td>863</td>
</tr>
<tr class="odd">
<td>Yes = 1</td>
<td>193</td>
<td>119</td>
<td>138</td>
<td>450</td>
</tr>
<tr class="even">
<td>Total</td>
<td>322</td>
<td>280</td>
<td>711</td>
<td>1313</td>
</tr>
</tbody>
</table>
<p>The next table shows the joint probabilities.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Obs: <span class="math inline">\(\Pr(C \cap S )\)</span></th>
<th>Class (<span class="math inline">\(C\)</span>)</th>
<th>~</th>
<th>~</th>
<th>~</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived <span class="math inline">\(S\)</span></td>
<td>1st</td>
<td>2nd</td>
<td>3rd</td>
<td>Marginal</td>
</tr>
<tr class="even">
<td>No =0</td>
<td>0.0982</td>
<td>0.1226</td>
<td>0.4364</td>
<td>0.6573</td>
</tr>
<tr class="odd">
<td>Yes = 1</td>
<td>0.1470</td>
<td>0.0906</td>
<td>0.1051</td>
<td>0.3427</td>
</tr>
<tr class="even">
<td>Marginal</td>
<td>0.2452</td>
<td>0.2133</td>
<td>0.5415</td>
<td>1.0000</td>
</tr>
</tbody>
</table>
<p>Recall that we see, in the center of the table, joint probabilities and <span class="math inline">\(\Pr((C=c) \cap (S=s) )\)</span>, and in the margins of the table we see the marginal probabilities (<span class="math inline">\(\Pr(S=s)\)</span> and <span class="math inline">\(\Pr(C=c)\)</span>).</p>
<p>We may now ask the question whether the two variables Passenger Class (<span class="math inline">\(C\)</span>) and Survival (<span class="math inline">\(S\)</span>) are dependent or independent. In other words, did your probability of survival depend on which class you were booked on. We will investigate this question with a hypothesis test. Let us spell out the hypotheses we would use in such a context.</p>
<p><span class="math display">\[\begin{eqnarray*}
    H_0&amp;:&amp; C ~ and ~ S ~ are~ independent\\
    H_A&amp;:&amp; C ~ and ~ S ~ are ~ dependent
\end{eqnarray*}\]</span></p>
<p>To continue with that question we, as usual when performing hypothesis tests, assume that the null hypothesis is true. If the null hypothesis was true, the two random variables are independent, then we should be able to reconstruct the joint probabilities from the marginal probabilities.</p>
<p><span class="math display">\[\begin{equation}
    \Pr((C=c) \cap (S=s) ) = \Pr(C=c) \cdot \Pr(S=s)
\end{equation}\]</span></p>
<p>This equation is only correct if <span class="math inline">\(S\)</span> and <span class="math inline">\(C\)</span> are independent. In general $ ((C=c) (S=s) ) = (C=c) (S=s|C=c) $ which comes from Bayes Theorem. We now reconstruct all the joint probabilities assuming independence. For instance</p>
<p><span class="math display">\[\begin{equation}
    \Pr((C=2nd) \cap (S=1) ) = \Pr(C=2nd) \cdot \Pr(S=1) = 0.2133 \cdot 0.3427   = 0.0731
\end{equation}\]</span></p>
<p>We can do similar calculations for the other five joint probabilities and they are all shown in the Table below (note that the marginal probabilities remain unchanged).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indep: <span class="math inline">\(\Pr(C) \Pr(S)\)</span></th>
<th>Class (<span class="math inline">\(C\)</span>)</th>
<th>~</th>
<th>~</th>
<th>~</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived <span class="math inline">\(S\)</span></td>
<td>1st</td>
<td>2nd</td>
<td>3rd</td>
<td>Marginal</td>
</tr>
<tr class="even">
<td>No =0</td>
<td>0.1612</td>
<td>0.1402</td>
<td>0.3559</td>
<td>0.6573</td>
</tr>
<tr class="odd">
<td>Yes = 1</td>
<td>0.0841</td>
<td>0.0731</td>
<td>0.1856</td>
<td>0.3427</td>
</tr>
<tr class="even">
<td>Marginal</td>
<td>0.2452</td>
<td>0.2133</td>
<td>0.5415</td>
<td>1.0000</td>
</tr>
</tbody>
</table>
<p>These probabilities are different to those that we observed. We could now continue and ask, how many of our 1313 Titanic passengers on our database we would have expected to come from 2nd class and have survived if the two variables were independent. We know that this should be 7.31% of the total of 1313, that is 95.96.</p>
<p>We can perform a similar calculation for all the six combinations of outcomes for the variables <span class="math inline">\(C\)</span> and <span class="math inline">\(S\)</span>. The folowing table shows both, the original number of observations (<span class="math inline">\(O_{sc}\)</span>) and the expected number of observations (<span class="math inline">\(E_{sc}\)</span>) if <span class="math inline">\(C\)</span> and <span class="math inline">\(S\)</span> were independent.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(O_{sc}\)</span> (<span class="math inline">\(E_{sc}\)</span>)</th>
<th>Class</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived</td>
<td>1st</td>
<td>2nd</td>
<td>3rd</td>
<td>Total</td>
</tr>
<tr class="even">
<td>No = 0</td>
<td>129 (211.64)</td>
<td>161 (184.04)</td>
<td>573 (467.32)</td>
<td></td>
</tr>
<tr class="odd">
<td>Yes = 1</td>
<td>193 (110.35)</td>
<td>119 (95.96)</td>
<td>138 (243.68)</td>
<td></td>
</tr>
<tr class="even">
<td>Total</td>
<td></td>
<td></td>
<td></td>
<td>1313</td>
</tr>
</tbody>
</table>
<p>You can already see from this table that, if the two variables were independent we should expect to see more survivors from the 3rd class passengers (243.68 compared to 138). In reverse, we do see more 1st class survivors than we would expect under independence (193 compared to 110.35). These differences seem suggestive of the two random variables not being independent, but, as we are trained as good statisticians, we know that, even if the null hypothesis of independence was correct, we would expect to see some sample variations.</p>
<p>The question is, however, how likely is it to see differences like the ones we can see in the last table (or more extreme) if the null hypothesis was true. In other words, we wish to calculate a p-value for the above hypothesis.</p>
<p>As you know from previous applications for hypothesis testing, to calculate a p-value we need a test statistic and a distribution. The test statistic is defined as</p>
<p><span class="math display">\[\begin{equation*}
    C^2 = \Sigma_{all~S} \Sigma_{all~C}  \frac{(O_{cs} - E_{cs})^2}{E_{sc}}
\end{equation*}\]</span></p>
<p>The double sum merely achieves that we calculate this difference for all joint categories (here six) and the index <span class="math inline">\(sc\)</span> indexes the survival status (<span class="math inline">\(S=s\)</span>) and the class (<span class="math inline">\(C=c\)</span>) respectively.</p>
<p>The test statistic <span class="math inline">\(C^2\)</span> increases as the differences ( <span class="math inline">\(O_{cs} - E_{cs}\)</span> ) increase. The question is when is it too big (or the probability of it occurring under the validity of the null hypothesis too small) to be consistent with the null hypothesis. This can be determined once you know the test statistic’s distribution.</p>
<p><span class="math display">\[\begin{equation*}
    C^2 \sim \chi^2_{(rows-1)(cols-1)}
\end{equation*}\]</span></p>
<p>The <span class="math inline">\(\chi^2\)</span> distribution, like the t-distribution has one degrees of freedom parameter. For this particular test, that degrees of freedom parameter is calculated as <span class="math inline">\((rows-1)(cols-1)\)</span> where <span class="math inline">\(rows\)</span> is the number of row categories (here 2 as the survival variable has two categories) and <span class="math inline">\(cols\)</span> is the number of column categories (here 3, the number of classes on the Titanic). Therefore, in our example the degrees of freedom parameter take the value <span class="math inline">\(1\cdot2=2\)</span>.</p>
<p>Depending on the degrees of freedom, <span class="math inline">\(\chi^2\)</span> distributions can take quite different shapes. The following image provides a few examples.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chisq.png" class="img-fluid figure-img"></p>
<figcaption><span class="math inline">\(\chi^2\)</span> distributions with various degrees of freedom.</figcaption>
</figure>
</div>
<p>As for the t- and Normal distribution there are statistical tables. You could also use the Excel function “=CHISQ.DIST(X,dof,TRUE)” to get <span class="math inline">\(\Pr(\chi^2_{dof}\leq X)\)</span> to obtain probabilities from the cdf. So, let’s calculate that test statistic for our example</p>
<p><span class="math display">\[\begin{eqnarray*}
    C^2 &amp;=&amp; \frac{(129 - 211.64)^2}{211.64} + \frac{(161 - 184.04.64)^2}{184.04} + \frac{(573 - 467.32)^2}{467.32} +\\ &amp;&amp;\frac{(193 - 110.35)^2}{110.35} + \frac{(119 - 95.96)^2}{95.96} + \frac{(138 - 243.68)^2}{243.68}\\
    &amp;=&amp;  172.30  
\end{eqnarray*}\]</span></p>
<p>To calculate the p-value we now need to figure out <span class="math inline">\(\Pr(\chi^2_{2}\geq 172.30)=1-\Pr(\chi^2_{2}&lt; 172.30)\)</span> recognising that we are looking at 2 degrees of freedom. By visually inspecting the <span class="math inline">\(\chi^2\)</span> cdf with two degrees of freedom you can already tell that virtually all density is to the left of 172.30 (with the largest X value being 20 on the graph). So in this example <span class="math inline">\(\Pr(\chi^2_{2}\geq 172.30)=1-1=0\)</span>. So the p-value of our test is virtually 0 and hence we reject <span class="math inline">\(H_0\)</span>. This means, for this example we reject the null hypothesis and we conclude that there is dependence between <span class="math inline">\(S\)</span> and <span class="math inline">\(C\)</span> and we confirm what we suspected after looking at the earlier table. As a first class passenger you had a higher probability of surviving the sinking of the Titanic.</p>
<p>For this test statistic to provide reliable results we need two things:</p>
<ol type="1">
<li>the data need to be a random sample from a population</li>
<li>sufficient observations, such that in each of the categories we have <span class="math inline">\(E_{sc} \geq 5\)</span></li>
</ol>
<p>In case you do have categories which are too small you can consider combining categories to greater larger categories.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are the manager of a record store (<a href="https://www.piccadillyrecords.com/">For the younger of you a visit to Picadilly Records may be useful, like this one in Manchester, UK</a>). One of your unique selling points is that you have staff members who are very knowledgable in particular genres of music. You wonder whether on different days your customers’ music taste is significantly different.</p>
<p>For one (typical) week you record the number of customers and ask them for their favourite music genres.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Observed</th>
<th>Music (<span class="math inline">\(M\)</span>)</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Weekday (<span class="math inline">\(W\)</span>)</td>
<td>Hip Hop</td>
<td>Rock</td>
<td>Metal</td>
<td>Pop</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Monday</td>
<td>40</td>
<td>60</td>
<td>92</td>
<td>98</td>
<td>290</td>
</tr>
<tr class="odd">
<td>Tuesday</td>
<td>36</td>
<td>66</td>
<td>67</td>
<td>67</td>
<td>236</td>
</tr>
<tr class="even">
<td>Wednesday</td>
<td>29</td>
<td>69</td>
<td>54</td>
<td>58</td>
<td>210</td>
</tr>
<tr class="odd">
<td>Thursday</td>
<td>43</td>
<td>90</td>
<td>98</td>
<td>78</td>
<td>309</td>
</tr>
<tr class="even">
<td>Friday</td>
<td>82</td>
<td>156</td>
<td>132</td>
<td>134</td>
<td>504</td>
</tr>
<tr class="odd">
<td>Saturday</td>
<td>78</td>
<td>134</td>
<td>151</td>
<td>144</td>
<td>507</td>
</tr>
<tr class="even">
<td>Total</td>
<td>308</td>
<td>575</td>
<td>594</td>
<td>579</td>
<td>2056</td>
</tr>
</tbody>
</table>
<p>What is the test statistic?</p>
<p><span class="math inline">\(\chi^2 =\)</span> <input class="webex-solveme nospaces" data-tol="0.001" size="7" data-answer="[&quot;19.3011&quot;]"></p>
<p>What are the d.o.f. for the distribution of the test statistic under the null hypothesis?</p>
<p>d.o.f = <input class="webex-solveme nospaces" size="2" data-answer="[&quot;15&quot;]"></p>
<p>What is the test’s p-value?</p>
<p>p-value = <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2004&quot;,&quot;.2004&quot;]"></p>
<p>What is your conclusion?</p>
<ul>
<li>A. There is very little evidence to support the null hypothesis that customer’s music tastes differ by weekday.</li>
<li>B. There is very little evidence to support the null hypothesis that customer’s music tastes are the same on different weekday..</li>
<li>C. There is not sufficient evidence to reject the null hypothesis that customer’s music tastes differ by weekday.</li>
<li>D. There is not sufficient evidence to reject the null hypothesis that customer’s music tastes are the same on different weekday.</li>
</ul>
<div class="webex-solution">
<button>
Solution
</button>
<p>Test stat: <span class="math inline">\(\chi^2 = 19.3011\)</span> (best to use EXCEL)<br>
<span class="math inline">\(dof = (6-5)(4-1)=15\)</span><br>
<span class="math inline">\(p-val = 0.2004\)</span></p>
<p>Here is a video walk-through for the above problem (YouTube, 27min)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/R723nbR2pdI" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
</div>
</div>
</section>
<section id="summary" class="level3" data-number="14.10.4">
<h3 data-number="14.10.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">14.10.4</span> Summary</h3>
<p>The last three examples were examples of hypothesis tests that test for other things but for a value of the population mean. There are many other tests you could perform. Commonly you may want to perform a test on the variance (or equality of variances) in a population or on the type of distribution in the population.</p>
<p>If you are an applied economist you may frequently refer to textbooks or the internet to search for “Hypothesis test of XX”. Here we cannot cover any of these details, but hopefully, by now, you realise that hypothesis tests have some common features:</p>
<ul>
<li>A set of hypotheses</li>
<li>A test statistic</li>
<li>A distribution for this test statistic (assuming <span class="math inline">\(H_0\)</span> is correct and potentially the validity of some further assumptions)</li>
<li>Calculate a p-value to see how compatible the data are with the null hypothesis</li>
</ul>
<p>If you look for these elements in any hypothesis test then you should be able to navigate new tests (YouTube, 2min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/4Vql2gOh6V8" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Statistical v. Economic significance
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is an additional aspect of hypothesis tests you should be aware of. You may well conclude, after performing a hypothesis test that there is sufficient statistical evidence to reject a null hypothesis. We sometimes call this a statistically significant test result. If this is formulated carefully it will not say just “siginificant test result”, i.e.&nbsp;without the “statistically”. Because, what is statistically significant is not necessarily substantially, or economically, significant.</p>
<p>Especially in times where we can use large amounts of data, we may find statistically significant results which are not really substantially significant. A good example of such a case is described by <a href="https://understandinguncertainty.org/risks-big-data-%E2%80%93-or-why-i-am-not-worried-about-brain-tumours">David Spiegelhalter in this blog post</a>. Here he describes why the finding that people with university degrees are statistically more likely to have brain tumors should not keep you awake at night.</p>
</div>
</div>
</section>
</section>
<section id="extra-reading" class="level2" data-number="14.11">
<h2 data-number="14.11" class="anchored" data-anchor-id="extra-reading"><span class="header-section-number">14.11</span> Extra reading</h2>
<p>If you want to know more about the subtleties of p-values, then this is a good read: Lew, M.J. (2020) <a href="https://link.springer.com/chapter/10.1007/164_2019_286">A Reckless Guide to P-values: Local Evidence, Global Errors, Part of the Handbook of Experimental Pharmacology book series</a> (HEP,volume 257).</p>


</section>

</main> <!-- /main -->
<script src="include/webex.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Sampling_Dist.html" class="pagination-link" aria-label="Sampling Distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>