<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Introducing Probability – Statistics Notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ConditionalProbability.html" rel="next">
<link href="./DealingWithDataSets.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./IntroToProbability.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introducing Probability</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Notes</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datatypes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Types</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphical_descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Numerical Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./CorrelationRegressionCausation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation, Regression and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DealingWithDataSets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dealing with real life datasets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IntroToProbability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introducing Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ConditionalProbability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">7.1</span> Introduction</a></li>
  <li><a href="#venn-diagrams" id="toc-venn-diagrams" class="nav-link" data-scroll-target="#venn-diagrams"><span class="header-section-number">7.2</span> Venn diagrams</a></li>
  <li><a href="#probability" id="toc-probability" class="nav-link" data-scroll-target="#probability"><span class="header-section-number">7.3</span> Probability</a>
  <ul class="collapse">
  <li><a href="#the-axioms-of-probability" id="toc-the-axioms-of-probability" class="nav-link" data-scroll-target="#the-axioms-of-probability"><span class="header-section-number">7.3.1</span> The axioms of probability</a></li>
  <li><a href="#the-addition-rule-of-probability" id="toc-the-addition-rule-of-probability" class="nav-link" data-scroll-target="#the-addition-rule-of-probability"><span class="header-section-number">7.3.2</span> The addition rule of probability</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introducing Probability</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">7.1</span> Introduction</h2>
<p>This video gives a brief introduction into why economists and social scientists should study probabilities (YouTube, 4min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/I3OFG1QlDLc" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>So far we have been looking at ways of summarising samples of data drawn from an underlying population of interest. Although at times tedious, all such arithmetic calculations are fairly mechanical and straightforward to apply. To remind ourselves, one of the primary reasons for wishing to summarise data is so assist in the development of inferences about the population from which the data were taken. That is to say, we would like to elicit some information about the mechanism which generated the observed data.</p>
<p>Perhaps you can recall this little schematic which we discussed in the introduction.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/InferenceScheme.png" class="img-fluid figure-img"></p>
<figcaption>Schematic of Statistical Inference and how it relates to descriptive statistics and probability calculus.</figcaption>
</figure>
</div>
<p>We now start on the process of developing mathematical ways of formulating inferences and this requires the use of <strong>probability</strong>. This becomes clear if we think back to one of the early questions posed in this course: “prior to sampling is it possible to predict with absolute certainty what will be observed?” The answer to this question is “no”; although it would be of interest to know <strong>how likely it is that certain values would be observed</strong>. Or, what is the <strong>probability</strong> of observing certain values?</p>
<p>Before proceeding, we need some more tools:</p>
</section>
<section id="venn-diagrams" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="venn-diagrams"><span class="header-section-number">7.2</span> Venn diagrams</h2>
<p>Venn diagrams (and diagrams in general) are of enormous help in trying to understand, and manipulate probability. We begin with some basic definitions, some of which we have encountered before.</p>
<ul>
<li><p><strong>Experiment</strong>: any process which, when applied, provides data or an outcome; e.g., rolling a dice and observing the number of dots on the upturned face; recording the amount of rainfall in Manchester over a period of time.</p></li>
<li><p><strong>Sample Space</strong>: set of possible outcomes of an experiment; e.g., <span class="math inline">\(S\)</span> (or $$) <span class="math inline">\(=\)</span> <span class="math inline">\(\{1,2,3,4,5,6\}\)</span>, which is the sample space of rolling a dice. Or <span class="math inline">\(S=\{x;x\geq 0\}\)</span>, which is the sample space of an experiment where the outcomes can be any real non-negative number, or the set of real non-negative real numbers.</p></li>
<li><p><strong>Simple Event</strong>: just one of the possible outcomes on <span class="math inline">\(S\)</span></p></li>
<li><p><strong>Event</strong>: a subset of <span class="math inline">\(S\)</span>, denoted <span class="math inline">\(E\subset S\)</span>; e.g., <span class="math inline">\(E=\left\{ 2,4,6\right\}\)</span> (i.e.&nbsp;any even number on a dice) or <span class="math inline">\(E=\left\{ x;4&lt;x\leq 10\right\}\)</span>, which means “the set of real numbers which are strictly bigger than <span class="math inline">\(4\)</span> but less than or equal to <span class="math inline">\(10\)</span>”.<br>
Note that an event, <span class="math inline">\(E\)</span>, is a collection of simple events. You will have to decide what your event of interest is and that depends on the situation.</p></li>
</ul>
<p>Such concepts can be represented by means of the following Venn Diagram:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Venn_1.jpg" class="img-fluid figure-img"></p>
<figcaption>Venn Diagram.</figcaption>
</figure>
</div>
<p>The sample space, <span class="math inline">\(S\)</span>, is depicted as a closed rectangle, and the event <span class="math inline">\(E\)</span> is a closed loop wholly contained within <span class="math inline">\(S\)</span> and we write (in set notation) <span class="math inline">\(E\subset S\)</span>.</p>
<p>In dealing with probability, and in particular the probability of an event (or events) occurring, we shall need to be familiar with <strong>unions, intersections</strong> and <strong>complements</strong>.</p>
<p>To illustrate these concepts, consider the sample space <span class="math inline">\(S=\{x;x\geq 0\}\)</span>. In this example the sample space represents an infinite set of numbers. Don’t let the square finite sample space, represented in the next Figure, distract you from that. The following events defined on <span class="math inline">\(S\)</span>, as depicted in the Figure:</p>
<p><span class="math inline">\(E=\{x;4&lt;x\leq 10\},\,F=\{x;7&lt;x\leq 17\},\,G=\{x;x&gt;15\},\,H=\{x;9&lt;x\leq 13\}\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Venn_2.png" class="img-fluid figure-img"></p>
<figcaption>Venn Diagram.</figcaption>
</figure>
</div>
<p>Note that the size of the graphical representation does not represent any probabilities here.</p>
<ul>
<li><ol type="a">
<li>Event <span class="math inline">\(E\)</span>: This graphical representation merely illustrates that <span class="math inline">\(E\)</span> is a subset of <span class="math inline">\(S\)</span>, <span class="math inline">\(E\subset S\)</span></li>
</ol></li>
<li><ol start="2" type="a">
<li>Union: <span class="math inline">\(E\cup F\)</span><br>
The <strong>union</strong> of <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> is denoted <span class="math inline">\(E\cup F\)</span>, with <span class="math inline">\(E\cup F=\{x;4&lt;x\leq 17\}\)</span>; i.e., it contains elements (simple events) which are either in <span class="math inline">\(E\)</span> or in <span class="math inline">\(F\)</span> or (perhaps) in both. This is illustrated on the Venn diagram by the dark shaded area in diagram (b).</li>
</ol></li>
<li><ol start="3" type="a">
<li>Intersection: <span class="math inline">\(E\cap F\)</span><br>
The <strong>intersection</strong> of <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> is denoted <span class="math inline">\(E\cap F\)</span>, with $EF={ x;7x} $; i.e., it contains elements (simple events) which are common to both <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span>. Again this is depicted by the dark shaded area in (c).</li>
</ol></li>
<li><ol start="4" type="a">
<li>The Null set/event: $EG=$<br>
If events have no elements in common (as, for example, <span class="math inline">\(E\)</span> and <span class="math inline">\(G\)</span>) then they are said to be <strong>mutually exclusive</strong>, and we can write <span class="math inline">\(E\cap G=\emptyset\)</span>, meaning the <strong>null set</strong> which contains no elements. Such a situation is illustrated on the Venn Diagram by events (the two shaded events in (d)) which do not overlap. Notice however that <span class="math inline">\(G\cap F\neq \emptyset\)</span>, since <span class="math inline">\(G\)</span> and <span class="math inline">\(F\)</span> have elements in common.</li>
</ol></li>
<li><ol start="5" type="a">
<li>Complement of <span class="math inline">\(E\)</span>: <span class="math inline">\(\bar{E}\)</span><br>
The <strong>complement</strong> of an event <span class="math inline">\(E\)</span>, say, is everything defined on the sample space which is not in <span class="math inline">\(E\)</span> This event is denoted <span class="math inline">\(\bar{E}\)</span>, the dark shaded area in (e); here <span class="math inline">\(\bar{E}=\left\{ x;x\leq 4\right\} \cup \left\{ x;x&gt;10\right\}\)</span>. An alternative notation that is sometimes used for the complement of an event <span class="math inline">\(E\)</span> is <span class="math inline">\(E^c\)</span>.</li>
</ol></li>
<li><ol start="6" type="a">
<li>Subset of <span class="math inline">\(F\)</span>: <span class="math inline">\(H\subset F\)</span> and <span class="math inline">\(H\cap F=H\)</span><br>
Finally note that <span class="math inline">\(H\)</span> is a sub-set of <span class="math inline">\(F\)</span>; see (f). It is depicted as the dark closed loop wholly contained within <span class="math inline">\(F\)</span>, the lighter shaded area, so that <span class="math inline">\(H\cap F=H\)</span>; if an element in the sample space is a member of <span class="math inline">\(H\)</span> then it must also be member of <span class="math inline">\(F\)</span>. (In mathematical logic, we employ this scenario to indicate that “<span class="math inline">\(H\)</span> implies <span class="math inline">\(F\)</span>”, but not necessarily vice-versa.) Notice that $GH=$ but <span class="math inline">\(H\cap E\neq \emptyset\)</span>.</li>
</ol></li>
</ul>
<p>This video goes through most elements of the above example (YouTube, 8min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/RYRze4XXlrE" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose that the sample space <span class="math inline">\(S\)</span> consists of the positive integers from 1 to 10 inclusive. Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be the following sets:</p>
<p><span class="math inline">\(X=\{2,3,4\},\\\,Y=\{3,4,5\},\\Z=\{5,6,7\}\)</span>.</p>
<p>List the members in the following sets. For the Emplty set answer “.”. If the answer is a single number give that number, if the answer contains several numbers, e.g.&nbsp;3, 5 and 6, then asnwer “3,5,6”, numbers in ascending order , seperated by a comma and without spaces).</p>
<p><span class="math inline">\(\bar{X}\cap Y =\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;5&quot;]"></p>
<p><span class="math inline">\(\bar{X}\cup Y  =\)</span> <input class="webex-solveme nospaces" size="18" data-answer="[&quot;1,3,4,5,6,7,8,9,10&quot;]"></p>
<p><span class="math inline">\(X\cap Z  =\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;.&quot;]"></p>
<p><span class="math inline">\(Y\cup Z  =\)</span> <input class="webex-solveme nospaces" size="9" data-answer="[&quot;3,4,5,6,7&quot;]"></p>
<p><span class="math inline">\(\overline{Y\cup Z} =\)</span> <input class="webex-solveme nospaces" size="10" data-answer="[&quot;1,2,8,9,10&quot;]"></p>
<p><span class="math inline">\(X\cap(\overline{Y\cup Z})  =\)</span> <input class="webex-solveme nospaces" size="1" data-answer="[&quot;2&quot;]"></p>
<p><span class="math inline">\(\overline{X\cap(\overline{Y\cup Z})}  =\)</span> <input class="webex-solveme nospaces" size="18" data-answer="[&quot;1,3,4,5,6,7,8,9,10&quot;]"></p>
<div class="webex-solution">
<button>
Solutions
</button>
<ul>
<li><span class="math inline">\(\bar{X}\cap Y = \{5\}\)</span></li>
<li><span class="math inline">\(\bar{X}\cup Y  = \{1,3,4,5,6,7,8,9,10\}\)</span></li>
<li><span class="math inline">\(X\cap Z  = \{ \emptyset \}\)</span></li>
<li><span class="math inline">\(Y\cup Z  = \{3,4,5,6,7\}\)</span></li>
<li><span class="math inline">\(\overline{Y\cup Z}  = \{1,2,8,9,10\}\)</span></li>
<li><span class="math inline">\(X\cap(\overline{Y\cup Z})  = \{2\}\)</span></li>
<li><span class="math inline">\(\overline{X\cap(\overline{Y\cup Z})}  = \{1,3,4,5,6,7,8,9,10\}\)</span></li>
</ul>
</div>
</div>
</div>
</section>
<section id="probability" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="probability"><span class="header-section-number">7.3</span> Probability</h2>
<p>The term <strong>probability</strong> is used in everyday conversation. Watching the daily news, for instance, you will come across weather forecasts which will often include probabilistic statements like “There is a 70% probability of rain for tomorrow.” Here is a <a href="https://youtu.be/5qPibjwo21g">video on weather forecasts</a> and an incredibly interesting podcast on the <a href="https://www.pushkin.fm/podcasts/against-the-rules/respect-the-polygon">importance of communicating uncertainty in weather forecasts (38 min)</a>.</p>
<p>Other areas where we use probabilities are sports (What is the probability of England winning the World Cup) games of chance (e.g.&nbsp;roulette or poker) or economics (What is the probability of a recession?). What you will do now is to learn about a coherent theory of probability; a theory which allows us to combine and manipulate probabilities in a consistent and meaningful manner. You will describe ways of dealing with, and describing, uncertainty. This will involve <strong>rules</strong> which govern our use of terms like probability.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Communicating uncertainty
</div>
</div>
<div class="callout-body-container callout-body">
<p>Communicating probabilities, or uncertainty is one of the great challenges of scientists, economists and data analysts. Dealing in uncertainties is what we do. But often the people we are communicating to and with do not want to hear uncertainties, they want certainties. Will it rain tomorrow? Yes or No! Will my employer go out of business? Yes or no! Will the Conservatives be able to lead the government after the next election? Yes or no! Will this investment be profitable? Yes or no! Will the Apple share price go up? yes or no!</p>
<p>Despite the thirst for certainty you will have to find ways to communicate uncertainty which both, conveys the right information (including the level of certainty you have), is understandable to the public, and protects your reputation. It turns out that this is a great challenge.</p>
<p>Here is a great <a href="https://fullfact.org/media/uploads/en-communicating-uncertainty.pdf">document on communicating uncertainty</a> by <a href="https://fullfact.org">Full Fact</a> and <a href="https://youtu.be/JhfMkmzaNdU?t=238">a lecture on this issue (60 min)</a> by the excellent David Spiegelhalter and a <a href="http://understandinguncertainty.org/">website</a> he initiated.</p>
<p>This is supplementary and non-assessed information.</p>
</div>
</div>
<p>There have been a number of different approaches (interpretations) of probability. Most depend, at least to some extent, on the notion of relative frequency as now described:</p>
<ul>
<li>Suppose an experiment has an outcome of interest <span class="math inline">\(E\)</span>. The <strong>relative frequency interpretation</strong> of probability says that assuming the experiment can be repeated a large number of times then the relative frequency of observing the outcome <span class="math inline">\(E\)</span> will settle down to a <strong>number</strong>, denoted <span class="math inline">\(\Pr (E)\)</span>, <span class="math inline">\(P(E)\)</span> or Prob<span class="math inline">\((E)\)</span>, called the <strong>probability</strong> of <span class="math inline">\(E\)</span>.</li>
</ul>
<p>This is illustrated in the next Figure where the proportion of heads obtained after <span class="math inline">\(n\)</span> flips of a fair coin is plotted against <span class="math inline">\(n\)</span>, as <span class="math inline">\(n\)</span> increases; e.g., of the first 100 flips, 46 were heads (<span class="math inline">\(46\%\)</span>). Notice that the plot becomes less `wobbly’ after about <span class="math inline">\(n=140\)</span> and appears to be settling down to the value of <span class="math inline">\(\frac{1}{2}\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Prob_coin.jpg" class="img-fluid figure-img"></p>
<figcaption>Relative frequency of heads in <span class="math inline">\(n\)</span> toin tosses.</figcaption>
</figure>
</div>
<p>Due to this interpretation of probability, we often use observed sample proportions to approximate underlying probabilities of interest. There are, of course, other interpretations of probability; e.g., the subjective interpretation which simply expresses the strength of one’s belief about an event of interest such as whether Liverpool will win the Premier League! Any one of these interpretations can be used in practical situations provided the implied notion of probability follows a simple set of <strong>axioms</strong> or <strong>rules</strong>.</p>
<section id="the-axioms-of-probability" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="the-axioms-of-probability"><span class="header-section-number">7.3.1</span> The axioms of probability</h3>
<p>There are just <strong>three</strong> basic rules that must be obeyed when dealing with probabilities:</p>
<ul>
<li>For any event <span class="math inline">\(E\)</span> defined on <span class="math inline">\(S\)</span> i.e., <span class="math inline">\(E\subset S,\,\,\Pr (E)\geq 0\)</span>; <strong>probabilities are non-negative</strong>.</li>
<li><span class="math inline">\(\Pr (S)=1\)</span>; <strong>having defined the sample space of outcomes, one of these outcomes must be observed</strong>.</li>
<li>If events <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> are mutually exclusive defined on <span class="math inline">\(S\)</span>, so that $EF=$, then <span class="math inline">\(\Pr \left( E\cup F\right) =\Pr \left( E\right)+\Pr \left( F\right)\)</span>. In general, for any set of mutually exclusive events, <span class="math inline">\(E_{1},E_{2},\ldots ,E_{k}\)</span>, defined on <span class="math inline">\(S:\)</span><br>
<span class="math display">\[\begin{equation*}
      \Pr (E_{1}\cup E_{2}\cup \ldots \cup E_{k})=\Pr (E_{1})+\Pr (E_{2})+\ldots\Pr (E_{k})
  \end{equation*}\]</span><br>
i.e., <span class="math inline">\(\Pr \left( \bigcup_{j=1}^{k}E_{j}\right) =\sum_{j=1}^{k}\Pr (E_{j})\)</span>.</li>
</ul>
<p>In terms of the Venn Diagram, one can (and should) usefully think of the area of <span class="math inline">\(E\)</span> relative to that of <span class="math inline">\(S\)</span> as providing an indication of probability. (Note, from axiom 2, that the area of <span class="math inline">\(S\)</span> is implicitly normalised to be unity).</p>
<p>Also observe that, contrary to what you may have believed, it is not one of the rules that <span class="math inline">\(\Pr (E)\leq 1\)</span> for any event <span class="math inline">\(E\)</span>. Rather, this is an implication of the three rules given:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Implications
</div>
</div>
<div class="callout-body-container callout-body">
<p>It must be that for any event <span class="math inline">\(E\)</span>, defined on <span class="math inline">\(S\)</span>, $E{E}=$ and <span class="math inline">\(E\cup \bar{E}=S\)</span>. By Axiom 1, <span class="math inline">\(\Pr (E)\geq 0\)</span> and <span class="math inline">\(\Pr \left( \bar{E}\right) \geq 0\)</span> and by Axiom 3, <span class="math inline">\(\Pr(E)+\Pr (\bar{E})=\Pr (S)\)</span>. So <span class="math inline">\(\Pr \left( E\right) +\Pr \left( \bar{E}\right) =1\)</span> by Axiom 2. This implies that</p>
<ul>
<li><span class="math inline">\(0\leq \Pr (E)\leq 1\)</span></li>
<li><span class="math inline">\(\Pr (\bar{E})=1-\Pr (E)\)</span></li>
</ul>
<p>The first of these is what we might have expected from probability (a number lying between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>). The second implication is also very important; it says that the probability of <span class="math inline">\(E\)</span> not happening is one minus the probability of it happening. Thus when rolling a die, the probability of getting <span class="math inline">\(6\)</span> is one minus the probability of getting either a <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, <span class="math inline">\(3\)</span>, <span class="math inline">\(4\)</span> or <span class="math inline">\(5\)</span>.</p>
</div>
</div>
<p>These axioms imply how to calculate probabilities on a sample space of equally likely outcomes. For example, and as we have already noted, the experiment of rolling a fair dice defines a sample space of six, mutually exclusive and equally likely outcomes (1 to 6 dots on the up-turned face). The axioms then say that each of the six probabilities are positive, add to 1 and are all the same. Thus, the probability of any one of the outcomes must be simply <span class="math inline">\(\frac{1}{6}\)</span>; which may accord with your intuition.</p>
<p>A similar sort of analysis reveals that the probability of drawing a club from a deck of 52 cards is <span class="math inline">\(\frac{13}{52}\)</span> since any one of the 52 cards has an equal chance of being drawn and 13 of them are clubs; i.e., 13 of the 52 are clubs, so the probability of drawing a club is <span class="math inline">\(\frac{13}{52}\)</span>. Notice the importance of the assumption of equally likely outcomes here.</p>
<p>In what follows you shall see how these axioms can be used. Firstly, consider the construction of a probability for the <strong>union</strong> of two events; i.e., the probability that <strong>either</strong> <span class="math inline">\(E\)</span> or <span class="math inline">\(F\)</span> or (perhaps) <strong>both</strong> will occur. Such a probability is embodied in the <strong>addition rule of probability</strong>.</p>
</section>
<section id="the-addition-rule-of-probability" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored"><span class="header-section-number">7.3.2</span> The addition rule of probability</h3>
<p>Let us begin with an example.</p>
<section id="example" class="level4 callout-info" data-number="7.3.2.1">
<h4 data-number="7.3.2.1" class="anchored" data-anchor-id="example"><span class="header-section-number">7.3.2.1</span> Example</h4>
<p>When rolling a fair dice, let <span class="math inline">\(E\)</span> denote the event of an “odd number of dots” and <span class="math inline">\(F\)</span> the event of the “number of dots being greater than, or equal, to <span class="math inline">\(4\)</span>”.</p>
<p><span class="math inline">\(E = \{1,3,5\}\)</span>, <span class="math inline">\(Pr(E) = \frac{3}{6}=0.5\)</span><br>
<span class="math inline">\(F = \{4,5,6\}\)</span>, <span class="math inline">\(Pr(F) = \frac{3}{6}=0.5\)</span></p>
<p>What is the probability of the event <span class="math inline">\(E\cup F\)</span>? To calculate this we can collect together all the mutually exclusive (simple) events which comprise <span class="math inline">\(E\cup F\)</span>, and then add up the probabilities (by axiom 3).</p>
<p><span class="math inline">\(E\cup F = \{1,3,4,5,6 \}\)</span>, <span class="math inline">\(Pr(E\cup F) = \frac{5}{6}\)</span><br>
<span class="math inline">\(E\cap F = \{5\}\)</span>, <span class="math inline">\(Pr(E\cap F) = \frac{1}{6}\)</span></p>
<p>Each of the simple events has a probability of <span class="math inline">\(\frac{1}{6}\)</span> so the required total probability is: <span class="math inline">\(\Pr \left( E\cup F\right) =\frac{5}{6}\)</span>. Consider carefully how this probability is constructed and note, in particular, that $( EF) ( E) +( F) $ since <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> have a simple event in common (namely 5 dots). As you will see shortly, <span class="math inline">\(\Pr \left( E\cup F\right) = \Pr \left( E\right) +\Pr \left( F\right) - \Pr(E \cap F)\)</span>.</p>
<p>This video goes through the above brief example (YouTube, 5min).</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/sFijzt3ByzY" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<p>In general, we can calculate the probability of the union of events using the <strong>addition rule of probability</strong>, as follows.</p>
<ul>
<li>For any events, <span class="math inline">\(E\subset S\)</span> and <span class="math inline">\(F\subset S:\Pr (E\cup F)=\Pr (E)+\Pr (F)-\Pr (E\cap F)\)</span>. So, in general, <span class="math inline">\(\Pr \left( E\cup F\right) \leq \Pr (E)+\Pr (F)\)</span>.</li>
</ul>
<p>We can demonstrate this as follows. Note that</p>
<p><span class="math display">\[\begin{equation*}
E\cup F=\left( E\cap \bar{F}\right) \cup \left( E\cap F\right) \cup \left(\bar{E}\cap F\right)
\end{equation*}\]</span></p>
<p>the union of three mutually exclusive events. These mutually exclusive events are depicted by the shaded areas <span class="math inline">\(\mathbf{a}\)</span>, <span class="math inline">\(\mathbf{b}\)</span> and <span class="math inline">\(\mathbf{c}\)</span>, respectively, in the next Figure.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Prob_add.jpg" class="img-fluid figure-img"></p>
<figcaption>Venn diagram to illustrate the addition rule.</figcaption>
</figure>
</div>
<p>Then by Axiom 3, and from the fact that the three events $( E{F}) $, $( EF) $ and <span class="math inline">\(\left( \bar{E}\cap F\right)\)</span> are mutually exclusive so that the “area” occupied by <span class="math inline">\(E\cup F\)</span> is simply <span class="math inline">\(\mathbf{a+b+c}\)</span>,</p>
<p><span class="math display">\[\begin{equation*}
\Pr \left( E\cup F\right) =\Pr \left( E\cap \bar{F}\right) +\Pr \left( \bar{E}\cap F\right) +\Pr \left( E\cap F\right) .
\end{equation*}\]</span></p>
<p>But also by Axiom 3, since $E=( E{F}) (EF) $, it must be that <span class="math inline">\(\Pr (E)=\Pr \left( E\cap \bar{F}\right)+\Pr (E\cap F)\)</span>; similarly, <span class="math inline">\(\Pr \left( \bar{E}\cap F\right) =\Pr \left(F\right) -\Pr \left( E\cap F\right)\)</span>. Putting all of this together gives</p>
<p><span class="math display">\[\begin{equation*}
\Pr (E\cup F)=\Pr (E)+\Pr (F)-\Pr (E\cap F).
\end{equation*}\]</span></p>
<p>This was a lengthy probabilistic argument to make sense of the probability addition formula. You may wonder why the addition formula is not just <span class="math inline">\(\Pr (E\cup F)=\Pr (E)+\Pr (F)\)</span>? You can refer back to the image above. If we just added <span class="math inline">\(\Pr (E)\)</span> and <span class="math inline">\(\Pr (F)\)</span> we would have double counted area b. We therefore have to subtract it once. And area b is <span class="math inline">\(\Pr (E\cap F)\)</span>.</p>
<p>When <span class="math inline">\(E\)</span> and <span class="math inline">\(F\)</span> are mutually exclusive, then there is no overlap, so that <span class="math inline">\(E\cap F=\emptyset\)</span>, this rule reveals Axiom 2: <span class="math inline">\(\Pr (E\cup F)=\Pr (E)+\Pr (F)\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the probability of drawing a Queen (<span class="math inline">\(Q\)</span>) or a Club (<span class="math inline">\(C\)</span>) in a single draw from a pack of cards?</p>
<p>The probability is <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.3077&quot;,&quot;.3077&quot;]"> (answer in decimals and rounded to 4dp)</p>
<div class="webex-solution">
<button>
Solutions
</button>
<p>4 out of 52 cards are Queens, so <span class="math inline">\(\Pr \left( Q\right) =\frac{4}{52}\)</span>, whilst <span class="math inline">\(\Pr\left( C\right) =\frac{13}{52}\)</span>. The probability of drawing the Queen of Clubs is simply <span class="math inline">\(\frac{1}{52}\)</span>; i.e., <span class="math inline">\(\Pr \left( Q\cap C\right) =\frac{1}{52}\)</span>. What we require is a Club or a Queen, for which the probability is</p>
<p><span class="math display">\[\begin{eqnarray*}
\Pr \left( Q\cup C\right) &amp;=&amp;\Pr \left( Q\right) +\Pr \left( C\right) -\Pr\left( Q\cap C\right) \\
&amp;=&amp;\frac{4}{52}+\frac{13}{52}-\frac{1}{52} \\
&amp;=&amp;\frac{16}{52}=\frac{4}{13} = 0.3077.
\end{eqnarray*}\]</span></p>
</div>
</div>
</div>
<p>You will often be presented with frequency (count) tables of the following type.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Region</th>
<th>Very good health</th>
<th>Good health</th>
<th>Fair health</th>
<th>Bad health</th>
<th>Very bad health</th>
<th><strong>Sum</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>North East</td>
<td>11,425</td>
<td>8,795</td>
<td>3,977</td>
<td>1,476</td>
<td>428</td>
<td>26,101</td>
</tr>
<tr class="even">
<td>North West</td>
<td>32,413</td>
<td>23,502</td>
<td>9,847</td>
<td>3,842</td>
<td>1,083</td>
<td>70,687</td>
</tr>
<tr class="odd">
<td>London</td>
<td>20,086</td>
<td>18,302</td>
<td>7,476</td>
<td>2,376</td>
<td>701</td>
<td>52,943</td>
</tr>
<tr class="even">
<td><strong>Sum</strong></td>
<td>67,924</td>
<td>50,599</td>
<td>21,300</td>
<td>7,694</td>
<td>2,214</td>
<td>149,731</td>
</tr>
</tbody>
</table>
<p>These are the respondents from three UK regions (North East, North West and London) and their self indicated health status. The data are available in the 2011 Census Microdata Teaching File (see the Data Sets page). For instance there are 8,795 respondents from the North East that indicated that their health was best categorised as “Good health”. Throughout the three regions there were 50,599 respondents that gave “Good health” as their health status.</p>
<p>Now you may be interested whether, for instance, respondents from the North West tend to be more positive about their health, compared to respondents from other regions. For this purpose it is useful to calculate a probability table based on the above frequency table. The way to do that is to divide all frequency values in the above table by the total number of responses, here 149,731. For example, for the above case of someone coming from the North East and indicating “Good health” we would calculate <span class="math inline">\(8795/149731\)</span> which results in <span class="math inline">\(0.0587\)</span>. This is the probability that, if we randomly drew a person from our 149,731 responses, we would get someone from the North East with “Good health”, <span class="math inline">\(Pr("North~East" \cap "Good~health")=0.0587\)</span>. If you do that for all cells in the above table you get the following:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Region</th>
<th>Very good health</th>
<th>Good health</th>
<th>Fair health</th>
<th>Bad health</th>
<th>Very bad health</th>
<th><strong>Sum</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>North East</td>
<td>0.0763</td>
<td>0.0587</td>
<td>0.0266</td>
<td>0.0099</td>
<td>0.0029</td>
<td>0.1743</td>
</tr>
<tr class="even">
<td>North West</td>
<td>0.2165</td>
<td>0.1570</td>
<td>0.0658</td>
<td>0.0257</td>
<td>0.0072</td>
<td>0.4721</td>
</tr>
<tr class="odd">
<td>London</td>
<td>0.1609</td>
<td>0.1222</td>
<td>0.0499</td>
<td>0.0159</td>
<td>0.0047</td>
<td>0.3536</td>
</tr>
<tr class="even">
<td><strong>Sum</strong></td>
<td>0.4536</td>
<td>0.3379</td>
<td>0.1423</td>
<td>0.0514</td>
<td>0.0148</td>
<td>1.000</td>
</tr>
</tbody>
</table>
<p>As another example, the <strong>Pr(“London” “Very<sub>bad</sub>health”)=0.0047</strong> implies that 0.47% of the sample are respondents from London with very bad health. We call these probabilities joint probabilities and in the above table they are coloured in blue. The probabilities at the margins of the table are also called marginal probabilities. For instance <span class="math inline">\(Pr("London")=0.3536\)</span>, meaning that if we randomly draw a response from the above 149,731 respondents, there is a 35% probability that this response comes from London.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following frequency table, where 9,900 respondents from two cities have been asked whether they enjoy eating vegetables.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">City</th>
<th style="text-align: right;">Enjoy (E)</th>
<th style="text-align: right;">Neutral (N)</th>
<th style="text-align: right;">Do not enjoy (D)</th>
<th style="text-align: right;"><strong>Sum</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Springfield (S)</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="3" data-answer="[&quot;752&quot;]"></td>
<td style="text-align: right;">1,045</td>
<td style="text-align: right;">876</td>
<td style="text-align: right;">2,673</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gotham City (G)</td>
<td style="text-align: right;">2,893</td>
<td style="text-align: right;">2,504</td>
<td style="text-align: right;">1,803</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="4" data-answer="[&quot;7200&quot;]"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Sum</strong></td>
<td style="text-align: right;">3,645</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="4" data-answer="[&quot;3549&quot;]"></td>
<td style="text-align: right;">2,679</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="4" data-answer="[&quot;9873&quot;]"></td>
</tr>
</tbody>
</table>
<p>Complete the above table using the link between joint and marginal frequencies.</p>
<p>Now calculate the probability table (to 4dp:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">City</th>
<th style="text-align: right;">Enjoy (E)</th>
<th style="text-align: right;">Neutral (N)</th>
<th style="text-align: right;">Do not enjoy (D)</th>
<th style="text-align: right;"><strong>Sum</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Springfield (S)</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.0762&quot;,&quot;.0762&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.1058&quot;,&quot;.1058&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.0887&quot;,&quot;.0887&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2707&quot;,&quot;.2707&quot;]"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Gotham City (G)</td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="5" data-answer="[&quot;0.293&quot;,&quot;.293&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2536&quot;,&quot;.2536&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.1826&quot;,&quot;.1826&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.7293&quot;,&quot;.7293&quot;]"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Sum</strong></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.3692&quot;,&quot;.3692&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.3595&quot;,&quot;.3595&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.2713&quot;,&quot;.2713&quot;]"></td>
<td style="text-align: right;"><input class="webex-solveme nospaces" size="1" data-answer="[&quot;1&quot;]"></td>
</tr>
</tbody>
</table>
<p>The <span class="math inline">\(Pr("Springfield" \cap "Enjoy")\)</span> is a <select class="webex-select"><option value="blank"></option><option value="">marginal</option><option value="answer">joint</option></select> probability.</p>
<p>The <span class="math inline">\(Pr("Gotham~City")\)</span> is a <select class="webex-select"><option value="blank"></option><option value="answer">marginal</option><option value="">joint</option></select> probability.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a car journey from Manchester to London via the M6 and M1. Let <span class="math inline">\(E=\)</span> be “heavy traffic somewhere on route” and <span class="math inline">\(F=\)</span> “roadworks somewhere on route”. It is estimated that <span class="math inline">\(\Pr (E)=0.8\)</span> and <span class="math inline">\(\Pr (F)=0.4\)</span>, whilst the probability of NOT encountering both is <span class="math inline">\(\Pr (\overline{E\cap F})=0.6\)</span>. What is the probability of encountering heavy traffic or roadworks?</p>
<p>What is <span class="math inline">\(\Pr \left( E\cup F\right)\)</span>?</p>
<p><span class="math inline">\(\Pr \left( E\cup F\right) =\)</span> <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.8&quot;,&quot;.8&quot;]"></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>First calculate <span class="math inline">\(\Pr \left( E\cap F\right) = 0.4\)</span></p>
</div>
<div class="webex-solution">
<button>
Feedback
</button>
<p><span class="math display">\[\begin{eqnarray*}
\Pr (E\cup F) &amp;=&amp;\Pr (E)+\Pr (F)-\Pr (E\cap F) \\
&amp;=&amp;\Pr (E)+\Pr (F)-(1-\Pr (\overline{E\cap F})) \\
&amp;=&amp;0.8+0.4-1+0.6 \\
&amp;=&amp;0.8=\Pr (E)
\end{eqnarray*}\]</span></p>
<p>This video works through this example (YouTube, 7min).</p>
<p></p><div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/agQPNVssoAQ" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>.<p></p>
</div>
<p>Notice that this implies, in this case, that <span class="math inline">\(F\subset E\)</span> (why?). This then implies that when there are roadworks somewhere on route you are bound to encounter heavy traffic; on the other hand, you can encounter heavy traffic on route without ever passing through roadworks.</p>
</div>
</div>
<p>We can generalise this addition rule to three events, <span class="math inline">\(E_{1},E_{2}\)</span> and <span class="math inline">\(E_{3}\)</span> as</p>
<p><span class="math display">\[\begin{eqnarray*}
    \Pr (E_{1}\cup E_{2}\cup E_{3}) &amp;=&amp;\Pr (E_{1})+\Pr (E_{2})+\Pr (E_{3}) \\
    &amp;&amp;-\Pr (E_{1}\cap E_{2})-\Pr (E_{1}\cap E_{3})-\Pr (E_{2}\cap E_{3}) \\
    &amp;&amp;+\Pr (E_{1}\cap E_{2}\cap E_{3}).
\end{eqnarray*}\]</span></p>
<section id="example-1" class="level4 callout-info" data-number="7.3.2.2">
<h4 data-number="7.3.2.2" class="anchored" data-anchor-id="example-1"><span class="header-section-number">7.3.2.2</span> Example</h4>
<p>You are asked to spin a <a href="https://g.co/kgs/FB3Wif">wheel of fortune (change the wheel size to 12!)</a> with numbers 1 to 12 being equally likely outcomes. The three events you consider are:</p>
<ul>
<li><span class="math inline">\(E_1=\{\)</span> any number larger or equal than 10 <span class="math inline">\(\}\)</span></li>
<li><span class="math inline">\(E_2=\{\)</span> any number smaller than 5 <span class="math inline">\(\}\)</span></li>
<li><span class="math inline">\(E_3=\{\)</span> any even number <span class="math inline">\(\}\)</span></li>
</ul>
<p>What is the probability that any of these three events occurs?</p>
<p><span class="math display">\[\begin{eqnarray*}
    \Pr (E_{1}\cup E_{2}\cup E_{3}) &amp;=&amp;\Pr (E_{1})+\Pr (E_{2})+\Pr (E_{3}) \\
    &amp;&amp;-\Pr (E_{1}\cap E_{2})-\Pr (E_{1}\cap E_{3})-\Pr (E_{2}\cap E_{3}) \\
    &amp;&amp;+\Pr (E_{1}\cap E_{2}\cap E_{3})\\
    &amp;=&amp; \frac{3}{12} + \frac{4}{12} + \frac{6}{12} - \frac{0}{12} - \frac{2}{12} - \frac{2}{12} + \frac{0}{12}\\
    &amp;=&amp; \frac{9}{12} = 0.75  
\end{eqnarray*}\]</span></p>
</section>
<p>Similar concepts apply when manipulating proportions as demonstrated in the next example.</p>
<section id="example-2" class="level4 callout-info" data-number="7.3.2.3">
<h4 data-number="7.3.2.3" class="anchored" data-anchor-id="example-2"><span class="header-section-number">7.3.2.3</span> Example</h4>
<p>A sample of 1000 science undergraduates were asked whether they took either Mathematics (M), Physics (P) or Chemistry (C) at A-level. All of them took at least one of the three subjects at A-level. The following responses were obtained: 100 just took Mathematics; 70 just took Physics; 100 just took Chemistry; 150 took Mathematics and Physics, but not Chemistry; 40 took Mathematics and Chemistry, but not Physics; and, 240 took Physics and Chemistry, but not Mathematics. What proportion took all three?</p>
<p>This can be addressed with the following diagram:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Prob_Alevels.jpg" class="img-fluid figure-img"></p>
<figcaption>Venn diagram for A level example.</figcaption>
</figure>
</div>
<p>The shaded area contains the number who took all three, which can be deduced from the above information (since the total of the numbers assigned to each part of the Venn diagram must be 1000). The numbers in all areas but for the shaded area sum to 700. The answer is therefore <span class="math inline">\(30\%\)</span> as 300 out of 1000 have to be in the shaded center area.</p>
</section>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercises
</div>
</div>
<div class="callout-body-container callout-body">
<p>To calculate the above solution you can also refer to the previous formula:</p>
<p><span class="math display">\[\begin{equation*}
    \Pr(M\cup P\cup C) =\Pr(M)+\Pr(P)+\Pr(C) -\Pr(M\cap P)-\Pr(M\cap C)-\Pr(P\cap C) +\Pr(M\cap P\cap C)
\end{equation*}\]</span></p>
<p>What is <span class="math inline">\(\Pr(M\cup P\cup C)\)</span>?</p>
<p>Answer: <span class="math inline">\(\Pr(M\cup P\cup C)=1\)</span></p>
<p>Feedback: <span class="math inline">\(\Pr(M\cup P\cup C)=1\)</span> is, in the context of this question, the sample space. Note that all students have taken at least one of these three subjects.</p>
<p>The information in the problem says that 70 (out of the 1000) students only took Physics. Which probability is that? Note, as usual, <span class="math inline">\(S\)</span> represents the sample space.</p>
<ul>
<li>A: <span class="math inline">\(\Pr(M\cap P)\)</span></li>
<li>B: <span class="math inline">\(\Pr(P)\)</span></li>
<li>C: <span class="math inline">\(\Pr(\bar{M}\cap \bar{C} \cap P)\)</span> (T)</li>
<li>D: <span class="math inline">\(1 - \Pr(C \cup M)\)</span> (T)</li>
<li>E: <span class="math inline">\(Pr(P) - \Pr(C \cup M)\)</span></li>
</ul>
<p>Note which answer. Multiple correct answers are possible. Seperate multiple answers by comma. <code>rfitb(c("C,D", "C, D", "D,C","D, C"))</code></p>
</div>
</div>
<p>Two further results on unions, intersections and complements which are of use (and which are fairly easy to demonstrate using Venn diagrams) are <strong>de Morgan Laws</strong>:</p>
<ul>
<li><p>$ {A}{B} =( ) $</p></li>
<li><p>${A}{B}=( ) $</p></li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercises
</div>
</div>
<div class="callout-body-container callout-body">
<p>One hundred students were surveyed about their preference between Math and Statistics. The following two-way table displays data for the sample of students who responded to the survey.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>extbf{Preference}</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prefers Math</td>
<td>22</td>
<td>18</td>
<td>40</td>
</tr>
<tr class="even">
<td>Prefers Statistics</td>
<td>25</td>
<td>12</td>
<td>37</td>
</tr>
<tr class="odd">
<td>No preference</td>
<td>8</td>
<td>15</td>
<td>23</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>55</td>
<td>45</td>
<td>100</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Find the probability that a randomly selected student prefers Math. Enter your answer as a or decimal.</li>
</ol>
<p>P(prefers Math) = <input class="webex-solveme nospaces" size="3" data-answer="[&quot;0.4&quot;,&quot;.4&quot;]"></p>
<ol start="2" type="1">
<li><p>In this sample, are the events “prefers Math” and “prefers Statistics” mutually exclusive? <select class="webex-select"><option value="blank"></option><option value="answer">Yes</option><option value="">No</option><option value="">Can’t say</option></select></p></li>
<li><p>Find the probability that a randomly selected student prefers Math or prefers Statistics.</p></li>
</ol>
<p>P(prefers Math or Statistics) = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.77&quot;,&quot;.77&quot;]"></p>
<ol start="4" type="1">
<li><p>In this sample, are the events “prefers Statistics” and “male” mutually exclusive? <select class="webex-select"><option value="blank"></option><option value="">Yes</option><option value="answer">No</option><option value="">Can’t say</option></select></p></li>
<li><p>Find the probability that a randomly selected student prefers Statistics or is male.</p></li>
</ol>
<p>P(prefers Statistics or is male) = <input class="webex-solveme nospaces" size="4" data-answer="[&quot;0.67&quot;,&quot;.67&quot;]"></p>
<section id="additional-resources" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="additional-resources"><span class="header-section-number">7.4</span> Additional Resources</h2>
<p>Khan Academy</p>
<ul>
<li><a href="https://www.khanacademy.org/math/statistics-probability/probability-library/addition-rule-lib/v/probability-with-playing-cards-and-venn-diagrams">Basic Probability and Venn Diagram</a></li>
<li><a href="https://www.khanacademy.org/math/probability/independent-dependent-probability/addition_rule_probability/v/addition-rule-for-probability">Addition Rule</a></li>
</ul>


</section>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script src="include/webex.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./DealingWithDataSets.html" class="pagination-link" aria-label="Dealing with real life datasets">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dealing with real life datasets</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ConditionalProbability.html" class="pagination-link" aria-label="Conditional Probability">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>